### ISSUE TITLE
EventLoopFuture.map should supports throws on closure

### ISSUE THREAD

**Issue by omochi** [apple/swift-nio#1011]
In comment for `map`, it can treats error.

```
    /// Operations performed in `map` should not block, or they will block the entire event
    /// loop. `map` is intended for use when you have a data-driven function that performs
    /// a simple data transformation that can potentially error.
```

### Expected behavior

```swift
    public func map<NewValue>(file: StaticString = #file, line: UInt = #line, _ callback: @escaping (Value) throws -> (NewValue)) -> EventLoopFuture<NewValue> {
```

### Actual behavior

```swift
    public func map<NewValue>(file: StaticString = #file, line: UInt = #line, _ callback: @escaping (Value) -> (NewValue)) -> EventLoopFuture<NewValue> {
```

Difference is type of `callback`.

### Steps to reproduce

This is current code.

https://github.com/apple/swift-nio/blob/c59c193ea7fd2ac0f8819e7f1fc8c47a2e60eca7/Sources/NIO/EventLoopFuture.swift#L547

### SwiftNIO version/commit hash

master

**Comment by Lukasa** [comment]
Sorry, that's our fault: the comment is wrong. It got incorrectly reproduced from the place it belongs, which is `flatMapThrowing`. `flatMapThrowing` is also the function you actually want to call here.

**Comment by Lukasa** [comment]
See #1012 for the removal of that comment.

**Comment by omochi** [comment]
OK. thanks.
