### ISSUE TITLE
Cocoapod release updates

### ISSUE THREAD

**Issue by MoveUpwardsDev** [apple/swift-nio#1017]
### Expected behavior
Have Cocoapod release inline with the library release

### Actual behavior
Actual Cocoapod version:

Using SwiftNIO (2.1.0)
Using SwiftNIOConcurrencyHelpers (2.1.0)
Using SwiftNIOFoundationCompat (2.1.0)
Using SwiftNIOTLS (2.1.0)
Using SwiftNIOTransportServices (1.0.2)

### Steps to reproduce

1. Update podfile
2. pod update

**Comment by weissi** [comment]
sorry, will do that tonight

**Comment by MoveUpwardsDev** [comment]
@weissi thanks.

**Comment by weissi** [comment]
ok, script for SwiftNIO is running so within the next 20min or so it should have validated and uploaded all those pods

**Comment by weissi** [comment]
- [ ] SwiftNIO (2.1.0)
- [ ]  SwiftNIOConcurrencyHelpers (2.1.0)
- [ ]  SwiftNIOFoundationCompat (2.1.0)
- [ ]  SwiftNIOTLS (2.1.0)
- [ ]  SwiftNIOTransportServices (1.0.2)

**Comment by weissi** [comment]
@MoveUpwardsDev  I believe that's all done. Please confirm that it works for you :)

**Comment by MoveUpwardsDev** [comment]
Cocoapod is now up to date.

Do you plan in the future to automatically create cocoapod release along with a new github release ?

**Comment by weissi** [comment]
> Do you plan in the future to automatically create cocoapod release along with a new github release ?

Unfortunately, I can't get cocoapods to work on my work machine so I always need to do it at home :P. Automating that will be tough

**Comment by MoveUpwardsDev** [comment]
What about CI through Travis or Bitrise.

We have setup a automatic release on cocoapod trunk repo based on github release. Very handy :)

**Comment by weissi** [comment]
@MoveUpwardsDev https://developer.apple.com/documentation/swift_packages
