### ISSUE TITLE
Getting Crash on Release Mode and reported by Apple

### ISSUE THREAD

**Issue by ranmyfriend** [apple/swift-nio#1031]
When we are running on Release Mode App is getting crash due to Swift NIO. Sorry for the blaming. Please have a look at the Crash Report.

It clearly says: CNIOLinux Framework not Loaded

`Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, Library not loaded: @rpath/CNIOLinux.framework/CNIOLinux | Referenced from: /var/containers/Bundle/Application/4F413213-073D-41FA-AF10-1EDEC4AC5D2A/*****.app/***** | Reason: no suitable image found.  Did find: | /private/var/containers/Bundle/Application/4F413213-073D-41FA-AF10-1EDEC4AC5D2A/*******.app/Frameworks/CNIOLinux.framework/CNIOLinux: mremap_encrypted() => -1, errno=12 for /private/var/containers/Bundle/Application/4F413213-073D-41FA-AF10-1EDEC4AC5D2A/*****.app/Frameworks/CNIOLinux.framework/CNIOLinux
Triggered by Thread:  0`

I have already heard one of your main contributors Swift-NIO Works very well on Release modes. But now I don't know, Why am I getting this crash. Because of this crash, we are stopped our App Release :(

We want some idea like, Should we need to do anything special for Swift NIO on Release Mode.

**Enviornment Details**
iOS 12.3.1 (16F203)
iPhone X

Thanks
Ranjith

**Comment by Lukasa** [comment]
No special steps should be required here. In your install process are you copying the CNIOLinux framework into your app?

**Comment by MobileMatrix** [comment]
> No special steps should be required here. In your install process are you copying the CNIOLinux framework into your app?

I am embedding framework in application.

**Comment by Lukasa** [comment]
And there are no meaningful differences between your release binary’s install and linking process and the distribution binary?

**Comment by weissi** [comment]
@ranmyfriend / @MobileMatrix any updates here? There is nothing special that should be required for SwiftNIO in release mode at all.

How are you depending on SwiftNIO? Via the Xcode Packages support or via CocoaPods or via dragging in the project into your xcodeproj?

**Comment by ranmyfriend** [comment]
Thanks for your support @weissi  @Lukasa The issue is addressed and it was from our end

**Comment by sehajc** [comment]
@ranmyfriend I'm experiencing the same issue on release mode. Could you please tell me how you resolved it?

**Comment by ranmyfriend** [comment]
@sehajc there was an issue from our end and not from NIO side. So we have fixed it. But am also saying NIO works well in debug as well as Release Mode. If you are facing any issue specifically please describe more about the issue and let us know.

**Comment by sehajc** [comment]
@ranmyfriend Thanks. I understand it's not an issue from NIO side. We are using Carthage instead of swift package manager as our dependency manager. We get a crash in release mode(on iOS 12), the same as yours "Reason: no suitable image found." for "CNIOLinux".
My guess is that we are not setting up the .xcodeproj correctly but we haven't been able to figure it out yet

**Comment by ranmyfriend** [comment]
@sehajc Okay let me explain to you what we faced and how we resolved it. So initially we were used Swift NIO using Carthage but the way we wanted in a private framework which has a dependency for NIO. But here is the catch it was giving some problem, So we went with Cocoapods. Like we built our own framework and added Swift-NIO as dependency there. then it solved our issues and even it works well. Why dont you try the same approach on your project. And can you please confirm me? Are you using Swift NIO directly to your project or via custom framework?

**Comment by sehajc** [comment]
@ranmyfriend Thanks. That's very helpful. We are trying the private framework approach as well. Using swift package manager to generate xcodeproj for swift-nio project and then using carthage to build all NIO frameworks. We are making sure to link all the NIO frameworks built with Carthage into the app, not just the private framework. We'll keep on trying with Carthage or eventually switch to SPM for swift-nio.

Unfortunately the project I'm working on is a couple years old with lots of dependencies and we rely heavily on Carthage so switching to Cocoapods is a no-go. 

Thanks again for your help
