### ISSUE TITLE
switch atomics to use ManagedBuffer

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1039]
I'm pretty sure we can use ManagedBuffer(Pointer) to implement the atomics to save one allocation per atomic.

Currently, how this works is:

`class Atomic*` holds `struct UnsafeEmbeddedAtomic` which holds an `OpaquePointer` to raw memory that we use the the C atomics. From from a given use site, we have two layers of indirection

```
[use site] -> [Atomic class] -> [raw memory for the atomic]
```

with `ManagedBuffer(Pointer)` we could however allocate the raw memory together with the `Atomic*` class instance and whilst it would still technically be two layers of indirection, it's really only one because the second one is a (small) offset from the beginning of the class. So essentially we'd be saving one allocation and one possible cache miss.

**Comment by weissi** [comment]
This is something that can be done with medium to advanced Swift knowledge but pretty much without any NIO knowledge at all.

If there are any questions regarding what this actually means, please reach out.

**Comment by 2bjake** [comment]
I'm interested in doing this one but I need more detail.

Is the idea that ```Atomic``` would still use ```UnsafeEmbeddedAtomic``` but the space for the underlying atomic is allocated by ```Atomic.init``` and stored as a property?

One way I could imagine doing this is have ```Atomic.init``` make the ```T.atomic_create(value)``` call and pass the result to a new ```UnsafeEmbeddedAtomic.init(pointer: OpaquePointer)```. This doesn't seem great though, since there's no enforcement that ```pointer``` is pointing to an ```AtomicPrimitive```.

I'm guessing this is where ```ManagedBuffer``` comes in, but I'm not understanding how it should be used. Or maybe I'm just completely misunderstanding the intention! :)

Can you explain a bit more about how you see this being implemented?

**Comment by weissi** [comment]
Hi @2bjake, great to hear you're interested taking this issue.

At the moment, we need two allocations for every atomic:

1. for the [`class Atomic<T>`](https://github.com/apple/swift-nio/blob/master/Sources/NIOConcurrencyHelpers/atomics.swift#L156)
2. the [`malloc`](https://github.com/apple/swift-nio/blob/master/Sources/CNIOAtomics/src/c-atomics.c#L30) for the underlying storage

If however we would use [`ManagedBuffer`](https://developer.apple.com/documentation/swift/managedbuffer) or [`ManagedBufferPointer`](https://developer.apple.com/documentation/swift/managedbufferpointer) we should be able to allocate the class instance (which we need for lifecycle management) and the storage for the actual atomic in only one allocation because `ManagedBuffer(Pointer)` support tail allocating some extra storage which is all we need.

Implementation-wise, we have two options:

1. We make `Atomic<T>` subclass `ManagedBuffer<Void, T.CWrapperType>` which would mean we could keep the existing API but unfortunately would get some extra methods on `Atomic<T>` that we don't really want
2. Make a new `struct FastAtomic<T>` which uses `ManagedBuffer` or `ManagedBufferPointer` (probably the latter) and doesn't reveal it's own implementation.

In the `CAtomics` module, we'll likely need a new function like

```
*/ struct catmc_atomic_##type *catmc_atomic_##type##_create_with_existing_storage(void *storage, type value) { /*
*/     atomic_init(storage->value, value); /*
*/     return storage; /*
*/ } /*
```

which allows us to initialise a new C atomic using existing storage (which is a pointer to the tail allocated storage of the class).

I'm not sure if all of this makes sense and really answers your questions so please keep asking which bits are unsure.

**Comment by 2bjake** [comment]
Thanks so much for providing this explanation. This is all new to me (which is why I wanted to tackle it!) I think I've got it now. I've got a version that is passing tests that looks like this:

```swift
public class FastAtomic<T: AtomicPrimitive> {
    @usableFromInline
    typealias Manager = ManagedBufferPointer<Void, T>

    /// Create an atomic object with `value`
    @inlinable
    static func withValue(_ value: T) -> FastAtomic {
        let ptr = Manager(bufferClass: self, minimumCapacity: 1) { buffer, _ in
            Manager(unsafeBufferObject: buffer).withUnsafeMutablePointerToElements { atomicPtr in
                //temporary, should actually pass atomicPtr to catmc_atomic_##type##_create_with_existing_storage(void *storage, type value)
                atomicPtr.initialize(from: UnsafePointer(T.atomic_create(value)), count: 1)
            }
        }
        return unsafeDowncast(ptr.buffer, to: FastAtomic<T>.self)
    }

    @inlinable
    public func compareAndExchange(expected: T, desired: T) -> Bool {
        return Manager(unsafeBufferObject: self).withUnsafeMutablePointerToElements {
            return T.atomic_compare_and_exchange(OpaquePointer($0), expected, desired)
        }
    }

    @inlinable
    public func add(_ rhs: T) -> T {
        return Manager(unsafeBufferObject: self).withUnsafeMutablePointerToElements {
            return T.atomic_add(OpaquePointer($0), rhs)
        }
    }

   //...

    deinit {
        Manager(unsafeBufferObject: self).withUnsafeMutablePointers {
            (pointerToHeader, pointerToElements) -> Void in
            pointerToElements.deinitialize(count: 1)
            pointerToHeader.deinitialize(count: 1)
        }
    }
}
```

Does this line up with what you were describing for option 2? Is it expected that ```FastAtomic```s would be created with a static function rather than an init?

**Comment by 2bjake** [comment]
I've got a version that is using ```catmc_atomic_##type##_create_with_existing_storage```. The only part I'm not sure about is how to set the buffer's element type to ```T.CWrapperType```. I tried adding a CWrapper typealias to the AtomicPrimitives but the ```catmc_atomic_##type``` types aren't visible on the Swift side.

Any thoughts on how to do this?

**Comment by 2bjake** [comment]
Answering my own questions. :p I got this working by moving the struct definitions into the header. However, this won't be backward compatible as now the atomic methods take ```UnsafeMutablePointer<catmc_atomic_##type>``` instead of ```OpaquePointer```, which causes the ```AtomicPrimitive``` protocol to change. I guess I could create "fast" versions of all these APIs as well.

**Comment by weissi** [comment]
@2bjake this looks awesome! I think given that you won't need to change the API, couldn't `FastAtomic` now just be `Atomic`?

**Comment by 2bjake** [comment]
Unfortunately the API does change in a few places:
- The ```ManagedBufferPointer```-based ```Atomic``` class doesn't have an ```init```, it is constructed with a static function.
- The ```AtomicPrimitive``` protocol needs an ```AtomicWrapper``` (what you called ```T.CWrapperType```) associatedtype and a new ```atomic_create_with_existing_storage method``` added (these could be added to a new protocol instead, but then the ```Atomic``` class would have to be generic over a type that also conforms to that new protocol)
- To specify the ```AtomicWrapper``` typealiases, the c structs can't be incomplete in the CNIOAtomics header. However, when fully defining the structs in the header, the generated Swift interface for the methods change. ```OpaquePointer```s become ```UnsafeMutablePointer<catmc_atomic_##type>```s. This also causes the ```AtomicPrimitive``` protocol to change.

I'm working on a ```FastAtomic``` version at the moment that is unique all the way down to the C layer (```Atomic```, ```AtomicPrimitive```, ```catmc_atomic_*```). "fast" is probably not the right name at the C layer, but it does make sense to have it be separate from the existing version. In the existing C layer implementation, the pointer is opaque and the user is required to call ```destroy```. In the new version, the pointer is not opaque, the user is responsible for allocating and deallocating the memory, and there shouldn't be a ```destroy``` function.

That said, it is annoying how much code duplication there is... I'm hoping to get this into a PR today so you can take a look and let me know what you think.
