### ISSUE TITLE
ByteBuffer.clear(minimumCapacity:) API

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1057]
We should have an API in `ByteBuffer` that works like `clear` but requests at least `minimumCapacity` bytes. The use for that is if the current buffer is uniquely referenced, it'll just be cleared (followed by `reserveCapacity`) but if the current buffer is not uniquely referenced, then we'd allocate a new one with `minimumCapacity`.

**Comment by weissi** [comment]
This could be a good first issue. The only NIO knowledge that's required would be basic `ByteBuffer` usage. If this issue sounds attractive, please comment here and we can give much more information.

The basic idea is that often it's beneficial to re-use an existing `ByteBuffer` if that doesn't cause a copy-on-write copy (regardless of the size of the existing `ByteBuffer`). If it would cause a copy-on-write copy however it's often beneficial to allocate a new `ByteBuffer` of _the right size_ rather than the size of the one that happens to be around.

**Comment by akshay1992kalbhor** [comment]
Hey Johannes, has this been assigned to anyone? If not can I take a shot at this? It will be my first contribution to this repo!

**Comment by weissi** [comment]
hi @akshay1992kalbhor , thanks for reaching out! No this hasn't been assigned to anybody yet. Please feel free to assign it to yourself. And please reach out if there's anything we can help with :)

**Comment by akshay1992kalbhor** [comment]
Thanks. I think I have a fairly good understanding of how ByteBuffer works and the first two comments will hopefully allow me to start working on this one. Is there anything else I should know before starting?

**Comment by akshay1992kalbhor** [comment]
Also, I don't have permission to assign the issue to myself. Can someone help me with that?

**Comment by weissi** [comment]
Thank you and done!

**Comment by weissi** [comment]
Don’t think there’s anything else to know if the issue makes sense to you

**Comment by weissi** [comment]
@akshay1992kalbhor are you still working on this?

**Comment by kam800** [comment]
I will work on that.

**Comment by Keno42** [comment]
I'm working on it, too.

**Comment by Lukasa** [comment]
Resolved by #1204, with the work done collaboratively by @keno42, @kam800, and @cweinberger. Great work all!
