### ISSUE TITLE
Consider adding example usage for Server apps

### ISSUE THREAD

**Issue by jkmathew** [apple/swift-nio#107]
It would be better if there is usage examples for 
```
NIOChatClient
NIOEchoClient
NIOHTTP1Server
NIOEchoServer
```

**Comment by Lukasa** [comment]
Yeah, that seems reasonable. Would a comment at the top of the source files suffice?

**Comment by jkmathew** [comment]
It would be great if there is a Readme in corresponding folder.

**Comment by karim-elngr** [comment]
How about adding example projects to serve as a quick start point? @Lukasa
