### ISSUE TITLE
WebSocket handler Thread affinity

### ISSUE THREAD

**Issue by allright** [apple/swift-nio#1073]
Ability to create new WebSocket handler on specific eventLoop.
For example, we have several WebSocketHandler, which can share common data without locks, due to use the same thread eventLoop.

**Comment by Lukasa** [comment]
It is not really accurate to think of a handle being created "on" an event loop. The thread safety semantics of any given handler are entirely up to that handler.

If you want to share data between handlers without locks, you need to take user action to ensure that you only create handlers on the same loop. The common way to do that for server connections is to restrict your event loop group size to be only one loop. For clients, you can take advantage of the fact that `EventLoop` conforms to `EventLoopGroup`.

Regardless, I don't think any NIO changes are required to achieve your goal.
