### ISSUE TITLE
SwiftNIO in Playground

### ISSUE THREAD

**Issue by amitahire** [apple/swift-nio#1112]
### Expected behavior
Use Import NIO and import NIOTransportServices in the playground 

### Actual behavior
NIO and NIOTransportServices are not listed in the playground

### Steps to reproduce
I followed instrcutions from this link - https://forums.swift.org/t/cant-experiment-swiftnio-in-playground/15020/4

Using Xcode Version 11.0 beta 5 (11M382q)
1. Create a new Xcode project for macOS
2. pod init
3. edit Podfile and put

POD File 
```
target 'ByteBuffer_Swift_NIO' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ByteBuffer_Swift_NIO
  pod 'SwiftNIO'
  pod 'SwiftNIOTransportServices'

end
```

8. pod install
9. close the Xcode project
10. open the Xcode workspace created by Cocoapods
11. File -> New -> Playground, select Blank
12. put import NIO and probably import NIOTransportServices in the playground
13. and you're done :)

===

> After that you can run swift package generate-xcodeproj inside SwiftNIO and drag the generated Xcode projects into any of your Xcode projects and it will work. It will also work in a playground

This also doesnt work. I drag the generated swift-nio.xcodeproj in the any other xcode project but modules are not recognized. 

### Swift & OS version (output of `swift --version && uname -a`)
Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
Target: x86_64-apple-darwin18.6.0

**Comment by Lukasa** [comment]
Try adding `pod 'SwiftNIO'` and `pod 'SwiftNIOTransportServices'` to the root of the pod file. I think dragging xcodeprojects around makes things get a bit weird with targets.

> This also doesnt work. I drag the generated swift-nio.xcodeproj in the any other xcode project but modules are not recognized.

Can you elaborate on what happens here?

**Comment by amitahire** [comment]
> Try adding pod 'SwiftNIO' and pod 'SwiftNIOTransportServices' to the root of the pod file. I think dragging xcodeprojects around makes things get a bit weird with targets

Scenario - 1 :
In the pod test project - I did not drag any xcodeproj - but just generated with `pod install` and then tried creating the playground project as described. 

> This also doesn't work. I drag the generated swift-nio.xcodeproj in the any other xcode project but modules are not recognized.
> 
> Can you elaborate on what happens here?

Scenario - 2 :
Created swift-nio project with `swift package generate-xcodeproject` and then dragged and dropped the `swift-nio.xcodeproj` into a new xcodeproj (not built from pods) but from xcode > File > New > Project  

Then created new playground but still  I do not get any of NIO modules in the import list.

**Comment by weissi** [comment]
@amitahire Apologies. I just tried with Xcode 11 beta 7 and it still works. I also made a [screen recording](https://www.dropbox.com/s/xt5l0r7w4twaqa5/small-rec.gif?dl=0).

**Comment by weissi** [comment]
@amitahire can you confirm that this works for you too?

**Comment by amitahire** [comment]
Thanks for replying back. It works now!
