### ISSUE TITLE
Figure out: Initialiser or options first

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1114]
swift-nio does initialiser, then channel options. NIOTS does the opposite. We need to figure out what’s right and write tests.

CC @normanmaurer

**Comment by weissi** [comment]
Talked to Norman, options first, then initialiser

**Comment by weissi** [comment]
@normanmaurer to also check netty

**Comment by normanmaurer** [comment]
@weissi just double checked... We do the same (first options then initialiser) in netty.
