### ISSUE TITLE
A few minor refactoring suggestions.  

### ISSUE THREAD

**Issue by ravikandhadai** [apple/swift-nio#1117]
1. https://github.com/apple/swift-nio/blob/5224cfbfd74f0ca4dc3b31dcd338a6fdf4904d80/Sources/NIOPerformanceTester/main.swift#L55

`reduce(into:)` is more performant on COW types than reduce. 

2. https://github.com/apple/swift-nio/blob/5224cfbfd74f0ca4dc3b31dcd338a6fdf4904d80/Sources/NIO/HappyEyeballs.swift#L452

https://github.com/apple/swift-nio/blob/5224cfbfd74f0ca4dc3b31dcd338a6fdf4904d80/Sources/NIO/HappyEyeballs.swift#L491

https://github.com/apple/swift-nio/blob/5224cfbfd74f0ca4dc3b31dcd338a6fdf4904d80/Sources/NIO/HappyEyeballs.swift#L519

`pendingConnections.count == 0` can be replaced with `pendingConnections.isEmpty` which would have more consistent performance even if the underlying collection changes from Array.

**Comment by weissi** [comment]
Thank you @ravikandhadai , fixed in #1118
