### ISSUE TITLE
Consider convenience option for bindTimeout

### ISSUE THREAD

**Issue by ktoso** [apple/swift-nio#1135]
### Expected behavior

Server bootstrap may want to allow setting a timeout on binding.

### Actual behavior

a) no such setting "bind timeout"
b) when one would try to use a connect timeout on a server bootstrap that's a fatal error (if we did a bind timeout, this could suggest "instead use BindTimeoutOption" perhaps; 

### Discussion

- So this isn't really critical, one can do the timeout manually on the future;
- The bind() operation seems to be blocking anyway, just that NIO provides a helper to prepare it, so it could allow preparing the same style of timing out a bind as it does for a connect (`.serverChannelOption(ChannelOptions.connectTimeout, value: timeout)`)
- other transports, NIOTS perhaps can _actually_ implement such timeout properly?

Nothing urgent, but thought it's a small inconsistency.

**Comment by Lukasa** [comment]
Yeah, this isn't too hard, we can do that. [NIOTS already has such a feature](https://github.com/apple/swift-nio-transport-services/pull/54) so we could just port it back to here. Going to suggest this as a contributor task.

**Comment by Davidde94** [comment]
Resolved in #1349
