### ISSUE TITLE
WebSocketFrameEncoder should optimistically see if it can write the web socket header to the front of the provided frame buffer.

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio#1150]
Right now the WebSocketFrameEncoder writes a `ByteBuffer` that is of between 2 and 10 bytes to contain the frame header before it writes the `ByteBuffer` for the WS frame.

This adds an extra write cost and potentially new allocations in cases where we likely don't need it. The WebSocketFrameEncoder should investigate whether there are enough free bytes at the start of the buffer to write the frame header and, if it can, to write the frame header into the buffer. That should avoid some extra write traffic.

**Comment by weissi** [comment]
@Lukasa do we now finally need a `mutating get canBeWrittenToProbablyWithoutTriggeringCoW: Bool { return isKnownUniquelyReferenced(self._storage) }

**Comment by Lukasa** [comment]
For performance reasons it’d be nice.

**Comment by weissi** [comment]
@Lukasa didn't you make a patch for this?

**Comment by Lukasa** [comment]
I didn’t finish it yet.

**Comment by Lukasa** [comment]
This is done.
