### ISSUE TITLE
NIO should crash on EBADF in release mode

### ISSUE THREAD

**Issue by kevints** [apple/swift-nio#1156]
Certain POSIX error numbers mean the NIO program is broken beyond repair and should crash. One such value is EBADF, which indicates that the file descriptor that NIO passed to the kernel is invalid for some reason. [SR-11557](https://bugs.swift.org/browse/SR-11557) was discovered in part because debug builds of NIO crash for this. I don't see any reason why release builds shouldn't crash for this error as well, i.e. we should promote this check from an assertion to a precondition.

**Comment by Lukasa** [comment]
Resolved by #1201.
