### ISSUE TITLE
Extend ByteBufferView to be a MutableCollection and a RangeReplaceableCollection

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio#1160]
When we added `ByteBufferView` (#411), @weissi and I thought that we couldn't make it mutable because it would inevitably CoW. This is because the way you build `ByteBufferView` objects is as constructed objects from a `ByteBuffer` (i.e. via `ByteBuffer.viewBytes(at:length:)` or `ByteBuffer.readableBytesView`), and as a result the original buffer still exists and holds a reference to the backing storage.

What we missed is that this can be enabled by adding a `ByteBufferView.init()` function that takes a `ByteBuffer` as its argument. In this mode the `ByteBufferView` would take ownership of the `ByteBuffer` entirely, including the writable bytes, and could therefore appropriately conform to the mutable protocols. This also creates proper bidirectional conversion between `ByteBuffer` and `ByteBufferView`, which is handy when interoperating with algorithms written generically over the Swift Collection types.

To make this work, we'd need to do a few things:

1. Add the appropriate initializer.
2. Extend `ByteBufferView` to have an idea that it may hold a slice larger than its range.
3. Implement `MutableCollection` and `RangeReplaceableCollection` for `ByteBufferView`.
4. Write tests verifying that, when using this API on the happy path, we don't incur CoW operations.
5. (optional, extension) Extend `NIOFoundationCompat` so that `ByteBufferView` conforms to `MutableDataProtocol` as well.

**Comment by glbrntt** [comment]
Unfortunately the Swift compiler is not on our side and we'll still incur a CoW at the moment: https://bugs.swift.org/browse/SR-11675

Is this something we still want to pursue at this time?

**Comment by Lukasa** [comment]
I think it is: the failure of this in the trivial case is annoying, but I suspect if the creation and use are separated by enough space the compiler may correctly do the right thing.
