### ISSUE TITLE
Question: When asserted by invokeWrite in CodePipeline

### ISSUE THREAD

**Issue by iq3addLi** [apple/swift-nio#1185]
Excuse me. 
I'm using SwiftNIO via Vapor. My application is asserted with [the invokeWrite function in CodePipeline.swift](https://github.com/apple/swift-nio/blob/1.14.1/Sources/NIO/ChannelPipeline.swift#L1402).
I'm investigating the cause and would appreciate a hint. 
1. If asserted here, what is generally considered to be happening?
2. Also, What risks are there if debugOnly is bypassed by an optimized build?

[Added] 
1 is how can I return false [here](https://github.com/apple/swift-nio/blob/1.14.1/Sources/NIO/Thread.swift#L116)? I might be paraphrased so.

### SwiftNIO version/commit hash

```swift
      {
        "package": "swift-nio",
        "repositoryURL": "https://github.com/apple/swift-nio.git",
        "state": {
          "branch": null,
          "revision": "ba7970fe396e8198b84c6c1b44b38a1d4e2eb6bd",
          "version": "1.14.1"
        }
      },
```

### Swift & OS version (output of `swift --version && uname -a`)

```
$ swift --version && uname -a
Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)
Target: x86_64-apple-darwin18.7.0
Darwin <*>.local 18.7.0 Darwin Kernel Version 18.7.0: Tue 
```

**Comment by Lukasa** [comment]
If you hit this assertion your code is not thread safe: either you or Vapor are writing to a `ChannelPipeline` without thread safety.

**Comment by Lukasa** [comment]
You can try running with `—sanitize=thread` to get more information.

**Comment by iq3addLi** [comment]
@Lukasa 
Thanks for your advice! 🙏
I specified `-Ounchecked` and enabled Thread Sanitizer from Xcode.
As expected, precondition () is no longer valid. So far I have not received any warnings from Sanitizer.

I was able to continue development. Thank you.
If I know anything about the cause of the problem, write it here.😁

**Comment by weissi** [comment]
@iq3addLi Thread Sanitizer can't show you all thread unsafety unfortunately. If you hit this assertion, there is _definitely_ thread unsafety. If you show a us a stack trace from when you hit the assertion, we might be able to pin point where the problem is. Just running with `-Ounchecked` to hide this bug _will definitely_ cause undefined behaviour.

**Comment by iq3addLi** [comment]
The previous comment was halfway because I had to move🚙
Swift + Vapor implementation at https://realworld.io/ will be released soon.
Implementation of business logic is complete.
It will be the largest sample code of Swift + Vapor💧
