### ISSUE TITLE
NIO makes it _incredibly_ hard to change a port number on a given socket address

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1189]
if we want to set the port number on a given `SocketAddress` we need to use code like this which is really dodgy and outright wrong if we don't know it's an IPv4 address:

```
let destAddress = en0Interface.broadcastAddress?.withSockAddr { (ptr, size) -> sockaddr_in in
    // this is terrible code making fragile assumptions just to change a port number :(
    precondition(size == MemoryLayout<sockaddr_in>.size)
    return ptr.withMemoryRebound(to: sockaddr_in.self, capacity: 1) { ptr in
        var newAddress = sockaddr_in()
        newAddress = ptr.pointee
        newAddress.sin_port = in_port_t(destPort).bigEndian
        return newAddress
    }
}
```

we need to fix this.

**Comment by Lukasa** [comment]
Fixing this should be straightforward enough for anyone with Swift experience.

**Comment by weissi** [comment]
Agreed. My API proposal would be to make `port` settable too. Only question is: What do we do if the address is a Unix Domain Socket? Ignore port or hard crash? CC @glbrntt / @Lukasa ?

**Comment by Lukasa** [comment]
I'd normally say crashing is fine, but given that `port` is already optional to cover this case I'd say we should only crash if it's being set to a non-`nil` value.

**Comment by weissi** [comment]
Agreed, sounds good to me!

**Comment by glbrntt** [comment]
Sounds totally reasonable!

**Comment by Lupurus** [comment]
> Agreed. My API proposal would be to make `port` settable too. Only question is: What do we do if the address is a Unix Domain Socket? Ignore port or hard crash? CC @glbrntt / @Lukasa ?

I looked at the code, but the point is: `address` is read-only. So even we make it settable or it's necessary to make a new `SocketAddress`. I came up with this code for the moment:

```
    public var port: Int? {
        get {
            switch self {
            case .v4(let addr):
                // looks odd but we need to first convert the endianness as `in_port_t` and then make the result an `Int`.
                return Int(in_port_t(bigEndian: addr.address.sin_port))
            case .v6(let addr):
                // looks odd but we need to first convert the endianness as `in_port_t` and then make the result an `Int`.
                return Int(in_port_t(bigEndian: addr.address.sin6_port))
            case .unixDomainSocket:
                return nil
            }
        }
        set {
            switch self {
            case .v4(let addr):
                var sin_address = addr.address
                sin_address.sin_port = in_port_t(newValue!).bigEndian
                self = SocketAddress(sin_address, host: addr.host)
            case .v6(let addr):
                var sin_address6 = addr.address
                sin_address6.sin6_port = in_port_t(newValue!).bigEndian
                self = SocketAddress(sin_address6, host: addr.host)
            case .unixDomainSocket(_):
                fatalError("fatalError: Cannot set the port of a unix domain socket.")
                // TODO: How can I make a Test on this?
            }
        }
    }
```

**Comment by Lupurus** [comment]
> Agreed. My API proposal would be to make `port` settable too. Only question is: What do we do if the address is a Unix Domain Socket? Ignore port or hard crash? CC @glbrntt / @Lukasa ?

If we make `port` settable, should we also make the new `ipAddress` mutable? Maybe not, because `SocketAddress(ipAddress: ...` can throw (and the throwable setters are not yet implemented).

**Comment by siemensikkema** [comment]
I'll be working on this

**Comment by Lupurus** [comment]
Ah, you were faster! Cool 😎

But @ all: what do you think about my last comment? Should ipAddress also be settable? I would say no, but it’s better to discuss it :)

**Comment by Lukasa** [comment]
I’m inclined to say that it should be settable via a mutating function, which will be allowed to throw.
