### ISSUE TITLE
Improve memory handling on `ByteBuffer.clear`

### ISSUE THREAD

**Issue by kam800** [apple/swift-nio#1202]
### Expected behavior
`ByteBuffer.clear`, aside from reseting the writer and the reader indexes, should also reset the `ByteBuffer._slice` to regain the whole `ByteBuffer._storage`.

### Actual behavior
`ByteBuffer.clear` doesn't reset the `ByteBuffer._slice`. Imagine having a byte buffer slice (`ByteBuffer.getSlice`). Calling `ByteBuffer.clear` on the slice will reset the reader and writer, but the `ByteBuffer.capacity` will return the old slice size, not the full storage capacity.

### Steps to reproduce

This can be easily reproduced with this unit test:
```
let alloc = ByteBufferAllocator()
var buf = alloc.buffer(capacity: 16)
buf.writeString("qwertyuiop")
XCTAssertEqual(buf.capacity, 16)

var slice = buf.getSlice(at: 3, length: 4)!
XCTAssertEqual(slice.capacity, 4)

slice.clear()
XCTAssertEqual(slice.capacity, 16) // XCTAssertEqual failed: ("4") is not equal to ("16")
```

**Comment by kam800** [comment]
I working on that with @Keno42.

**Comment by Lukasa** [comment]
This is a great catch, we should absolutely fix that up, thanks!
