### ISSUE TITLE
Add extra WebSocket decoder benchmarks

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio#1205]
With #1203 coming in, it’d be good to cover some more branches through the code.

1. A WebSocketFrame with a `maskingKey`.
2. A WebSocketFrame with a 16-bit length
3. A WebSocketFrame with a 64-bit length

This could even generalise further to have all of the above.

**Comment by ianpartridge** [comment]
And using `ByteToMessageDecoderVerifier`?

**Comment by emarashliev** [comment]
Addressed in #1219
