### ISSUE TITLE
Remove the binaries from the list of products.

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio#1217]
For some reason, in the past, when we started writing example binaries we added them all to the `.products` for our package. That isn’t really right: they aren’t a formal product of swift-nio. Having them there implies that they are versioned in some way. And it can lead to unnecessary noise in Xcode.

We should remove them from the `products`. This will have the effect of preventing them from being automatically built by `swift build`, but that’s ok: it’ll probably break one or two of our scripts, but it’s not the end of the world.

**Comment by shekhar-rajak** [comment]
Hi,

I am interested to contribute to the project and trying to understand the codebase. 
For this issue do we just have to remove the `Products`  folder from the root directory and check that all the test cases are passing?

**Comment by Lukasa** [comment]
Sorry @shekhar-rajak, I believe this was resolved by #1303.
