### ISSUE TITLE
XOR the pointer value in the promise creation store to hide it from Memory Graph Debugger

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1226]
Memory Graph Debugger and probably other memory debugging tools (like LSan/valgrind/...) will scan the heap for pointer values. Currently, the promise creation store contains `ObjectIdentifier(promise)` which means we will have the pointer value of `promise` in the heap without actually retaining that.
This leads to Mem Graph Debugger in debug mode showing reference cycles that aren't actually there.

The fix is easy: We should just make this an `UInt(bitPattern: ObjectIdentifier(promise))` and XOR that with a known value that fits into both 32 and 64 bit address spaces, for example `0xdeadbef`. That way, Mem Graph Debugger and friends won't see this as a reference and the tools will work better on NIO :).

**Comment by shekhar-rajak** [comment]
Hi,

I want to work on this. But I didn't understand this line:

> Currently, the promise creation store contains ObjectIdentifier(promise) which means we will have the pointer value of promise in the heap without actually retaining that.

Can you please explain a bit, in which file this happens?

**Comment by Lukasa** [comment]
Yup, it's a property of the [`SelectableEventLoop`](https://github.com/apple/swift-nio/blob/16ab4d657e1ad4e77bd5f8b94af8538561643053/Sources/NIO/SelectableEventLoop.swift#L89-L105).

**Comment by shekhar-rajak** [comment]
Thanks @Lukasa , I am able to find out the method [`promise creation store`](https://github.com/apple/swift-nio/blob/master/Sources/NIO/SelectableEventLoop.swift#L93).

Should we use 

```
private var _promiseCreationStore: [UInt: (file: StaticString, line: UInt)] = [:]
```

instead

```
private var _promiseCreationStore: [ObjectIdentifier: (file: StaticString, line: UInt)] = [:]
```
?

So code like ` self._promiseCreationStore[ObjectIdentifier(future)] = (file: file, line: line)` should be changed to ` self._promiseCreationStore[UInt(bitPattern: ObjectIdentifier(future))] = (file: file, line: line)`?

**Comment by weissi** [comment]
@shekhar-rajak sounds good!

**Comment by Lukasa** [comment]
I suspect that's what we'll have to do, yes.

**Comment by shekhar-rajak** [comment]
Thanks! I will work on this.
