### ISSUE TITLE
Dash docset is not working

### ISSUE THREAD

**Issue by liuxuan30** [apple/swift-nio#1254]
When trying to add Dash docset on https://apple.github.io/swift-nio/docs/2.10.1/docsets/NIO.xml

Dash 4.6.6 always says
![image](https://user-images.githubusercontent.com/4375169/69202340-5483de80-0b7c-11ea-8015-96b6e37672c5.png)

**Comment by Lukasa** [comment]
So the path to the docset is supposed to be https://apple.github.io/swift-nio/docs/2.10.1/NIO/docsets/NIO.xml. However, it seems that the docset URL is not quite right, because that docset won't work: it doesn't realise what its correct path is.

**Comment by Lukasa** [comment]
Specifically the contents of the xml file at that path are:

```
<entry><version>2.10.1</version><url>https://apple.github.io/swift-nio/docs/2.10.1/docsets/NIO.tgz</url></entry>
```

Note that the URL there is again going to 404 because it is missing the module name. So that suggests an issue in the generation process itself.

**Comment by Lukasa** [comment]
Thanks for the report, see #1256.

**Comment by liuxuan30** [comment]
NP, but I tried again on the website, clicking the dash button still gives old `https://apple.github.io/swift-nio/docs/2.10.1/docsets/NIO.xml`
If I manually copy `https://apple.github.io/swift-nio/docs/2.10.1/docsets/NIO.tgz`, it also errors as well.

With this PR merged, what's the next step to make Dash obtain this docset?

**Comment by Lukasa** [comment]
I believe we only regenerate the documentation after we issue a new tag. @tomerd is that correct?

**Comment by tomerd** [comment]
> I believe we only regenerate the documentation after we issue a new tag. @tomerd is that correct?

yes

**Comment by liuxuan30** [comment]
alright, can't wait for the next release :)

**Comment by klaas** [comment]
Hm... there is nothing at https://apple.github.io/swift-nio/docs/2.16.0/NIO/docsets/NIO.xml

The latest that I could find was https://apple.github.io/swift-nio/docs/2.13.0/NIO/docsets/NIO.xml

**Comment by tomerd** [comment]
we stoped publishing the docsets recently. how are you using these?

**Comment by klaas** [comment]
There's a "Install in Dash" button in the top right corner of https://apple.github.io/swift-nio/docs/current/NIO/index.html . That opens dash but then has an invalid "Docset feed URL".

Any other way to integrate them into Dash?

**Comment by weissi** [comment]
I'd also like to get the docsets back, @tomerd did they break or something?

**Comment by liuxuan30** [comment]
@tomerd why stopped? Dash is a great tool for API. would be very sorry to see NIO dropped it.

**Comment by glbrntt** [comment]
NIO switched to docc and no longer uses Jazzy to generate docs, unfortunately this means we no longer support docsets.
