### ISSUE TITLE
Fatal Error: NIOAny.swift, line 101

### ISSUE THREAD

**Issue by StrangeDays** [apple/swift-nio#1270]
### Expected behavior

- Work like developed and running on OSX 
- All requests work

### Actual behavior

- Fatal error: tried to decode as type Request but found Request with contents other(AsyncHTTPClient.HTTPClient.Request(method:

- Fatal error: tried to decode as type ByteBuffer but found IOData with contents other(IOData

### Steps to reproduce

Run your Server on Linux via Docker (swift:latest, ...)

- https://github.com/IBM-Swift/Kitura/issues/1465

### If possible, minimal yet complete reproducer code (or URL to code)

Pretty simple RestRequest (SwiftyRequest) with responseObject and responseData

### SwiftNIO version/commit hash

2.10.1

### Swift & OS version (output of `swift --version && uname -a`)

Swift version 5.1 (swift-5.1.2-RELEASE)
Target: x86_64-unknown-linux-gnu
Linux e965e14a2285 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by weissi** [comment]
that's a bug in async-http-client, I filed the issue over there as https://github.com/swift-server/async-http-client/issues/138
