### ISSUE TITLE
implement _UInt24 and _Uint56 == functions

### ISSUE THREAD

**Issue by glbrntt** [apple/swift-nio#1274]
[@weissi with George's account]

Unfortunately, because Swift likes ABI stability, the automatically derived equals functions aren't `@inlinable` and there's no syntactic place to put the `@inlinable` for us. That leads to `_UInt24` and `_UInt56`'s equals functions to be `call       $s3NIO7_UInt24V23__derived_struct_equalsySbAC_ACtFZ ; static NIO._UInt24.__derived_struct_equals(NIO._UInt24, NIO._UInt24) -> Swift.Boo` instead of just a few CMP/TEST instructions.

This can be fixed by manually implementing the `==` functions and marking them inlinable.

**Comment by Lukasa** [comment]
Resolved by #1285.
