### ISSUE TITLE
Issue with NIOHTTPClientUpgradeHandler when immediatly firing write after buffered read.

### ISSUE THREAD

**Issue by MrLotU** [apple/swift-nio#1279]
In [NIOHTTPClientUpgradeHandler.swift](https://github.com/apple/swift-nio/blob/master/Sources/NIOHTTP1/NIOHTTPClientUpgradeHandler.swift#L314) data is  buffered until the upgrade is complete, and is than fired once the upgrade is done.

If you fire a `channel.write` immediatly after receiving one of those buffered `channel.read`s, NIO will error with 
```
The operation couldn’t be completed. (NIOHTTP1.NIOHTTPClientUpgradeError error 1.)
writingToHandlerAfterUpgradeCompleted
```
This is because the `write` will arrive in the `NIOHTTPClientUpgradeHandler` before it removed itself from the pipeline. The error is fired from [this line](https://github.com/apple/swift-nio/blob/master/Sources/NIOHTTP1/NIOHTTPClientUpgradeHandler.swift#L150) due to the line linked above setting `upgradeState` to `.upgradeComplete`.

### Expected behavior
My `channel.write` works fine, since `NIOHTTPClientUpgradeHandler` should remove itself from the pipeline

### Actual behavior
`NIOHTTPClientUpgradeHandler` receives the `write` before it removed itself from the pipeline.

### Steps to reproduce

1. Have a WebSocket server that sends back it's first packet with the HTTP upgrade response (this is important, otherwise data does not end up in the buffer)
2. Connect to the WebSocket
3. Fire a `channel.write` immediately after receiving the first packet.
4. Observe

### If possible, minimal yet complete reproducer code (or URL to code)
https://github.com/MrLotU/bug-repros/tree/nio-1279
All code outside of `main.swift` is copied from [vapor/websocket-kit](https://github.com/vapor/websocket-kit)

### SwiftNIO version/commit hash
SwiftNIO 2.10.1

### Swift & OS version (output of `swift --version && uname -a`)
```
Apple Swift version 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9)
Target: x86_64-apple-darwin19.0.0
Darwin ip-192-168-178-248.eu-west-1.compute.internal 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64
```
Also reproducible on latest Swift master toolchain (`org.swift.50201911301a`)

**Comment by Lukasa** [comment]
This is a great catch. Yeah, I think we can transition to `upgradeComplete` _last_ in that callback block, instead of first. This is an exception from our normal rules about state changes, so we should add a comment there, but that's fine.

@MrLotU do you want to write a patch for this?
