### ISSUE TITLE
Unit test failed and crashed under Swift Package + iOS Simulator

### ISSUE THREAD

**Issue by liuxuan30** [apple/swift-nio#1281]
Hi there,

In my framework https://github.com/liuxuan30/TelloSwift, I created swift package file and tried to run UT on macOS and iOS Simulator.

the macOS passed, however every time I ran on iOS Sim, it always crashes inside nio. Running same tests in original xcode project on both iOS and macOS passed without problem, which makes me very confused

the crash:
![image](https://user-images.githubusercontent.com/4375169/70005929-3a97c200-15a6-11ea-9bd6-58759abd2373.png)

Can someone help, if this is a nio bug, or Xcode UT bug?

**Comment by weissi** [comment]
@liuxuan30 thanks for reporting. This sounds very much like https://bugs.swift.org/browse/SR-11564 . Can you confirm the following:

- you're on Xcode 11.2.x or 11.3 beta
- this only happens on device or in simulator, _not_ on macOS
- if you set `DEAD_CODE_STRIPPING=NO` in your Xcode project then this doesn't happen either

**Comment by liuxuan30** [comment]
Hi @weissi yes I'm on 11.2.1 from AppStore build;
This only happens on iOS simulator, **and under Swift Package xcode project**, not regular (the regular is perfectly running tests)

where to set DEAD_CODE_STRIPPING?
I set it in Swift package "Run scheme", still crashes
![image](https://user-images.githubusercontent.com/4375169/70047727-8dec2d80-1603-11ea-9bf3-edceaf4a7ad2.png)

**Comment by weissi** [comment]
@liuxuan30 you need to

1. Select your project on the left side in Xcode
2. Click on 'build settings'
3. Select the project up top
4. under "Linking", go to "Dead Code Stripping"
5. set it to "No"

**Comment by weissi** [comment]
<img width="493" alt="Screenshot 2019-12-03 at 11 36 34 am" src="https://user-images.githubusercontent.com/624238/70048001-2ad9a700-15c1-11ea-82cc-fbbfa41a7972.png">

like here, make sure that in both cases the project itself is selected

**Comment by liuxuan30** [comment]
@weissi 
Some context:
In my original Xcode project, they are YES, and the tests runs perfectly on iOS simulator;
I have set them all to NO, including the PROJECT and TARGETS, and then bring up the swift package Xcode project, it still crashes;

I think the problem is I cannot see build setting for a swift package project, there is no place to click like a regular xcodeproj:
![image](https://user-images.githubusercontent.com/4375169/70048434-46ff3780-1605-11ea-858a-e0aaf3895318.png)

**Comment by weissi** [comment]
@liuxuan30 oh yes, with a Swift package I don't know how to change that. You could temporarily use the old school `swift package generate-xcodeproj` and set it there

**Comment by weissi** [comment]
@liuxuan30 another thing that may help would be this: Once it has crashed, type in the `(lldb) ` console in the bottom right:

```
command script import lldb.macosx.crashlog
save_crashlog /tmp/crash.txt
```

and then attach `/tmp/crash.txt` here.

**Comment by liuxuan30** [comment]
[crash.txt](https://github.com/apple/swift-nio/files/3916446/crash.txt)
crash text here you go

**Comment by weissi** [comment]
@liuxuan30 thanks! this is 99.9% the bug I mentioned:

```
Thread 5:
0   TelloSwiftTests                  0x000000010f622032 method descriptor for TelloSwift.TelloCommandHandler.write(context: NIO.ChannelHandlerContext, data: NIO.NIOAny, promise: Swift.Optional<NIO.EventLoopPromise<()>>) -> ()
1   None                             0x000070000b7a4560 None
```

we're trying to _execute_ the method descriptor which is _data_. The same happened for example in

- https://github.com/apple/swift-nio/issues/1227
- https://github.com/grpc/grpc-swift/issues/623
- https://github.com/grpc/grpc-swift/issues/605

**Comment by liuxuan30** [comment]
sure, much appreciated your help. So we just sit tight and wait for https://bugs.swift.org/browse/SR-11564 to be fixed?

**Comment by liuxuan30** [comment]
but one weird thing is the normal Xcode tests passed all the time, even with Dead Code Stripping is YES

**Comment by weissi** [comment]
@liuxuan30 what do you mean with 'the normal Xcode tests'? I think the bug is a bit random, it doesn't always cause an issue and it doesn't always hit the same piece of code :(

**Comment by weissi** [comment]
@liuxuan30 could you try with Xcode 11.1?

**Comment by liuxuan30** [comment]
> @liuxuan30 what do you mean with 'the normal Xcode tests'? I think the bug is a bit random, it doesn't always cause an issue and it doesn't always hit the same piece of code :(

The normal tests means, running the exact same tests in original .xcodeproj, it passes all the time in my memory, as well as travis CI, you can check it in my project repo. But the swift package project will fail 100%

I'm not able to try 11.1 :( sorry

**Comment by weissi** [comment]
Sorry, I wasn't quite precise enough: I meant random as in it depends on the binary. With the same binary, the crash will always be the same.

Can you try this from the command line:

    cd TelloSwift # go to your checkout (where your Package.swift lives)
    xcodebuild -scheme swift-nio-Package test -destination "id=$(xcrun simctl list -j devices iPhone\ 11\ Pro\ Max available | grep udid | cut -d '"' -f4)" DEAD_CODE_STRIPPING=NO

what happens if you do that?

**Comment by liuxuan30** [comment]
Hi @weissi sorry for the late reply.
running
>xcodebuild -scheme TelloSwift test -destination "id=$(xcrun simctl list -j devices iPhone\ 11\ Pro\ Max available | grep udid | cut -d '"' -f4)" DEAD_CODE_STRIPPING=NO

seems passed without problem.

**Comment by weissi** [comment]
@liuxuan30 what happens if you re-run the above command but remove the `DEAD_CODE_STRIPPING=NO` argument?

**Comment by liuxuan30** [comment]
@weissi the tests passed as well without DEAD_CODE_STRIPPING=NO

**Comment by liuxuan30** [comment]
I'm seeing a new Xcode 13.3, when it's installed I will try again.

**Comment by weissi** [comment]
thank you!

**Comment by liuxuan30** [comment]
it seems Xcode 11.3 indeed fixed this issue :) good day
