### ISSUE TITLE
SIGABRT in ClientBootstrap with release configuration only

### ISSUE THREAD

**Issue by cilki** [apple/swift-nio#1294]
### Expected behavior
The following should not crash when built with the release configuration in Xcode:
```swift
let loopGroup = MultiThreadedEventLoopGroup(numberOfThreads: 1)
let bootstrap = ClientBootstrap(group: loopGroup)
    .channelOption(ChannelOptions.socket(SocketOptionLevel(SOL_SOCKET), SO_REUSEADDR), value: 1)

 bootstrap.connect(host: "example.com", port: 80).whenComplete { result in
    switch result {
    case .success(_):
         print("Success")
    case .failure(let error):
        print(error)
    }
}
```

### Actual behavior
The application crashes with a SIGABRT on `Bootstrap.swift:525` when built with the release configuration, but **not** with the debug configuration.

### Steps to reproduce
Here is an Xcode 11.2.1 project which is just the above section of code in `AppDelegate.swift`: [https://github.com/cilki/NIOCrashReproducer](https://github.com/cilki/NIOCrashReproducer). It doesn't seem to matter which simulator is used, but I've been using an `iPhone 11 Pro Max 13.2.2`.

1. Build with debug configuration -> app prints "success"
2. Build with release configuration -> app crashes

I've tried changing the compiler optimization levels in both configurations, but it always works in debug mode and always crashes in release mode.

### SwiftNIO version/commit hash
2.10.1

### Swift & OS version (output of `swift --version && uname -a`)
```
Apple Swift version 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9)
Target: x86_64-apply-darwin19.0.0
root:xnu-6153.41.3~23/RELEASE_X86_64 x86_64
```

**Comment by weissi** [comment]
@cilki Thanks so much for the reproducer, I could repro immediately. This is also https://bugs.swift.org/browse/SR-11564 I think, I had no idea how bad this is. The good news is that the workaround is very straightforward. Set `DEAD_CODE_STRIPPING = NO` and you should be good.

<img width="920" alt="Screenshot 2019-12-05 at 11 40 21 pm" src="https://user-images.githubusercontent.com/624238/70283328-9e91d480-17b8-11ea-8060-cfda376fac01.png">

**Comment by weissi** [comment]
I think this is also the same underlying issue as https://github.com/apple/swift-nio/issues/1281

**Comment by weissi** [comment]
@cilki can you confirm that disabling dead code stripping fixes the issue in your real application too?

**Comment by cilki** [comment]
@weissi That was it. Thank you so much! :+1:
