### ISSUE TITLE
DELETE requests should allow bodies

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1313]
See https://github.com/swift-server/async-http-client/issues/146 . Currently we seem to drop request bodies on DELETE. Whilst that’s spec compliant it’s unhelpful and also unexpected.

Let’s fix that.

**Comment by weissi** [comment]
Additionally we should check the server part too as well as other verbs where we think a body is “unlikely”

**Comment by Lukasa** [comment]
The server part is fine, it's just `DELETE` and `HEAD` in the wrong place I'm pretty sure.
