### ISSUE TITLE
ByteBuffer should be hashable

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1320]
ByteBuffers should conform to `Hashable` which should be pretty straightforward as we can just call `withUnsafeReadableBytes` and hand those bytes to the `Hasher`.

**Comment by fabianfett** [comment]
Hi @weissi, 

I just looked at this. I came up with your proposed really simple solution:

```swift
extension ByteBuffer: Hashable {
    /// The hash value for the readable bytes.
    public func hash(into hasher: inout Hasher) {
        withUnsafeReadableBytes { ptr in
            hasher.combine(bytes: ptr)
        }
    }
}
```

But adding a test that ensures that different buffers with the same content but different reserved capacities are hash equal showed me that this maybe is not as simple as thought.

```swift
    func testHasherUsesReadBuffersOnly() {
        // Only cares about the read buffer
        self.buf.writeInteger(Int8.max)
        self.buf.writeString("oh hi")

        var hasher = Hasher()
        hasher.combine(self.buf)
        let hash = hasher.finalize()
        
        var otherBuffer = allocator.buffer(capacity: 32)
        otherBuffer.writeString("oh hi")

        var otherHasher = Hasher()
        otherHasher.combine(otherBuffer)
        let otherHash = otherHasher.finalize()
        
        XCTAssertEqual(hash, otherHash)
    }
```

Do you maybe have a hint on how to proceed from here?

**Comment by Lukasa** [comment]
Have you cleared `self.buf`? That is, are you confident there are no readable bytes in there from the previous test?

**Comment by fabianfett** [comment]
@Lukasa I made it explicit and it still fails. If you want me to I can upload my code and create a PR so that you can have a look maybe?

My first guess with the reserved capacities is obviously not the case. Sorry dumb me. 

If I set a breakpoint for the line:
```
hasher.combine(bytes: ptr)
```

And I `po` the pointer for each run, I get the following output:
```
(lldb) po ptr
▿ UnsafeRawBufferPointer(start: 0x0000000105004000, count: 5)
  ▿ _position : Optional<UnsafeRawPointer>
    ▿ some : 0x0000000105004000
      - pointerValue : 4378869760
  ▿ _end : Optional<UnsafeRawPointer>
    ▿ some : 0x0000000105004005
      - pointerValue : 4378869765

(lldb) po ptr
▿ UnsafeRawBufferPointer(start: 0x0000000100f00f80, count: 5)
  ▿ _position : Optional<UnsafeRawPointer>
    ▿ some : 0x0000000100f00f80
      - pointerValue : 4310699904
  ▿ _end : Optional<UnsafeRawPointer>
    ▿ some : 0x0000000100f00f85
      - pointerValue : 4310699909
```

Very strange.

**Comment by Lukasa** [comment]
If I had to guess, I’d say the mistake here is that we are hashing the _buffer pointer_, not the bytes _within_ that buffer pointer. I think you’ll need to loop over the bytes.

**Comment by weissi** [comment]
`combine(ptr:)` definitely combines the bytes the pointer is pointing to: https://developer.apple.com/documentation/swift/hasher/2995579-combine

**Comment by Lukasa** [comment]
In that case we’ll need to see the code itself.

**Comment by weissi** [comment]
this works just fine:

```
$ cat test.swift && echo ====== && swift test.swift
var one = Array("hello world".utf8)
var two = Array("hello world".utf8)

var h1 = Hasher()
one.withUnsafeBytes {
    h1.combine(bytes: $0)
}
print(h1.finalize())

var h2 = Hasher()
two.withUnsafeBytes {
    h2.combine(bytes: $0)
}
print(h2.finalize())
======
6295175629148869854
6295175629148869854
```
