### ISSUE TITLE
create NIOAtomic{Bool,Int,...} types

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1321]
we should create a bunch of _struct_s called

- `NIOAtomicBool`
- `NIOAtomicInt`
- `NIOAtomicInt64`
- `NIOAtomicUInt`
- ...

which clearly document that they have _reference semantics_. To start with, they should be implemented with `NIOAtomic<...>` and once Swift supports them, we should implement them with the upcoming stdlib atomics.

**Comment by Lukasa** [comment]
Closing in favour of stdlib atomics instead, which should better address this wide range of use-cases.
