### ISSUE TITLE
NIOWebsocket Base64 encoding - unexpected memory overhead.

### ISSUE THREAD

**Issue by fabianfett** [apple/swift-nio#1322]
### Actual behavior

After the issue https://github.com/apple/swift-nio/issues/1265, I started to dig into the implementation of base64. The results of that work can be found at [fabianfett/swift-base64](https://github.com/fabianfett/swift-base64). While implementing decoding, I tested the performance of my implementation against Foundation. Since I wanted to base my work on the Base64 encoding provided by `NIOWebsocket` I also tested its performance. Surprisingly it's rather slow.

Encoding 100k times the bytes from 0 to 255 produced these results:

**On my MacBook Pro 2016 (2,7 GHz Intel Core i7)** 
```
Number of invocations: 100000
------------------------------------------
Encoding
Foundation   | took: 0.24192798137664795s
NIOWebsocket | took: 8.385756015777588s
------------------------------------------
```

**On Linux Foundation's performance isn't great either.** Therefore the performance hit compared to Foundation is not as bad.
```
------------------------------------------
Encoding
Foundation   | took: 3.710782051086426s
NIOWebsocket | took: 5.109261989593506s
Base64       | took: 0.10653805732727051s
------------------------------------------
```

### If possible, minimal yet complete reproducer code (or URL to code)

The code to reproduce can be found the branch `compare-with-niowebsocket-base64` at [fabianfett/swift-base64](https://github.com/fabianfett/swift-base64)
https://github.com/fabianfett/swift-base64/tree/compare-with-niowebsocket-base64

Performance results on GitHub actions can be seen in the `Performance Tests` (Not great for detailed measuring, but we are of the target by quite a margin in this case):
https://github.com/fabianfett/swift-base64/pull/2/checks

Looking into the issue with Instruments, I'm quite sure the performance hit is based on the use of the `Unicode.Scalar` that seem to come with "some" memory overhead.

<img width="930" alt="Screen Shot 2019-12-20 at 18 52 51" src="https://user-images.githubusercontent.com/6780861/71279796-f2c0bb00-2359-11ea-900d-c8b863220fa8.png">

### SwiftNIO version/commit hash

commit hash: `0ac7e2266bccd08ab174f6e2ef55522797b68343` code unchanged since Feb 14 2019.

### Swift & OS version (output of `swift --version && uname -a`)

```
Target: x86_64-apple-darwin18.7.0
Darwin xxx 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
```

**Comment by weissi** [comment]
thanks very much @fabianfett for the report! Yes, our base64 algorithm is _very_ naive at the moment. We don't expose it as API and we only ever use it to to WebSocket which needs it to encode exactly one, short string (I think it's less than 64 characters) per connection. So any performance optimisation would very likely be invisible in actual uses.

Nevertheless, we could make it more optimised which would actually not be hard.

Maybe you'd like to take a stab at optimising our implementation?

A couple of thoughts:
- We should probably accumulate the bytes into an `Array<UInt8>` instead of a `String`
- We shouldn't use a lookup table but a `switch` instead

Just these two things together will probably already make it pretty fast.

**Comment by weissi** [comment]
@fabianfett oh, I just see that you already implemented faster base64. Would you like to contribute it to SwiftNIO too? I'm pretty sure that if you removed the lookup table from your code and replaced it by a `switch`, it'd be even faster.

Other thoughts: it's no faster to write `32` than it is to write `UIn8(ascii: " ")` which is much more readable

**Comment by fabianfett** [comment]
> Would you like to contribute it to SwiftNIO too?

There has been discussion about this in https://github.com/apple/swift-nio/issues/1265

@Lukasa proposed another way though:

> I think in general I don't want swift-nio to vend small utilities like this. I agree that having a general base-64 encode and decode function is useful, but swift-nio is not a very good place to put such a function. Given that swift-nio is permissively licensed, I would recommend taking the following steps:
>
> 1. Creating a new swift package containing the contents of that file, making the initializer public, and announcing the package on the Swift forums.
> 2. Proposing the code for inclusion in the standard library preview package, possibly by making it more generic (i.e. by using Collection instead of Array).
> 3. Eventually aim to get the code in the standard library.
>
> How does that sound?

Would be very open to contribute it to SwiftNIO anyways.

**Comment by Lukasa** [comment]
To be clear, I don’t think NIO should _vend_ it. I’m more than happy for NIO to contain a vendored copy, I just don’t want to expose it as public API on NIO.

**Comment by fabianfett** [comment]
@weissi could you point me to some documentation where I could learn about how a switch would be faster than the lookup table?

**Comment by fabianfett** [comment]
@weissi I just tested replacing the lookup table with a switch to get a sense of what performance improvements should be possible with a switch.

https://github.com/fabianfett/swift-base64/pull/3/files

In my local tests as well as on the GitHub actions (ci) the switch performs two times slower than the lookup table. https://github.com/fabianfett/swift-base64/pull/3/checks

Am I doing something completely false?

**Comment by weissi** [comment]
> @weissi I just tested replacing the lookup table with a switch to get a sense of what performance improvements should be possible with a switch.
> 
> https://github.com/fabianfett/swift-base64/pull/3/files
> 
> In my local tests as well as on the GitHub actions (ci) the switch performs two times slower than the lookup table. https://github.com/fabianfett/swift-base64/pull/3/checks
> 
> Am I doing something completely false?

I commented in the code, I’d assume something like

```
switch byte {
    case 0...51: return byte &+ 48
    case foo...bar: return byte &- buz
     ...
}
```
Should be faster

**Comment by weissi** [comment]
> To be clear, I don’t think NIO should _vend_ it. I’m more than happy for NIO to contain a vendored copy, I just don’t want to expose it as public API on NIO.

👍 +1, obviously we do like fast code but we don’t want to make base 64 encoding our API.

**Comment by fabianfett** [comment]
Great! I'd gladly provide a vended version of my code to Swift-NIO as soon as we can agree on the fastest easy solution. ;)

> This function performs the world's most naive Base64 encoding: no attempts to use a larger lookup table or anything intelligent like that, just shifts and masks. This works fine, for now: the purpose of this encoding is to avoid round-tripping through Data, and the perf gain from avoiding that is more than enough to outweigh the silliness of this code.

Would really like to help ensure this code comment is true. 😜

**Comment by weissi** [comment]
> Great! I'd gladly provide a vended version of my code to Swift-NIO as soon as we can agree on the fastest easy solution. ;)
> 
> > This function performs the world's most naive Base64 encoding: no attempts to use a larger lookup table or anything intelligent like that, just shifts and masks. This works fine, for now: the purpose of this encoding is to avoid round-tripping through Data, and the perf gain from avoiding that is more than enough to outweigh the silliness of this code.
> 
> Would really like to help ensure this code comment is true. 😜

For our use-case (always 64 bytes), it _is_ probably true today :).

**Comment by fabianfett** [comment]
> For our use-case (always 64 bytes), it is probably true today :).

I'm so sorry: https://github.com/fabianfett/swift-base64/pull/2/checks?check_run_id=359283613

**Comment by weissi** [comment]
@fabianfett you'd need to add two conversions from `ByteBuffer` to `Data` and back into your benchmark to approximate the one use-case we have. And you'd need to consider allocator pressure (for allocating an extra `Data`) in a heavily loaded real-world system. But again, if you're interested in making the NIO's base64 encoder faster, we are more than happy to take it :).
