### ISSUE TITLE
swift 5.2 CI

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1327]
Once the 5.2 snapshots are available on swift.org/download, we should CI with them. They're not available right now yet but the `swift-5.2-branch` is cut.

CC @Lukasa / @tomerd / @shahmishal

**Comment by weissi** [comment]
@tomerd should we do this like we did 5.1 snapshots in the past with the custom docker image?

**Comment by weissi** [comment]
We now have official nightlies for docker 🎉🎉🎉: https://forums.swift.org/t/nightly-swift-docker-images/33029

**Comment by Davidde94** [comment]
Closing this - we added official 5.2 CI (with the release images) in the linked PR
