### ISSUE TITLE
scheduleRepeatedAsyncTask: returning future from different EL hits precondition

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1334]
If the user returns a future from a different event loop from `EventLoop.scheduleRepeatedAsyncTask` will cause a precondition in NIO. That's a bug.

test case that shows the issue

```swift
    func testRepeatedTaskOffFuture() {
        let elg1: EventLoopGroup = MultiThreadedEventLoopGroup(numberOfThreads: 1)
        defer {
            XCTAssertNoThrow(try elg1.syncShutdownGracefully())
        }

        let elg2: EventLoopGroup = MultiThreadedEventLoopGroup(numberOfThreads: 1)
        defer {
            XCTAssertNoThrow(try elg2.syncShutdownGracefully())
        }

        let g = DispatchGroup()
        var callNumber = 0
        g.enter()
        let task = elg1.next().scheduleRepeatedAsyncTask(initialDelay: .nanoseconds(0), delay: .nanoseconds(0)) { task in
            struct Dummy: Error {}

            callNumber += 1
            switch callNumber {
            case 1:
                return elg2.next().makeSucceededFuture(())
            case 2:
                g.leave()
                return elg2.next().makeFailedFuture(Dummy())
            default:
                XCTFail("shouldn't be called \(callNumber)")
                return elg2.next().makeFailedFuture(Dummy())
            }
        }
        task.begin(in: .nanoseconds(0))
        g.wait()
    }
```

**Comment by weissi** [comment]
@Lukasa starter bug? Or is that a little too complicated?

**Comment by Lukasa** [comment]
I think this could be a starter bug with some guidance from the NIO team.

**Comment by Andrewangeta** [comment]
@weissi @Lukasa please tell me this doesn’t require a breaking change 😭

**Comment by Lukasa** [comment]
Nope, it shouldn't.

**Comment by Andrewangeta** [comment]
I think I wanna take this bug on. It’ll be a fun dive into some NIO innards.

**Comment by weissi** [comment]
@Andrewangeta awesome! Please reach out for help/pointers anytime!

**Comment by weissi** [comment]
@Andrewangeta are you still interested in fixing this?

**Comment by Andrewangeta** [comment]
Yes but unfortunately I can’t find the time to dig into it :( it might be best if someone else had a look into it. I’ll just learn from the eventual PR that fixes it. @weissi

**Comment by weissi** [comment]
No worries at all!

**Comment by joshuawright11** [comment]
@weissi I took a stab @ fixing the assertion here https://github.com/joshuawright11/swift-nio/commit/67941712c25aee1a223ffb53601d21d912afd4af but the `default` switch case still gets called 2-4 more times; slightly confused on the mechanics of the test... does the `syncShutdownGracefully()` stop any repeated tasks currently on that `EventLoop`?

**Comment by weissi** [comment]
@joshuawright11 hmm, that’s odd. Maybe there’s a bug in the scheduling code for repeated tasks. After returning a failed future, we shouldn’t run the task again. I’m happy for you however to not fail the test in `default` if you file an issue about that bug. You can just leave a TODO and return a failed future. We can fix the scheduling in a different PR

**Comment by gmilos** [comment]
Looks like the core of the bug is rescheduling on the `Future`'s `EventLoop`, not on the `RepeatedTask`'s `EventLoop`: https://github.com/apple/swift-nio/blob/7100980bf7d8bc1cf862c5558ad2e12cd8991661/Sources/NIO/EventLoop.swift#L148. Same issue with the cancellation few lines below: https://github.com/apple/swift-nio/blob/7100980bf7d8bc1cf862c5558ad2e12cd8991661/Sources/NIO/EventLoop.swift#L153.

The fix is to wrap in the usual dispatch test, like the below:
https://github.com/apple/swift-nio/blob/7100980bf7d8bc1cf862c5558ad2e12cd8991661/Sources/NIO/EventLoop.swift#L73-L79

Any suggestions from the committers re further improvements?

**Comment by weissi** [comment]
@gmilos you can do that test OR you can use `futureFromRandomEventLoop.hop(to: myPreferredEventLoop)`
