### ISSUE TITLE
we should assert/precondition that read doesn't return EINVAL

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1339]
`read` returning `EINVAL` is a bug in NIO and we should assert/precondition that it doesn't happen similar to what we do for `EBADF`/`EFAULT` on all syscalls. See #1337 for an example where that happens.

**Comment by Bouke** [comment]
In another project, I'm wrapping all posix calls like this: https://github.com/Bouke/HAP/blob/a494b40ab0c84b729e4a618a132879dcc68265f9/Sources/COperatingSystem/libc.swift#L7-L11. Do you have something similar in mind?

**Comment by Lukasa** [comment]
We do. We have a wrapper like that as well, but it turns some errors into crashes, on the grounds that they should never happen. Johannes is proposing adding EINVAL to that list of errors.

**Comment by weissi** [comment]
@Bouke just a drive-by comment: errno numbers differ across operating systems, your snippet looks like they’re hardcoded. If you have taken care of this in a different way please ignore

**Comment by Bouke** [comment]
@weissi I didn’t know that, thanks! In my code I’m mostly interested in success or failure anyway. Do you know of a cross os way to create strict posix error (enum)?

**Comment by weissi** [comment]
@Bouke hmm, what are you using the enum for? I’d just work with raw values (check NIO’s `IOError` type for example). The number of errno codes between platforms will also vary.

And regarding success or failure: in posix, there are some error codes that you definitely need to handle specially, for example `EINTR`.

Also be very very careful using `errno` in Swift, there is no guaranteed correct way to use errno in Swift because of ARC. Bugs.swift.org is down so I can’t find the bug number right now. But the back story is that ARC can run code at any point in time and the code run by ARC might change the `errno` value. Therefore you must somehow make sure that between the syscall and the place where you read `errno` there’s definitely no `deinit`s run by ARC. Using carefully placed inline(never) and inline(__always), NIO does the best we can do today in our `enum Posix`
