### ISSUE TITLE
Should use Posix.read instead of Glibc.read for timerfd

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1341]
https://github.com/apple/swift-nio/blob/976e65aba7102662533cf8c3d4969decbe52b904/Sources/NIO/Selector.swift#L552

To read the bytes from timerfd, we use Glibc.read directly but we should use `try! Posix.read` instead which would’ve made debugging #1337 incredibly straightforward. We should probably also go through the codebase and find other uses of Darwin/Glib.$syscall rather than Posix.$syscall (outside of System.swift)

**Comment by shekhar-rajak** [comment]
Hi @weissi ,

Can we use `try? Posix.read`  (not `try! Posix.read`), because we are not caring about the result?

**Comment by weissi** [comment]
@shekhar-rajak please use `try!` we don’t care about the result IF if was successful. If this operation fails, there’s a severe bug in NIO and we must crash. Because we didn’t do this so far bug #1337 stayed in NIO for over a year without us noticing, had we crashed, it would’ve been obvious straight away.

**Comment by shekhar-rajak** [comment]
Thanks for letting me know. I will work on this.
