### ISSUE TITLE
IOError is 26 bytes long, should be 3 words (24) or less

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1355]
### Expected behavior

All `Error` types should be 3 words or less. On 64 bit platforms that's 24 bytes. This is important because Errors get boxed in Error existentials which have 3 words of builtin storage. If that's not enough, it'll heap allocate. So we'd expect

```swift
  3> MemoryLayout<IOError>.size
$R1: Int = 24 or less
```

### Actual behavior

```swift
  3> MemoryLayout<IOError>.size
$R1: Int = 26
```

### Steps to reproduce

1. `swift run --repl`
2. `import NIO`
3. `MemoryLayout<IOError>.size`

### SwiftNIO version/commit hash

master on 24th Jan 2020

### Suggested fix

The very likely culprit is `StaticString` which is just a bad type. It's 2 words + 1 byte wide. Given that we also store an `errno` value, it's obvious how we blow through the 24 bytes. The fix should be really straightforward: Now that `String` is good, we should just always store a `String` instead of either a `String` or a `StaticString`.

**Comment by realdoug** [comment]
this seems like an easy first one.  I'm going to take a pass at it over the weekend.

**Comment by weissi** [comment]
@realdoug thanks so much, that'd be fantastic!
