### ISSUE TITLE
Cocoapods Support

### ISSUE THREAD

**Issue by Jake-Prickett** [apple/swift-nio#1390]
### Expected behavior
Cocoapods is currently on `2.11.0` 

[CocoaPods.org](https://cocoapods.org/pods/SwiftNIO)
[Podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/e/8/6/SwiftNIO/2.11.0/SwiftNIO.podspec.json)

### Actual behavior
Cocoapods version would be in sync with the current release.

-----------------------------------------------------------

Are Cocoapods going supported going forward? I'm working on a project that is looking to leverage `SwiftNIO` but currently uses Pods. I see an issue from some time ago with a similar thought. 

https://github.com/apple/swift-nio/issues/1017

**Comment by weissi** [comment]
Sorry @Jake-Prickett , I'll update it to 2.13.1 tonight

**Comment by Jake-Prickett** [comment]
Nice! Thank you so much for your quick response. Is the plan to continue to support Cocoapods for SwiftNIO?

**Comment by weissi** [comment]
@Jake-Prickett Sure, happy to continue pushing the updates. I'll try to be better pushing them once released rather than on bug report ;)

**Comment by weissi** [comment]
@Jake-Prickett okay, this should be done. Random other thought, given that you're using the NIO pods, would you at all be interested in becoming NIO's CocoaPods maintainer? I'd need to discuss this with the others but I think this is best done by someone who actually uses the pods :).

The actual update is pretty straightforward (`scripts/build_podspecs.sh -u  2.13.1`), for boring technical reasons however I have to always do this on my home computer which means I often forget 😬

**Comment by jpricke1-ford** [comment]
@weissi I would absolutely be interested. Once you discuss with the others, please let me know how I can help!

**Comment by weissi** [comment]
@jpricke1-ford Thank you! I talked to the relevant folks and if you're still interested, we'd very much like for you to be NIO's Cocoapods maintainer :). To sort out the details, would you mind sending me an email to johannesweiss@apple.com ? We can then sort out the boring stuff like actually giving you access and so on :)
