### ISSUE TITLE
ServerBootstrap: should we add the AcceptHandler before or after running the serverChannelInitializer

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1392]
question: ServerBootstrap: should we add the AcceptHandler before or after running the serverChannelInitializer

CC @normanmaurer 

Historically, in NIO we added the `AcceptHandler` _after_ the `serverChannelInitializer`. In #1372 I accidentally flipped it around which made a test in `swift-nio-extras` fail. I'm now changing that back to retain the old behaviour. Nevertheless, we should decide what's right.

**Comment by normanmaurer** [comment]
@weissi in netty we add it after we run the initialiser. This worked great for us and also ensure the user does not mess up the pipeline in a way that would break the accept logic.

**Comment by weissi** [comment]
thanks @normanmaurer , let's match Netty here then and leave it the way it is now on `master` (and also in all versions ever released).
