### ISSUE TITLE
undo @convention(c) hacks in System.swift

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1397]
in #206 we introduced workarounds for https://bugs.swift.org/browse/SR-7242 which appears fixed so we can probably undo :)

**Comment by weissi** [comment]
removed "good first issue" for now because we actually need to validate that Swift 5.1 at least is fine.

**Comment by weissi** [comment]
"good first issue" back because I just verified and even with Swift 5.1 it's fine :)

**Comment by shekhar-rajak** [comment]
Hi,

Do we just have to remove [`@convention annotation from all these variables`](https://github.com/apple/swift-nio/blob/master/Sources/NIO/System.swift#L48) ?

**Comment by weissi** [comment]
@shekhar-rajak yeah, I think we can just make them

```
let sysWrite = write
```

instead of the whole

```
let sysWrite: @convention(c) (CInt, UnsafeMutableRawPointer, size_t) -> ssize_t = ...
```

mess :)

**Comment by shekhar-rajak** [comment]
Thanks @weissi !  I will work on this.
