### ISSUE TITLE
Support for Websocket compression

### ISSUE THREAD

**Issue by bridger** [apple/swift-nio#1406]
I'm curious if compression support has been considered for Websockets in NIO. I'd be interested in using it in my server-side app.

Kitura developed [this package for websocket compression](https://github.com/IBM-Swift/Kitura-WebSocket-Compression) built on NIO's websockets. [I asked about it being supported in Vapor](https://github.com/vapor/websocket-kit/issues/55) and @tanner0101 suggested it would be very convenient to have it live directly in NIO.

How do you decide which parts of the Websocket spec are included in NIO and which are up to clients? I know Compression is an extension to Websockets, but it is pretty standard in most packages.

**Comment by Lukasa** [comment]
NIO is very reluctant to take on a dependency on zlib: in fact, we removed a previous HTTP compression library to `swift-nio-extras` for this very reason. I think we'd be happy to accept a patch in `swift-nio-extras` that implements this extension, though.
