### ISSUE TITLE
Stop copying Strings into Arrays for SHA1

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio#1409]
This code is a very Swift 4.2 block:

https://github.com/apple/swift-nio/blob/2c555d144a3699b0f267d71092c01e60491b9615/Sources/NIOWebSocket/SHA1.swift#L48-L53

We can use `String.utf8.withContiguousStorageIfAvailable` as a fast-path here, and only fall back to the Array case if that fails. In most cases this will save us an allocation for each hash function update.

**Comment by trungducc** [comment]
It seems like an easy one to start contributing. Could I create a PR to fix this issue?

**Comment by Lukasa** [comment]
Please do.
