### ISSUE TITLE
How to get an auth code using ASWebAuthenticationSession?

### ISSUE THREAD

**Issue by uch1** [apple/swift-nio#1415]
I'm trying to obtain an auth code from Stripe's OAuth endpoint using ASWebAuthenticationSession - this event happens after the my Stripe redirect url gets called.

Unfortunately, the authSession's completion handler doesn't call back with a callbackURL. And I need this callbackURL to query the auth code. I've read different articles on this topic but I can't figure out why my implementation doesn't work they way I expect it to.

[link to my question on StackOverflow](https://stackoverflow.com/questions/60398648/how-to-get-an-auth-code-using-aswebauthenticationsession) 

**Here's my code:**

``` swift 

class CreateStripeConnectAccountController: UIViewController {

  var authSession: ASWebAuthenticationSession!

  override func viewDidLoad() {
      super.viewDidLoad()
      configureAuthSession()
  }

  private func configureAuthSession() {

    let urlString = Constants.URLs.stripeConnectOAuth // Sample URL

    guard let url = URL(string: urlString) else { return }

    authSession = ASWebAuthenticationSession(url: url, callbackURLScheme: nil, completionHandler: { (callbackURL, error) in
       guard error == nil, let successURL = callbackURL else {
          print("Nothing")
          return
       }

       let oauthToken = NSURLComponents(string: (successURL.absoluteString))?.queryItems?.filter({$0.name == "code"}).first

       print(successURL.absoluteString)
    })

    authSession.presentationContextProvider = self
    authSession.start()
  }
}

extension CreateStripeConnectAccountController: ASWebAuthenticationPresentationContextProviding {
    func presentationAnchor(for session: ASWebAuthenticationSession) -> ASPresentationAnchor {
        self.view.window ?? ASPresentationAnchor()
    }
}

```

**Comment by Lukasa** [comment]
For questions about Apple platform APIs, please use [the developer forums](https://forums.developer.apple.com/welcome).
