### ISSUE TITLE
ByteToMessageDecoder: Default implementation for decodeLast should be provided

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1416]
For all but EOF framed protocols, the right implementation for `decodeLast` is

            public func decodeLast(context: ChannelHandlerContext,
                            buffer: inout ByteBuffer,
                            seenEOF: Bool) throws -> DecodingState {
                while try self.decode(context: context, buffer: &buffer) == .continue {}
                return .needMoreData
            }

And yet, we require users to always provide a `decodeLast` implementation. Instead, we should just provide the one above.

**Comment by shekhar-rajak** [comment]
So we have to change the current `decodeLast` method in  `NIOChatServer/main.swift:`, `NIOHTTP1/HTTPDecoder.swift`,  `NIOTLS/SNIHandler.swift`, `NIOWebSocket/WebSocketFrameDecoder.swift` ?

**Comment by weissi** [comment]
@shekhar-rajak Thanks, great questions:

-  `HTTPDecoder` definitely needs its own implementation that's different to the one suggested above because HTTP/1 can be EOF framed sadly.
- `SNIHandler` is also special because (see comment on `decode`), its decode never returns `.continue`
- `NIOChatServer/main.swift`'s decodeLast should be removed indeed
- `NIOWebSocket`'s `decodeLast` should also be removed and replaced with the above, @Lukasa to confirm this.

**Comment by Lukasa** [comment]
Confirm for `WebSocketFrameDecoder`.
