### ISSUE TITLE
HTTPObjectAggregator implementation

### ISSUE THREAD

**Issue by m0wfo** [apple/swift-nio#1436]
### Expected behavior
Netty's [HttpObjectAggregator](https://netty.io/4.1/api/io/netty/handler/codec/http/HttpObjectAggregator.html) significantly simplifies implementation of HTTP APIs where raw throughput is not a concern. Happy to port this if needed, just checking here that I'm not duplicating any work.

Downstream handlers would optionally be able to deal with subtypes of `FullHttpRequest` and `FullHttpResponse` rather than individual parts.

### Actual behavior

HTTP channel handlers must track state of individual parts of an HTTP message they have sent/received.

### Steps to reproduce

Write a SwiftNIO handler which deals with HTTP :)

### If possible, minimal yet complete reproducer code (or URL to code)

_[anything to help us reproducing the issue]_

### SwiftNIO version/commit hash

HEAD, AFAIK

### Swift & OS version (output of `swift --version && uname -a`)

latest, pick any OS

**Comment by Lukasa** [comment]
I think this would be a good addition to the project!
