### ISSUE TITLE
HTTPHeaders[canonicalForm:] quoted strings

### ISSUE THREAD

**Issue by tanner0101** [apple/swift-nio#1441]
HTTPHeader's canonical form subscript does not currently respected quoted strings. For example:

```http
foo: "bar, baz"
```

I'm not sure whether or not this is actually _required_ for what this subscript is used for, but it's worth considering. 

I've copied down an expanded HTTP header BNF collected from [RFC 2616](https://tools.ietf.org/html/rfc2616) and [RFC 822](https://tools.ietf.org/html/rfc822) here. 

```
message-header = field-name ":" [ field-value ]
field-name     = token
field-value    = *( field-content | LWS )
field-content  = <the OCTETs making up the field-value
                 and consisting of either *TEXT or combinations
                 of token, separators, and quoted-string>
quoted-string  = <"> *(qtext/quoted-pair) <">; Regular qtext or
                                             ;   quoted chars.
quoted-pair =  "\" CHAR                      ; may quote any char
qtext          =  <any CHAR excepting <">,   ; => may be folded
                   "\" & CR, and including
                   linear-white-space>
OCTET          = <any 8-bit sequence of data>
CHAR           = <any US-ASCII character (octets 0 - 127)>
CTL            = <any US-ASCII control character
                        (octets 0 - 31) and DEL (127)>
TEXT           = <any OCTET except CTLs,
                        but including LWS>
LWS            = [CRLF] 1*( SP | HT )
token          = 1*<any CHAR except CTLs or separators>
separators     = "(" | ")" | "<" | ">" | "@"
               | "," | ";" | ":" | "\" | <">
               | "/" | "[" | "]" | "?" | "="
               | "{" | "}" | SP | HT
```

**Comment by Lukasa** [comment]
RFC 2616 is dead, let's not quote it.

Strictly speaking `canonicalForm` is only best-effort: the correct implementation involves having specific parsers for specific header fields. We aren't doing that in NIO because it's more work than we can justifiably do and we'll inevitably miss a bunch of parsers. However, we should probably be ignoring commas within quoted strings.

**Comment by Lukasa** [comment]
Closing in favour of #1453.
