### ISSUE TITLE
Add convenient Type(from buffer: ByteBuffer) initialisers

### ISSUE THREAD

**Issue by Davidde94** [apple/swift-nio#1456]
Currently it's a little too verbose to load a full `ByteBuffer` into, for example, a `String`. 

```
var buffer = ...
let string = buffer.readString(length: buffer.readableBytes)!
```

We can make the process simpler by providing a `String(from buffer: ByteBuffer)` initialiser.

```
var buffer = ...
let string = String(from buffer: buffer)!
```

Types to add:
- [x] String
- [x] Data (must go in `NIOFoundationCompat`)
- [x] Array<UInt8>
- [x] DispatchData

**Comment by weissi** [comment]
- [ ] `DispatchData`
