### ISSUE TITLE
configureHTTP2SecureUpgrade Deprecated But Replacement Isn't Public

### ISSUE THREAD

**Issue by jshier** [apple/swift-nio#1458]
### Issue
`ChannelPipeline.configureHTTP2SecureUpgrade(h2ChannelConfigurator:http1ChannelConfigurator:)` is marked as deprecated and points to `Channel.configureHTTP2SecureUpgrade(h2ChannelConfigurator:http1ChannelConfigurator:)` as a replacement. However, `Channel.configureHTTP2SecureUpgrade(h2ChannelConfigurator:http1ChannelConfigurator:)` is still an `internal` method due to the extension that contains it not being public.

I'm happy to fix the issue, but as a matter of style does NIO prefer a global ACL for extensions, or per method ACLs? I can update the file to follow a consistent pattern while I'm there.

**Comment by Lukasa** [comment]
Thanks for the find @jshier! Per-method ACLs are preferred, thanks. And thanks for providing a patch!
