### ISSUE TITLE
Support propagating ECN information on `AddressedEnvelope`s

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio#1472]
It is possible that users of datagram channels may be interested in ECN information associated with the IP packets that carry the datagrams. It's possible to obtain this information from the OS and for us to propagate it through the channel, but today we do not.

The proposal for how to do so comes in multiple parts, each of which is probably a separate chunk of work:

- [ ] Add support for `AddressedEnvelope` to carry arbitrary metadata in a performant way

    This probably involves adding a metadata field to `AddressedEnvelope` that is usually empty, and only ever filled when necessary. This metadata will need to be keyed and typed. This is a straightforward Swift-level data structure problem, and requires no NIO-specific knowledge.

- [ ] Move datagram channels over to using `recvmsg` in the single-read case, instead of `recvfrom`. (#1473)

    This allows us to extract metadata from socket reads.

- [ ] Wire up extracting metadata of known types from `recvmsg`.

    Just a straightforward extension. We need to minimise allocations here, so we should aim to be careful about how we build this. Ideally we'll use the stack.

- [ ] Add a `ChannelOption` that allows users to request ECN information, and then make sure we extract and propagate that information.

- [ ] Update `swift-nio-transport-services` to support this new flag, as `Network.framework` automatically provides this information for us.

**Comment by PeterAdams-A** [comment]
Solved for swift-nio iin #1587, #1590, #1591, #1593 , #1594 and #1596.

I've made an issue in transport services - https://github.com/apple/swift-nio-transport-services/issues/100 to track adding this support there.

**Comment by ovidiuurotaru** [comment]
Can we also read ECN flags using NIO?

**Comment by Lukasa** [comment]
Yes, this is implemented. Set `ChannelOption.explicitCongestionNotification` on your `DatagramBootstrap` to enable it.
