### ISSUE TITLE
Allocation tests flakey on docker swift 5.0

### ISSUE THREAD

**Issue by PeterAdams-A** [apple/swift-nio#1488]
### Expected behavior
Deterministic success or fail.

### Actual behavior
I ran the docker tests of nio on swift 5.0 3 times in a row on my laptop.  2 out of 3 failed with the error 

```
++ echo 'info: 1_reqs_1000_conn: allocations not freed: 0'
++ info '1_reqs_1000_conn: total number of mallocs: 962000'
++ true
++ true
++ echo 'info: 1_reqs_1000_conn: total number of mallocs: 962000'
++ assert_less_than 0 5
++ [[ ! 0 -lt 5 ]]
++ assert_greater_than 0 -5
++ [[ ! 0 -gt -5 ]]
++ [[ -z x ]]
++ max_allowed=963050
++ assert_less_than_or_equal 962000 963050
++ [[ ! 962000 -le 963050 ]]
++ assert_greater_than 962000 962050
++ [[ ! 962000 -gt 962050 ]]
++ fail 'assertion '\''962000'\'' > '\''962050'\'' failed'
++ echo 'FAILURE: assertion '\''962000'\'' > '\''962050'\'' failed'
FAILURE: assertion '962000' > '962050' failed
++ false
--- OUTPUT  END  ---
```
### Steps to reproduce

Run the tests - 

```
docker-compose -f docker/docker-compose.yaml -f docker/docker-compose.1804.50.yaml -p swift-nio2-swift50-prb run --rm test
```

### SwiftNIO version/commit hash

bootstrapShortcut2 branch but I believe also true on master.

### Swift & OS version (output of `swift --version && uname -a`)

NA- it's docker.

**Comment by weissi** [comment]
Thanks @PeterAdams-A . Where did you get the allocation limits from?

**Comment by weissi** [comment]
oh sorry, you had the command there.

**Comment by weissi** [comment]
@PeterAdams-A hmm, so you have one _fewer_ allocations that I would expect.  Could you give me the output of `uname -a` as well as the exact git sha?

**Comment by weissi** [comment]
And actually also the output of `swift --version` because the Swift versions change over time (unlikely tbh since you joined)

**Comment by PeterAdams-A** [comment]
These are now stable enough
