### ISSUE TITLE
Since assigning IP Address 0.0.0.0 as a host, I get (harmless) error at launch of server

### ISSUE THREAD

**Issue by Yourney** [apple/swift-nio#1494]
### Expected behavior
Working in Vapor 4.4.0, I was advised that I needed to set hostname = "0.0.0.0" to make my server visible from outside my home network (after configuring the NAT in my Switch).
That worked great! (without that, I could not call the server from outside)

### Actual behavior
After setting the hostname to "0.0.0.0", I get two errors in my log:
```
Run[56723:4488683] [si_destination_compare] send failed: Invalid argument
Run[56723:4488683] [si_destination_compare] send failed: Undefined error: 0
```
The errors seem harmless, but they are annoying.

### Steps to reproduce

1. Run a server without the hostname = "0.0.0.0"
2. Server runs fine, but cannot be called from outside my home network
3. Now configure the hostname = "0.0.0.0"
4. Server is now reachable from outside (through my NAT) but I get the two error lines when launching the server

### If possible, minimal yet complete reproducer code (or URL to code)
```
import Vapor

// configures your application
public func configure(_ app: Application) throws {
    
    app.http.server.configuration.port = 8181
    app.http.server.configuration.hostname = "0.0.0.0"
}
```

### SwiftNIO version/commit hash
swift-nio 2.16.0

_[the SwiftNIO tag/commit hash]_
swift-nio 2.16.0

### Swift & OS version (output of `swift --version && uname -a`)
Apple Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)
Target: x86_64-apple-darwin19.4.0
Darwin iMac-2015.fritz.box 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

**Comment by Lukasa** [comment]
These logs do not come from NIO, but from the OS. Please use `feedbackassistant.apple.com` to report them.

Thanks!

Cory

**Comment by Yourney** [comment]
Thanks Cory!!
I might just do that!
Wouter
