### ISSUE TITLE
writeWithUnsafeMutableBytes is missing a precondition

### ISSUE THREAD

**Issue by Davidde94** [apple/swift-nio#1503]
### Expected behavior
There should be a `precondition` to crash somewhat gracefully if an invalid value (e.g. `-1`) is passed.

### Actual behavior
Ungraceful malloc crash

### Steps to reproduce
Call `writeWithUnsafeMutableBytes(minimumWritableBytes: -1)`

### SwiftNIO version/commit hash
Every commit

### Swift & OS version (output of `swift --version && uname -a`)
Every version

**Comment by weissi** [comment]
We just discussed this offline. All the necessary checks are there. What happened is that we requested `-1` bytes available at minimum but then still wrote a number of bytes in the buffer.
