### ISSUE TITLE
isKnownUniquelyReferenced logic is duplicated multiple time in HTTPRequest/ResponseHead

### ISSUE THREAD

**Issue by Davidde94** [apple/swift-nio#1504]
The below code block is present a couple of times through the NIO codebase. It can be safely factored out into into a function with the name: `copyStorageIfNotUniquelyReferenced`

```
if !isKnownUniquelyReferenced(&self._storage) {
    self._storage = self._storage.copy()
}
```

**Comment by weissi** [comment]
We should factor this one out into a function called `copyStorageIfNotUniquelyReferenced`.

**Comment by weissi** [comment]
Note, this should be restricted to `HTTPTypes.swift` and leave the `ByteBuffer` code alone where there appear to be duplications but most of them are actually slightly different.

**Comment by Lukasa** [comment]
Agreed: several of `ByteBuffer`'s usages of `isKnownUniquelyReferenced` are explicitly to perform optimised operations (e.g. in `clear`, where we want to allocate a new clean buffer without doing the copy that `self._storage.copy` requires).

**Comment by weissi** [comment]
@Lukasa the problem I could see in `ByteBuffer` is that I failed to annotate every single `isKnownUniquelyRef`'d call with `// this is necessary for correctness` vs. `// this is only an optimisation, not necessary for correctness`.

**Comment by shekhar-rajak** [comment]
Hi,

Do we need to create method only in `HTTPTypes.swift` file and use it inside there only ?

**Comment by weissi** [comment]
@shekhar-rajak yes, it can be a `private mutating func` on the struct in `HTTPTypes.swift`

**Comment by shekhar-rajak** [comment]
Thanks @weissi , I will work on it.
