### ISSUE TITLE
[Performance] Decoding Decodables from ByteBuffer is not zero-copy.

### ISSUE THREAD

**Issue by vlm** [apple/swift-nio#1511]
### Expected behavior

The `ByteBuffer`'s `getJSONDecodable` ought to be zero-copy.

### Actual behavior

The `ByteBuffer`'s `getJSONDecodable` doesn't use zero-copy flags to `getData`.

The `getData`'s `byteTransferStrategy:` option at https://github.com/apple/swift-nio/blob/eb140159386d19fa2c9439af24286982a52fb0b3/Sources/NIOFoundationCompat/ByteBuffer-foundation.swift#L109 could have been set to `.automatic`, that copies everything less than 256kb.

### Steps to reproduce

Observe https://github.com/apple/swift-nio/blob/eb140159386d19fa2c9439af24286982a52fb0b3/Sources/NIOFoundationCompat/Codable%2BByteBuffer.swift#L31

**Comment by vlm** [comment]
Also since the `getData`'s result is not leaked outside of the decoder function, there's opportunity to perform zero-copy without allocating the deallocator function when constructing `Data`.

**Comment by Lukasa** [comment]
We should unconditionally use zero-copy here; copying is only used on small buffers to avoid retaining large ones for small amounts of data, and that’s not really relevant here.

**Comment by Lukasa** [comment]
> Also since the getData's result is not leaked outside of the decoder function, there's opportunity to perform zero-copy without allocating the deallocator function when constructing Data.

I don’t think that’s entirely accurate. There is no guarantee in the `JSONDecoder` API that the passed in `Data` is not sliced to produce any output `Data` objects, at least not that I’m aware of. So we need to defend against the possibility that the `Data` we pass in may be propagated outside the function.

**Comment by weissi** [comment]
exactly because of what @Lukasa says, I decided not to do this but was thinking about asking the Foundation folks if they would be happy to make the guarantee that `JSONDecoder` never still references the `Data` that was passed in.
