### ISSUE TITLE
fix cores count in containers

### ISSUE THREAD

**Issue by gautierdelorme** [apple/swift-nio#1512]
The current `System.coreCount` implementation relies on `_SC_NPROCESSORS_ONLN` so isn't cgroups aware which might have a bad impact for apps runnings in containers (e.g. Docker, Kubernetes, Amazon ECS...).
This issue might affect many users since SwiftNIO examples and documentation recommend the usage of `System.coreCount` to start event loops through `MultiThreadedEventLoopGroup(numberOfThreads: System.coreCount)`. It seems like the community is following these guidelines and relies heavily on `System.coreCount`. For example, Vapor follows the guidelines and also relies on `System.coreCount` (see https://github.com/vapor/vapor/blob/633b2a81f547383aa6becb6ba1ad011dc7174779/Sources/Vapor/Application.swift#L71).

### Expected behavior

`System.coreCount` to return the number of cores available to containers.

### Actual behavior

`System.coreCount` returns the containers' host cores count instead of the number of cores available to containers

### Steps to reproduce

1. Build a `swift-nio` image
   ```console
   $ docker build -t swift-nio:18.04-5.1 -f docker/Dockerfile --build-arg ubuntu_version=bionic --build-arg swift_version=5.1 .
   ```
1. Print `System.coreCount` when a container is not restricted
   ```console
   $ docker run --rm -it --privileged -v $PWD:/code -w /code swift-nio:18.04-5.1 swift run --repl
   Welcome to Swift version 5.1.5 (swift-5.1.5-RELEASE).
     1> import NIO; System.coreCount
   $R0: Int = 4
   ```
1. Print `System.coreCount` when a container is restricted to 1 core using cpusets
   ```console
   $ docker run --cpuset-cpus=0 --rm -it --privileged -v $PWD:/code -w /code swift-nio:18.04-5.1 swift run --repl
   Welcome to Swift version 5.1.5 (swift-5.1.5-RELEASE).
     1> import NIO; System.coreCount
   $R0: Int = 4
   ```
1. Print `System.coreCount` when a container is restricted to 2 cores using CFS quota
   ```console
   $ docker run --cpus=2 --rm -it --privileged -v $PWD:/code -w /code swift-nio:18.04-5.1 swift run --repl
   Welcome to Swift version 5.1.5 (swift-5.1.5-RELEASE).
     1> import NIO; System.coreCount
   $R0: Int = 4
   ```

### SwiftNIO commit hash

[eb140159386d19fa2c9439af24286982a52fb0b3](https://github.com/apple/swift-nio/commit/eb140159386d19fa2c9439af24286982a52fb0b3)

#### Cpusets

- Docker: CPU limit with `--cpuset-cpus`
- Kubernetes: CPU limit with the static policy (see https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies - very rarely enabled)
- Hard Limit the number of cores available to containers

#### CFS quotas

- Docker: CPU limits `--cpus` (or `--cpu-quota`/`--cpu-period` in old versions)
- Kubernetes: CPU limit with the **default** policy (most common setup)
- Soft Limit the number of cores available to containers (by limiting the amount of CPU time available to containers)

### Proposal

We should consider the lack of cpusets support as a bug and fix it. I don't see use cases where we don't want to return the real number of cores available to containers (instead of the host cores count).
About CFS quotas, in most situations users will expect `System.coreCount` to match the value they specify in their CPU limits (instead of the host cores count). This is especially important in Kubernetes since by default users don't have the ability to rely on cpusets (it's an option to enable on the admin side in the kubelet configuration). That said, maybe there are use cases where users want to know exactly the true number of cores available to containers. We could support that use case as well by adding a new method called `System.procCount` which work similarly as `nproc` (ignore CFS quota but respect cpusets). To reduce confusion, we might decide to only add `System.procCount` in the future if the community asks for it.

Let me know what you think. When we all agree on a solution I would love to take a stab at it.

**Comment by Lukasa** [comment]
I agree. More broadly, any platform that supports restricting available resources where we also expose an API to discuss those resources, our APIs should reflect the restrictions if at all possible. I can see no immediate utility in adding an API for the "true" number of cores: NIO isn't shipping a general purpose OS query API, just one that serves specific NIO use-cases, and the theoretical number is unlikely to be important at this time.

So far as I know, the only way to do this is to parse procfs. This is _really_ annoying, and it's going to be error prone, but I think it's all we can do. I think it's sufficient to parse `/proc/stat` and just count the number of times the word "cpu" appears in the output.

This is naturally Linux only, so we'll need to add a separate compile flag in the code, but that's ok.

@gautierdelorme if you're feeling up to it, we'd be happy to review a patch from you that would do this work.

**Comment by gautierdelorme** [comment]
@Lukasa I think CPU stats in `/proc/stat` are shared between hosts and containers. Here is what I had in mind to calculate `System.coreCount` (if linux):

- if CFS quota enabled (`/sys/fs/cgroup/cpu/cpu.cfs_quota_us` exists and `!= -1`)
   - return `/sys/fs/cgroup/cpu/cpu.cfs_quota_us` **/** `/sys/fs/cgroup/cpu/cpu.cfs_period_us` (rounded)
- else if cpusets defined
   - return CPU count from:
      ```swift
      var cpuset = cpu_set_t()
      CNIOLinux_pthread_getaffinity_np(pthread_self(), MemoryLayout.size(ofValue: cpuset), &cpuset)
      (0..<CNIOLinux_CPU_SETSIZE()).filter { CNIOLinux_CPU_ISSET($0, &cpuset) == 1 }.count
      // with `--cpuset-cpus=0-1,3` this will return `3`
      ```
- else
   - return CPU count from `_NPROCESSORS_ONLN` (current behavior)

**Comment by Lukasa** [comment]
I think the cpusets solution doesn't work sensibly if you've already pinned a thread to a CPU, no?

**Comment by gautierdelorme** [comment]
@Lukasa `pthread_getaffinity_np` fetches the set of CPUs available to the specified thread and `pthread_self` return the id of the current thread so we should always get the number of CPUs available for the current thread. Let me know if there are use cases where this is not what we want.
An alternative would be to parse `/sys/fs/cgroup/cpuset/cpuset.cpus`.

**Comment by Lukasa** [comment]
This is not what we want in any case where someone has already set a thread affinity. For example, NIO supports setting the thread affinity of the event loop threads.

**Comment by gautierdelorme** [comment]
Sure but within the event loop threads it seemed reasonable to me to also return only the number of CPUs available to those threads? Seems like I'm wrong so how do you feel about the other solution: parsing `/sys/fs/cgroup/cpuset/cpuset.cpus`?

**Comment by Lukasa** [comment]
I'm happy with that.

The problem is just because your current thread is pinned to a core doesn't mean new threads have to be pinned to that core. That means we don't want you to get confused about the resources available to your program.

**Comment by art-3** [comment]
Makes sense! Thanks for bringing that up @Lukasa. 👍 
I’ll start working on a fix.

**Comment by gautierdelorme** [comment]
@Lukasa Thanks for bringing that up! It makes sense. I’ll start working on a fix! 👍

**Comment by gautierdelorme** [comment]
@Lukasa Your comment made me realize the following implementation might be an issue: https://github.com/apple/swift-nio/blob/eb140159386d19fa2c9439af24286982a52fb0b3/Sources/NIO/LinuxCPUSet.swift#L29-L31

When for example containers are started with `--cpuset-cpus=3`, `System.coreCount` should return `0` but `3` is still a valid CPU id, right?

**Comment by Lukasa** [comment]
Yeah, that's correct, this precondition no longer holds. That's ok, we can just remove it, I think.
