### ISSUE TITLE
NIOPipeBootstrap assertion failed

### ISSUE THREAD

**Issue by hjuraev** [apple/swift-nio#1520]
### Expected behavior
Initialize NIOPipeBootstrap and setup pipeline

### Actual behavior

Assertion failed: leaked open NIOFileHandle(descriptor: 4). Call `close()` to close or `takeDescriptorOwnership()` to take ownership and close by some other means.

### Steps to reproduce

        try NIOPipeBootstrap(group: app.eventLoopGroup).channelInitializer({ channel -> EventLoopFuture<Void> in
            channel.pipeline.addHandler(PipeHandler())
            }).withPipes(inputDescriptor: input, outputDescriptor: output)

### SwiftNIO version/commit hash

Swift Nio 2.17.0

### Swift & OS version (output of `swift --version && uname -a`)

Apple Swift version 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51)
Target: x86_64-apple-darwin19.4.0

**Comment by weissi** [comment]
We've debugged this in the Vapor discord. The respective `input` & `output` fds were kqueues, not pipes so making them non-blocking failed :)
