### ISSUE TITLE
swift-nio repo takes too long to clone

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1528]
We've gotten more reports that `swift-nio` is slow to clone and it seems like the in-repo `gh-pages` branch is becoming a problem. See this:

```
$ git clone https://github.com/apple/swift-nio.git && cd swift-nio
$ git reflog expire --expire-unreachable=all --all
$ git gc --prune=all
$ du -ks .
44996	.
$ git branch -a | cut -d/ -f3 | grep -v -e HEAD -e gh-pages -e master | while read line; do git checkout $line; done && git checkout master # check out all branches (except gh-pages)
$ git remote remove origin # to make the gh-pages branch unreachable
$ git reflog expire --expire-unreachable=all --all
$ git gc --prune=all
$ du -ks .
10720	.
```

So it seems that out of the 45 MB in our repo, the `gh-pages` branch makes up for everything but 11 MB. We ought to move the docs.

CC @tomerd

**Comment by tomerd** [comment]
afaik this is a result of the docsets, which is why I removed them - see https://github.com/apple/swift-nio/pull/1478 for more discussion on that

I suggest the following plan:
1. remove the docsets from the history which will help this issue
2. find a new home for docs outside gh-pages like s3 where we can also include the docsets for folks that need/want them

**Comment by gwynne** [comment]
Can this potentially get some attention in the near-ish future? 😕

**Comment by tomerd** [comment]
hey @gwynne sorry for the delay. this is a bit more involved than originally seemed, but we are working to remove the docs from the repo.

**Comment by gistya** [comment]
It still takes way too long to clone.

**Comment by glbrntt** [comment]
The gh-pages branch has been pruned to remove the docs as they are now hosted on the Swift Package Index: https://swiftpackageindex.com/apple/swift-nio/documentation/nio.

Cloning should be much faster now.
