### ISSUE TITLE
Add better support for handling signals.

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio#153]
The traditional UNIX signal model is not really ideal for programs like NIO, where signal handlers are basically incapable of doing any real work that affects the event loops. Signal handlers are not able to obtain locks or do basically anything that may require that other code on the thread runs, so in a NIO program a signal handler can basically do nothing of interest: it can't even call `malloc`.

This is a bad scene, particularly in Swift, where there is very little Swift code that you can confidently run from a signal handler (no `malloc`, remember!). Given that interacting with signals is a common thing to want to do for servers (e.g. SIGHUP for reloading config), we should build an abstraction that allows NIO-using libraries to handle signals more gracefully. Naturally this will need to be opt-in, but that's ok.

The easiest way to do this is to implement the anonymous self-pipe trick, the standard solution to the problem (TL;DR at program start you create an anonymous pipe that you select on in your event loop, and in a signal handler you write a byte to the pipe and return, allowing you to handle the signal in the loop instead). An alternative option would be to spawn a thread dedicated to signal handling, though that may be a bit excessive (and it requires masking away the signals on all the other threads which is a PITA).

Regardless, we should at some point sit down and provide this abstraction.

**Comment by weissi** [comment]
we have a good example now in [`swift-nio-extras`](https://github.com/apple/swift-nio-extras) more specifically in https://github.com/apple/swift-nio-extras/blob/master/Sources/HTTPServerWithQuiescingDemo/main.swift

@Lukasa would you like to see more to close this issue?

**Comment by Lukasa** [comment]
Nope, works for me for now.
