### ISSUE TITLE
Flaky test: EventLoopTest.testScheduleRepeatedTaskCancelFromDifferentThread

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio#1535]
Seen in #1532:

```
09:13:13 Test Case 'EventLoopTest.testScheduleRepeatedTaskCancelFromDifferentThread' started at 2020-05-29 08:13:13.398
09:23:13 Build timed out (after 10 minutes). Marking the build as failed.
```

We believe we fixed this in #554, but it's back here.

**Comment by Lukasa** [comment]
[Direct build log link](https://ci.swiftserver.group/job/swift-nio2-swift50-prb/2063/console).

**Comment by glbrntt** [comment]
And again in #1526 ([logs](https://ci.swiftserver.group/job/swift-nio2-swift50-prb/2084/console))

**Comment by weissi** [comment]
So weird, #554 was believed to be fixed in August 2018. It hasn't happened since and now it's racy again? Sounds like we may have changed something?
