### ISSUE TITLE
remove the fullFilePath() hack in the tests

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1537]
Once we can depend on Swift 5.3 to be the oldest supported version (NIO 3+), we should remove all the

```swift
#if compiler(>=5.3)
internal func fullFilePath(_ filePath: StaticString = #filePath) -> StaticString {
    return filePath
}
#else
internal func fullFilePath(_ filePath: StaticString = #file) -> StaticString {
    return filePath
}
#endif
```

in the tests again and just use `#filePath`/`#file` where appropriate.

**Comment by glbrntt** [comment]
This was done in https://github.com/apple/swift-nio/pull/1544
