### ISSUE TITLE
Ordering of tasks scheduled with the same deadline on `SelectableEventLoop` is undefined

### ISSUE THREAD

**Issue by glbrntt** [apple/swift-nio#1541]
If two tasks are scheduled on an event loop with the same deadline then the order in which they fire is not guaranteed. This is unlikely to happen in the real world but it is possible. On `EmbeddedEventLoop` it is far more likely to happen as time is controlled. 

We should update `SelectableEventLoop` such that scheduled tasks are ordered by their deadline and ties are broken on the order in which they scheduled. `EmbeddedEventLoop` has already had this treatment.

See also: https://github.com/apple/swift-nio/pull/1540

**Comment by weissi** [comment]
We have to fix this. In the old days where we had only _in N nanoseconds_ API, this was probably okay(ish) because it's impossible to get a clash in the real world (because you'd need to get to equal values back from `DispatchTime.now()` in a row. Even in a tight loop, that's not possible with the time resolution of today's CPUs.

Just as a quick test:

```swift
import Dispatch

func foo() {
    var minDiff: UInt64 = .max

    var tLast: UInt64 = 0
    for _ in 0 ..< 100_000_000 {
        let t = DispatchTime.now().uptimeNanoseconds

        let diff = t - tLast
        if diff < minDiff {
            minDiff = diff
        }

        tLast = t
    }

    print(minDiff)
}

foo()
```

```
$ swiftc -O test.swift && echo ok && ./test
ok
21
```

so the closest I could get these two is 21 which leaves us enough head room because in the real world, we'd allocate a bunch and add things to the `PriorityQueue` etc so it'll be much more than 21 ns difference.

What _is_ a real problem however is the deadline based API. If someone did something like:

```swift
let now = NIODeadline.now()
myEL.preconditionOnEL()

for f in 0..<100 {
    myEL.schedule(deadline: now) {
        print(f)
    }
}
```

then it's reasonable to assume it'll print `0, 1, 2, ..., 99` and not some random order. Today however, this is not true because our `PriorityQueue` isn't a FIFO if two elements have the same priority (where priority is the deadline here).

**Comment by Lukasa** [comment]
I noodled over this a bit this weekend in between doing other things. I went through the following set of ideas, from worst to best. All of them rely on the idea that however we enqueue tasks will be linearizable: that is, if there’s a happens-before edge between the submission of two tasks then they must be de-queued by the loop in that order.

1. Use a 64-bit counter, monotonically incremented as tasks are put into the priority queue.

    In a live system with long lifetime, there is actually a bit of a risk of saturating this counter. As all calls to the execute family of tasks will need to increment this counter a heavily loaded system could absolutely overflow the counter with sufficiently long lifetime. Overflowing the counter is non-recoverable, as the moment that happens we can no longer meet the guarantees that #1909 would require we meet.

2. Use a 64-bit counter per clashing time

    We could evolve this idea by incrementing the 64-bit counter only when we enqueue tasks that clash in time. I think this is computationally just too expensive: it makes the heap operations much slower as we need to search the heap for tasks with the same deadline.

3. Use a 64-bit counter per second.

    Each time we de-queue tasks, we can record `NIODeadline.now()` and store that, along with a 64-bit counter that we increment for each task as long as the time has not ticked forward.

    I think this works pretty well. We can now process approximately 18 quintillion tasks enqueued per second. This is unlikely to be a risk on any real system. However, we don’t get the full benefit of the 128-bits we’ll be storing because in general we’ll “jump” forward in the timestamp: we won’t use each entry in the timestamp. We also have to make system calls to get the timestamp, and while the cost of these is fairly low thanks to the vDSO it’s not the cheapest thing we could do.

4. Use a 128-bit counter.

    So why not go whole-hog and just use a 128-bit counter? This gives us even better resolution: we effectively enqueue the maximum number of 64-bit tasks each second. It also avoids us needing to write somewhat complex code to handle the possibility of saturating the 64-bit counter in a given loop tick. We also replace the expensive system calls with fairly cheap `add` and `jo` instructions.

    Even the branch we add here doesn’t hurt that much as a huge number of production systems will never take it. As noted above, we need to enqueue 18 quintillion tasks to take the branch. A branch taken one in 18 quintillion times is a very very cheap branch. As most event loops won’t ever enqueue that many tasks they won’t ever take the branch, but it provides us the important breathing room for extremely busy loops.
    
     The biggest downside of this approach is that we burn 16 bytes per task. However, this is a bit of trading space for time that I think we can justify, so I recommend this approach.

**Comment by PeterAdams-A** [comment]
@Lukasa is is valid to reset the counter to 0 any time the queue becomes empty? Maybe that would be a way of using a shorter counter.

**Comment by weissi** [comment]
@Lukasa wait, a 64bit counter is definitely enough. The user could submit one work item _per nanosecond_ for over 500 years, and only then would we overflow. I think that's acceptable.

**Comment by Lukasa** [comment]
@weissi Yeah good note, my math had some weird order of magnitude issue in it. We can skip the UInt128 stuff.

As to the "memory ordering questions", the issue isn't `execute` it's `scheduleTask`. This is where we need to be able to tell in what order things get enqueued, as they need to be executed in the order they were enqueued, which right now they are not.

**Comment by weissi** [comment]
> As to the "memory ordering questions", the issue isn't execute it's scheduleTask. This is where we need to be able to tell in what order things get enqueued, as they need to be executed in the order they were enqueued, which right now they are not.

Yes, but that's not relevant for the futures, right? It's definitely relevant for `scheduleTask(deadline: X)`.

**Comment by Lukasa** [comment]
Sure, but #1909 is not only about futures, and _this_ issue explicitly is not about futures.
