### ISSUE TITLE
code of conduct uses old version 1.3.0, should be updated to 1.4

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1555]
Thanks to @gwynne who made me aware that we're using the old version 1.3.0.

IMHO we should update `apple/swift-nio{*,log,metrics,...}` and `swift-server/*` to match the new CoC version.

NIO's version is slightly adapted. The CoC file is three parts:

1. specific header about the project (NIO)
2. very slightly adapted "Covenant Contributor Code of Conduct"
3. footer including where to report.

I'm proposing to leave (1) and (3) as is but to replace (2) by the new version.

For completeness, the middle part (2) right now is slightly adapted from the [original 1.3.0](https://www.contributor-covenant.org/version/1/3/0/code-of-conduct/code_of_conduct.md). The actual diff (curtesy of @gwynne) is:

```diff
--- ORIGINAL_1.3.0    2020-06-14 05:40:10.000000000 -0500
+++ NIO_ADAPTION    2020-06-13 22:27:05.000000000 -0500
-# Contributor Code of Conduct
+### Contributor Code of Conduct v1.3
 As contributors and maintainers of this project, and in the interest of fostering an open and
 welcoming community, we pledge to respect all people who contribute through reporting
 issues, posting feature requests, updating documentation, submitting pull requests or patches,
@@ -28,17 +37,19 @@
 maintainers who do not follow or enforce the Code of Conduct may be permanently removed
 from the project team.

-This Code of Conduct applies both within project spaces and in public spaces when an
+This code of conduct applies both within project spaces and in public spaces when an
 individual is representing the project or its community.

 Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by
-contacting a project maintainer at [INSERT EMAIL ADDRESS]. All complaints will be reviewed and
+contacting a project maintainer at [swift-server-conduct@group.apple.com](mailto:swift-server-conduct@group.apple.com). All complaints will be reviewed and
 investigated and will result in a response that is deemed necessary and appropriate to the
 circumstances. Maintainers are obligated to maintain confidentiality with regard to the reporter
 of an incident.

-This Code of Conduct is adapted from the [Contributor Covenant][homepage],
-version 1.3.0, available at https://www.contributor-covenant.org/version/1/3/0/code-of-conduct.html
-
-[homepage]: https://www.contributor-covenant.org
+*This policy is adapted from the Contributor Code of Conduct [version 1.3.0](https://contributor-covenant.org/version/1/3/0/).*
```

As we can see, the edits are very minimal. I'm proposing to paste [version 1.4](https://www.contributor-covenant.org/version/1/4/code-of-conduct/code_of_conduct.md) verbatim between header & footer. The only modification is of course to replace `[INSERT EMAIL ADDRESS]` :)

**Comment by weissi** [comment]
@tomerd can we just do the CoC update or who'd need to approve?

**Comment by tomerd** [comment]
@weissi I believe this needs to be aligned with https://swift.org/community/#code-of-conduct

so if there are changes required we should propose them there first and then ripple down

**Comment by weissi** [comment]
@tomerd Sounds good to me! Who's responsible for these changes for swift.org ?

**Comment by tomerd** [comment]
if there are changes required, please bring them up in an email to ted / myself and I will bring them up with the core team etc

**Comment by tomerd** [comment]
cc @gwynne

**Comment by Lukasa** [comment]
We now incorporate the CoC by reference to the Swift project (see #2440).
