### ISSUE TITLE
`ByteBuffer.clear(minimumCapacity:)` uses `_Capacity` as it's type for `minimumCapacity`

### ISSUE THREAD

**Issue by glbrntt** [apple/swift-nio#1589]
### Expected behavior

NIO shouldn't expose `_UnderscoreInternal` types in its public API.

### Actual behavior

`ByteBuffer.clear(minimumCapacity:)` uses `_Capacity` instead of `Int`, see:

https://github.com/apple/swift-nio/blob/ee8acd9b3d0e2f00b852743f86075c35bea9e986/Sources/NIO/ByteBuffer-core.swift#L711

**Comment by glbrntt** [comment]
We should probably just deprecate it and replace it with `public mutating func clear(minimumCapacity: Int)`

**Comment by Lukasa** [comment]
Good spot
