### ISSUE TITLE
swift-nio repo takes too long to clone 

### ISSUE THREAD

**Issue by OHeroJ** [apple/swift-nio#1592]
swift-nio repo takes too long to clone

**Comment by ktoso** [comment]
How long is long?
It very could be a matter of your network, or github specifically.

For reference

> time git clone https://github.com/apple/swift-nio 
> 1.77s user 0.53s system 41% cpu 5.523 total # from japan

Is pretty ok

**Comment by glbrntt** [comment]
This is a dupe of #1528 -- the `gh-pages` branch is quite large which causes _some_ slowness.

**Comment by ktoso** [comment]
Ah the docs, makes sense :) +1ing that ticket

**Comment by OHeroJ** [comment]
More than 5 minutes
