### ISSUE TITLE
HTTPDecoder crashes with nil optional

### ISSUE THREAD

**Issue by keniwhat** [apple/swift-nio#1595]
### Expected behavior
Application should run.

NOTE: SSL connection is used.

All combinations fail on Linux.

### Actual behavior

Application crashes at line 341 in swift-nio/NIOHTTP1/HTTPDecoder with a nil optional.

### Steps to reproduce

1. Build an app on Linux use vapor-websocketkit.
2. Run app.

When using vapor web socket-kit, my swift app crashes at line 341 in swift-nio/NIOHTTP1/HTTPDecoder with a nil optional.

Debugging the code, the 'swap' function did not work.

### SwiftNIO version/commit hash

8a865bd15e69526cbdfcfd7c47698eb20b2ba951

### Swift & OS version (output of `swift --version && uname -a`)

Swift version 5.2.4.
Swift version 5.1.5.

Linux: Linux Mint 19 Cinammon.

**Comment by Lukasa** [comment]
> Debugging the code, the 'swap' function did not work.

This is not possible: the `swap` function _must_ work. It is more likely that there is either a re-entrancy or threading bug.

Do you have a call stack you can provide please? If you aren't seeing one normally, you can run your process under `lldb` until it crashes, and then use `bt` to print a backtrace. Can you also provide details on how you're building your application?

**Comment by tanner0101** [comment]
FWIW, this was originally reported here: https://github.com/vapor/websocket-kit/issues/73. If it seems like it's actually in WSKit lmk.

**Comment by keniwhat** [comment]
This was first reported against vapor/websocket-kit.  I am having trouble reproducing this issue in my latest code base, after swapping vapor/wesbsocket-kit back in.  Will backtrack and try to reproduce.

**Comment by Lukasa** [comment]
Did we get anywhere here?
