### ISSUE TITLE
EventLoopFuture with Result<> -> Result<> closure

### ISSUE THREAD

**Issue by tschuett** [apple/swift-nio#1599]
I am looking for a flatMap variant where the closure takes a Result<> and returns a Result<> or an EventLoopFuture
Is this possible?
_ callback: @escaping (Result<Value,SomeError) -> EventLoopFuture<NewValue>
or
_ callback: @escaping (Result<Value,SomeError) -> Result<NewValue, SomeOtherError>
I want to propagate the error through the chain. In the former case, I would return a failed future.

**Comment by glbrntt** [comment]
> I want to propagate the error through the chain. In the former case, I would return a failed future.

You can think of there being two paths for a callback chain: a success path and a failure path. 

Some functions stay on the same path while others can move between the two. `map`, for example, will only execute if you're on the success path and will guarantee that you stay on the success path. `recover` will only be executed on the failure path and guarantees that you move to the success path.

As such, if you're on the failure path (i.e. in an error state) then that error will always be propagated _unless_ you explicitly move back to the success path with `recover` or `flatMapError`. Mapping a `Result` into a new future just to propagate the error is therefore not necessary.

**Comment by tschuett** [comment]
Maybe I missed something:
`var fut = EventLoopFuture<Value>`
If `fut` failed, then I want to return a `GRPCStatus` with some callback.
If `fut` succeed, then I have some `flatMap` that will continue on the success path.

**Comment by Lukasa** [comment]
What does the success path ultimately produce? Note that in the end you'll need to have a `Future` of a single type here.

**Comment by tschuett** [comment]
I have a function that returns an `EventLoopFuture<GRPCStatus>`. I used to have a long list of flatMaps processing the result and finally return GRPCStatus(code: .ok, message: nil) unconditionally . I ignored errors for the moment. What happens, if a have an error in the middle. Can I do an early return?

**Comment by glbrntt** [comment]
If one of your `flatMap`s returns a failed future, then subsequent `flatMaps` will not be executed.

If `doSomethingElse` returns a _failed_ future then the callback containing `doAnotherThing()` will not be called. `status` will be a _failed_ future holding the error that was thrown by `doSomethingElse`. 

```swift
let status: EventLoopFuture<GRPCStatus> = doSomething().flatMap { someValue in
  doSomethingElse(someValue)
}.flatMap { anotherValue in
  doAnotherThing(anotherValue)
}
```

**Comment by tschuett** [comment]
Yes, but this only works, if all intermediate Futures are of type EFT<GRPCStatus>. Right?

**Comment by glbrntt** [comment]
Is your goal to _always_ end up with an `EventLoopFuture<GRPCStatus>` in the _success_ state, irregardless of an error?

**Comment by tschuett** [comment]
Yes, but the intermediate futures could be `EFT<A>` , `EFT<B>` , and `EFT<C>` on the success path. It would end with `EFT<GRPCStatus>`

**Comment by glbrntt** [comment]
[`recover`](https://github.com/apple/swift-nio/blob/3cfb3f1d6efb05d1e93be342ea3d3e99aed00bb5/Sources/NIO/EventLoopFuture.swift#L648) will only be executed in the failure state and guarantees that you will move back to the success state:

```swift
let status: EventLoopFuture<GRPCStatus> = doSomething().flatMap { someValue in
  doSomethingElse(someValue)
}.flatMap { anotherValue in
  doAnotherThing(anotherValue)
}.recover { error in
  convertErrorToStatus(error)
}
```
