### ISSUE TITLE
`channelRead` is triggered w/ autoRead = false

### ISSUE THREAD

**Issue by helje5** [apple/swift-nio#160]
### Expected behavior
No `channelRead` is triggered on the inbound handler if autoRead is off, and the outbound handler does no `read()` request.

### Actual behavior
After connecting to a server socket, one `read` seems to happen regardless of the autoRead option:
```swift
  .childChannelOption(ChannelOptions.autoRead, value: false)
```

Subsequent input is not reported (just the first stuff entered in `nc`).

### Steps to reproduce

I have no minimal reproduce setup yet. Lazy.

### SwiftNIO version/commit hash

1.1

### Swift & OS version (output of `swift --version && uname -a`)

4.0.3 , macOS

**Comment by normanmaurer** [comment]
@helje5 thats clearly a bug... let me look into it
