### ISSUE TITLE
Spin `check_no_api_breakages.sh` out and provide a common github action

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-nio#1600]
`check_no_api_breakages.sh` can be useful to projects to help ensure sure they don't accidentally break apis while adding new features.  Since it requires `jq` and a non-Xcode Swift toolchain (for `swift-api-digester` support), it isn't that easy to run on a Mac.

So the request here is to spin out the script and provide a standard GitHub action that enabled the easy wiring of this script so it could be run on PRs/branches to ensure projects don't break.

One important key would be it needs to work like most CI setups, where it doesn't need any GitHub credentials.  The action should just pass/fail, and the logs can provide the details for folks.  That way the action doesn't propose any security risks to teams to being able to enable it on their repos.

**Comment by Lukasa** [comment]
@tomerd Does this sound like something we should be shipping?

**Comment by thomasvl** [comment]
Any word on exposing this for other projects to use?

**Comment by Lukasa** [comment]
ping @tomerd

**Comment by tomerd** [comment]
Sorry for the delay, I have not seen this until now for some reason. my suggestion on this would be to have this integrated in to SwiftPM rather than ship as a separate script. There is actually already a JIRA for this: https://bugs.swift.org/browse/SR-10540, if you are interested in helping out this could be a fun project

**Comment by FranzBusch** [comment]
Closing this since it has been merged into the main branch of SPM now and is available in nightly snapshots. It can be used with `swift package diagnose-api-breaking-changes [sha/branch/tag]`
