### ISSUE TITLE
NIO will not build when used in command-line generated .xcodeproj

### ISSUE THREAD

**Issue by kmahar** [apple/swift-nio#1601]
Hey all - happened to run into this issue creating a fresh project depending on the MongoDB driver (which depends on NIO 2.0.0 up to the next major version). 

Due to a SwiftPM bug which doesn't apply `cSettings` to Swift targets (see discussion [here](https://forums.swift.org/t/xcode-swiftpm-integration-ignores-csettings/38487)), the driver currently doesn't build via the Xcode SwiftPM integration, so we (and users) have to do things the old way with `swift package generate-xcodeproj`. 

Note that we actually have a [PR for the driver](https://github.com/mongodb/mongo-swift-driver/pull/513) open right now which removes our need to use `cSettings`, so the need to generate `.xcodeproj`s in that way becomes a bit less important for us pretty soon, but I figured I would raise this issue nonetheless.

### Expected behavior
NIO builds successfully when used in a command line-generated .xcodeproj.

### Actual behavior
Errors:

```
/Users/km/MongoRepro/.build/checkouts/swift-nio/Sources/CNIODarwin/include/CNIODarwin.h:21:10: Include of non-modular header inside framework module 'CNIODarwin': 
'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/netinet/ip.h'

/Users/km/MongoRepro/.build/checkouts/swift-nio/Sources/NIO/ControlMessage.swift:16:8: Could not build Objective-C module 'CNIODarwin'
```

### Steps to reproduce

1. Create a new empty project using the `Package.swift` in [this gist](https://gist.github.com/kmahar/3784513967fc22af55a2d31bbc4362bb).
2. Run `swift package generate-xcodeproj` from the command line.
3. Open the resulting `.xcodeproj` in Xcode and attempt to build.

### SwiftNIO version/commit hash
I believe this was introduced by f12803dbf1e535c6c7fb0a52a6240d0349451a9b since it added both of the lines which the errors above point to.

The error is present when pinned to that exact commit, but does not occur one commit prior (ee8acd9b3d0e2f00b852743f86075c35bea9e986).

### Swift & OS version (output of `swift --version && uname -a`)
```
Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
Target: x86_64-apple-darwin19.5.0
Darwin kaitlin.fios-router.home 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
```

Also I'm using Xcode 11.6 in case that's helpful. Let me know if you need any more info.

**Comment by gkaindl** [comment]
Just a quick tip for others bitten by this problem, who come here through Google search: Until this is getting addressed in a new release, you can pin NIO to 2.19.0 as workaround in your main app's `Package.swift`, even if NIO actually gets pulled in through a dependency of your main app as a sub-dependency.

```
dependencies: [
    .package(
      url: "https://github.com/apple/swift-nio",
      .exact("2.19.0")
    ),
   // your other dependencies here
]
```

Run `swift package resolve`, and you can build it again.

Sorry for adding this comment here without adding anything to the issue itself, I was just thinking it might be helpful for some people, since NIO is a dependency in many packages where people might not even be aware that NIO is being used, so the build error might be confusing to some.

**Comment by Lukasa** [comment]
Good catch @kmahar, thanks. I think the fix is easy, one second.

**Comment by kmahar** [comment]
thanks for the quick fix and release @Lukasa!
