### ISSUE TITLE
TLS Certificate Transparency Support?

### ISSUE THREAD

**Issue by orj** [apple/swift-nio#1602]
Just a question really.  Can/does SwiftNIO support verifying Signed Certificate Timestamps for TLS connections? Thus implementing Client-side Certificate Transparency verification similar to what Apple Transport Security does?

Thanks

**Comment by Lukasa** [comment]
SwiftNIO does not do TLS. [SwiftNIO SSL](https://github.com/apple/swift-nio-ssl) does. Currently that project does not validate SCTs when running on Linux, but it does do so when running on Apple platforms.
