### ISSUE TITLE
Can't Archive Xcode project with Swift-NIO 2.20.0 dependency

### ISSUE THREAD

**Issue by franck-clement-ug** [apple/swift-nio#1603]
Hi ! 

Since the release of the version 2.20.0 yesterday, I'm experiencing issues building one of my project that includes the Swift-NIO project as an SPM dependency.

When archiving I have this issue:

`Integer literal '3735928559' overflows when stored into 'Int'`

![Capture d’écran, le 2020-07-30 à 11 28 41](https://user-images.githubusercontent.com/60363334/88942196-f1dcf980-d257-11ea-8674-1906609457f4.png)

The Archiving task worked before with the 2.19.0 Swift-NIO version.

I'm having an issue with a project importing [grpc-swift](https://github.com/grpc/grpc-swift) and Swift-NIO is a dependency of it so I can't explicitly tell SPM to fetch the 2.19.0 version.

Thank you in advance for those of you investigating this issue.

### Expected behavior
The project is archived properly

### Actual behavior
The project archiving task failed

### Steps to reproduce

With Xcode 11.6
1. Create a single view iOS Application
2. Import Swift-NIO 2.20.0 through SPM

![Capture d’écran, le 2020-07-30 à 11 30 51](https://user-images.githubusercontent.com/60363334/88942358-281a7900-d258-11ea-9ed1-2750be3f72ea.png)

3. Product > Archive 
4. You will have the `Integer literal '3735928559' overflows when stored into 'Int'` build error
### SwiftNIO version/commit hash

2.20.0

### Swift & OS version (output of `swift --version && uname -a`)
`Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
Target: x86_64-apple-darwin19.5.0
Darwin mbp-de-franck 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64`

**Comment by glbrntt** [comment]
Thanks for reporting this, it should be fixed by #1604.

> I'm having an issue with a project importing grpc-swift and Swift-NIO is a dependency of it so I can't explicitly tell SPM to fetch the 2.19.0 version.

Just a note on this: you can add SwiftNIO as a dependency directly to your package and require that the version is less than 2.20.0. As long as SwiftPM can find a version of SwiftNIO which satisfies your direct requirement and gRPC Swift's version requirement on SwiftNIO then it should be fine. Of course that's not the correct solution to this problem but it's worth noting as a temporary workaround.

**Comment by franck-clement-ug** [comment]
@glbrntt Thanks you for the fix information. 

And I'll definitely try you suggestion to workaround and explicitly set the version to 2.19.0 until fixed

**Comment by PeterAdams-A** [comment]
I have just published swift-nio 2.20.1 which should solve this issue for you.
