### ISSUE TITLE
Consider creating public EventLoopGroupProvider type

### ISSUE THREAD

**Issue by pokryfka** [apple/swift-nio#1608]
`EventLoopGroupProvider` type is used in a number of swift-server libraries, example from [AsyncHTTPClient](https://github.com/swift-server/async-http-client/blob/c9a9bf061d713c91ee9974fa8a6afe413acfd0e9/Sources/AsyncHTTPClient/HTTPClient.swift#L737-L743):

```swift
    /// Specifies how `EventLoopGroup` will be created and establishes lifecycle ownership.
    public enum EventLoopGroupProvider {
        /// `EventLoopGroup` will be provided by the user. Owner of this group is responsible for its lifecycle.
        case shared(EventLoopGroup)
        /// `EventLoopGroup` will be created by the client. When `syncShutdown` is called, created `EventLoopGroup` will be shut down as well.
        case createNew
    }
```

Currently different libraries (have to) implement (copy and paste) the same type in different namespaces.

This is a bit of a hassle as it requires mapping of "the same" type in different namespaces, example: https://github.com/pokryfka/aws-xray-sdk-swift/pull/49#discussion_r464148735

I think it would be very convenient if `SwiftNIO` defined it  and in such way promoted the pattern.

CC @ktoso

**Comment by Lukasa** [comment]
I think that seems like a reasonable enough request. As the feature is very small, this can be something that someone in the community provides.

**Comment by pokryfka** [comment]
@Lukasa 

the implementation is literally copying the example above to new namespace - hopefully for the last time!

please let me know if to create PR with the change

and if you expect any unit tests 🤔

**Comment by Lukasa** [comment]
Feel free to create the PR. I think I'd like a quick unit test that confirms that the `EventLoopGroup` you put in comes back out. This is not normally a test we'd bother writing, but it's a bad idea to have API surface that is completely unused within the project.
