### ISSUE TITLE
Poor performance of ByteBuffer. 

### ISSUE THREAD

**Issue by c-scalcucci** [apple/swift-nio#1612]
### Expected behavior
Our team is running the same architecture, with the same objects, with the same TOS, on the same TCP connection to our core. Swift code is running on SwiftNIO and Java is running Mina.

Being pretty similar, down to the point where Netty split from Mina, I expected to see two's ByteBuffers performing at around the same cost.

### Actual behavior
Swift code is taking much, much longer in the ByteBuffer when profiled. It seems a majority of the time is spent in indexing. We are both using a line based decoder. 

For a simple ping with 500 bytes, and an ack, the round trip is taking 70ms. 12ms are spent in crypto, and the rest is the reader and writer. For comparison, the Java code is spending 6ms in crypto, and only 14ms in reading and writing. 

I'll drill down and post the actual results of the profile. 

I did notice an issue raised about the performance, in https://github.com/apple/swift-nio/pull/1418/

Our team was wondering if this has been noticed by anyone else, and if PR-1418 is much farther out. We have been waiting for that release for quite a while. We are running in an extremely concurrent environment with an extremely complex state machine, and every ounce of performance and battery life matters. 

### Steps to reproduce

1. Set up a simple TCP client and receive any number of bytes delineated on both SwiftNIO and Mina.
2. Observe the latency and run a profile
3. The Swift ByteBuffers are far more expensive. 

### Swift NIO Version
2.20.2

**Comment by Lukasa** [comment]
#1418 is not about the performance of `ByteBuffer` but instead of `ByteBufferView`, and represents a microptimisation.

Before you go _any_ further, are you profiling in release mode (i.e. built with `swift build -c release`)? If you are not, the performance cannot possibly be comparable.

**Comment by c-scalcucci** [comment]
Going to close the issue, not quite sure why the profiler returned so much time spend in the TCP stack for v.2.14, but it's running much faster in v2.20.

Seems like now our major drag is libcrypto.
