### ISSUE TITLE
Practicality issues when Binding to UNIX Domain Socket Paths

### ISSUE THREAD

**Issue by dimitribouniol** [apple/swift-nio#1619]
### Expected behavior
When Binding to a UNIX Domain Socket Path, NIO doesn't claim the path if it already exists, nor does it remove the path during shut down. This means it is entirely up to the application to do this tidy work, which is impractical in the vast majority of cases. It seems that in most traditional cases (for C-based servers anyways), the server will always claim rights to a socket path file by removing the old one and binding to a new one, so it can launch back up quickly in the event of a crash.

I thus propose that the server bootstrap should always clean up its socket file (see the workaround code below), and additionally, that we have a configuration option to try and remove an existing file before binding to it, that would be true by default, but can be turned off if the user does not want that behavior for a specific reason.

### Actual behavior
If the socket path file already exists, NIO will fail to bind to it, regardless if it is in use or not. Additionally, after the server shuts down cleanly, the previous socket path is not cleaned up, meaning the server will not start a second time with the same path.

### Steps to reproduce

1. Create a `ServerBootstrap` as you usually would
2. Call bootstrap.bind(unixDomainSocketPath: socketPath)
3. Shut the server down using any method, and try to bind to the same socket path once again

### If possible, minimal yet complete reproducer code (or URL to code)

An example of this issue, and a workaround, is provided as a part of a rejected proposal to Vapor: https://github.com/vapor/vapor/pull/2371

- Server startup: https://github.com/dimitribouniol/vapor/blob/backup/unix-domain-sockets/Sources/Vapor/HTTP/Server/HTTPServer.swift#L254-L346
- Workaround: https://github.com/dimitribouniol/vapor/blob/backup/unix-domain-sockets/Sources/Vapor/HTTP/Server/HTTPServer.swift#L390-L446

### SwiftNIO version/commit hash

Last tested on 2.20.2

### Swift & OS version (output of `swift --version && uname -a`)

```
Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
Target: x86_64-apple-darwin19.6.0
Darwin Mochi-Dev-iMac-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64
```

**Comment by tanner0101** [comment]
+1 to ServerBootstrap handling this

**Comment by Lukasa** [comment]
Yup, I agree that both of these are worth implementing.

**Comment by dimitribouniol** [comment]
Thank you @AndriusA, @Lukasa!
