### ISSUE TITLE
NonBlockingFileIO should return FileRegion from read/write function as well

### ISSUE THREAD

**Issue by sveamarcus** [apple/swift-nio#1620]
https://github.com/apple/swift-nio/blob/a0f6a48ec0f52af49cdf8274757a2bd1ec9f3295/Sources/NIO/NonBlockingFileIO.swift#L494

After discussion with @Lukasa on Discord, it's been shown that the function should not return FileRegion as can be seen from the comments in #975. Hence, just a nit to remove FileRegion from the function docs return type.

**Comment by Lukasa** [comment]
Sorry, I wasn't clear: I think this function _should_ have returned `FileRegion`. Ideally we'd add a version of this that does.

**Comment by sveamarcus** [comment]
I stand corrected 👍 

Sorry for any confusion.

**Comment by Lukasa** [comment]
After some discussion with @AndriusA we've come to the conclusion that there is probably limited utility in adding the `FileRegion` to the return value, so we've agreed to just fix up the documentation.

**Comment by Lukasa** [comment]
Resolved by #1644.
