### ISSUE TITLE
Project Icon Missing

### ISSUE THREAD

**Issue by helje5** [apple/swift-nio#163]
Seriously. An Apple project w/o a Logo? Maybe some swallow crashing into a S/390 or something? Or a bug running around in an Xserve? Neo from Matrix? Something!

**Comment by Lukasa** [comment]
Thanks, but I don’t think we need a github issue for this. A logo will arrive when it arrives. Let’s let this issue tracker focus on the software itself. 😁

**Comment by helje5** [comment]
still pending ;-)
