### ISSUE TITLE
Is ByteBuffer thread-safe?

### ISSUE THREAD

**Issue by dirk68-fu** [apple/swift-nio#166]
Sorry, if this question is dumb, because the whole purpose of the object may be to allow exactly this, but the documentation does not specifically clarify this.

Is it safe to write from one thread and read from another?

**Comment by Lukasa** [comment]
Yes, but it won’t do what you want. 

ByteBuffer is a *copy on write* value-type data structure. If you are writing and reading from multiple threads, you necessarily have multiple references to the underlying buffer. Thus, the reading thread will not see the writes from the writing thread. 

In general, however, it is recommended that you don’t do this: it only makes sense if you conceptualise of ByteBuffer as a reference type, which is not the right way to think about it.

**Comment by normanmaurer** [comment]
@dirk68-fu just to clarify its still "valid" to write to the ByteBuffer from one thread, pass it to another thread and read from it tho. Basically the reading side will see a "snapshot" of the written data.
