### ISSUE TITLE
Sync execute task

### ISSUE THREAD

**Issue by purkylin** [apple/swift-nio#1680]
I have a handler to deal with request:

```swift
func channelRead(context: ChannelHandlerContext, data: NIOAny)  {
    //  promise or DispatchQueue
   decrypt(data, iv)
   iv += 1
}
```

How to guard above code sync execute, otherwise decrypt will failed as wrong iv.

**Comment by PeterAdams-A** [comment]
I'm not quite sure what you mean - do you mean you're queuing the decrypt to another event loop?  if so they should by default execute in the order you add them.

**Comment by Lukasa** [comment]
Also within the same event loop, so long as there are no calls out of this channel handler between `decrypt` and `iv += 1`.

**Comment by purkylin** [comment]
Thanks, it's my mistake. That should be sync
