### ISSUE TITLE
Typo in IdleChannelHandler is assigning a scheduled task to the wrong member field

### ISSUE THREAD

**Issue by abidon** [apple/swift-nio#1681]
By browsing the code I think I found a typo in `IdleChannelHandler.makeAllTimeoutTask` (see [here](https://github.com/apple/swift-nio/blob/2.23.0/Sources/NIO/ChannelHandlers.swift#L302-L310)).

When makeAllTimeoutTask is rescheduling, the resulting `Scheduled<T>` is assigned to `scheduledReaderTask` instead of `scheduledAllTask`.

**Comment by Lukasa** [comment]
Yup, looks like a typo to me. I think it ought to be possible to reproduce a bug there in a unit test, which would make a nice contribution along with a fix. Do you think you could do that?

**Comment by stepan-ulyanin** [comment]
Working on this one
