### ISSUE TITLE
Support for SwiftNIO on iOS

### ISSUE THREAD

**Issue by iychche** [apple/swift-nio#1685]
We are using SwiftNIO on iOS to implement a rsocket-swift library. This will support bi-directional communication on a websocket connection. We came across the following issue:

https://github.com/apple/swift-nio/issues/130

The issue seems to indicate that SwiftNIO uses POSIX networking which does not activate the cellular radio or on-demand VPN. However, the issue is from 2018. Has this been resolved? Are there any gotchas to using SwiftNIO on iOS? Also, are there any tests that we can run to make sure activating cellular radio is not an issue (We are very new to mobile/iOS development)

**Comment by Lukasa** [comment]
Yes, swift-nio-transport-services wraps Network.framework, which takes care of dealing with the complex networking situation on iOS. That’s the recommended way to run on iOS.
