### ISSUE TITLE
Invalid data (type) passed to channelRead in ChannelInboundHandler causing crash

### ISSUE THREAD

**Issue by matejukmar** [apple/swift-nio#1688]
I have set up custom websocket NIO chat server which also accepts also HTTP requests. I have two types of `ChannelInboundHandler` one with `typealias InboundIn = HTTPServerRequestPart` and the other with `typealias InboundIn = WebSocketFrame`

The crash occurs in `HTTPServerRequestPart` type of `ChannelInboundHandler` in this function:
```
  public func channelRead(context: ChannelHandlerContext, data: NIOAny) {
    let frame = self.unwrapInboundIn(data)
```

Crash occurs when calling `self.unwrapInboundIn(data)` because the data is not of `HTTPServerRequestPart` type but for some reason data type is actually `WebSocketFrame`. As inspected self.unwrapInboundIn forces unwrapping to type HTTPServerRequestPart. 

Crash log looks like this:
```
Fatal error: tried to decode as type HTTPPart<HTTPResponseHead, IOData> but found WebSocketFrame with contents 
```

The crash occurs very rarely, on average once every week or so.

I'm not clear how could this happen and if I'm doing something wrong when upgrading channel to websocket, although I can't see anything wrong. 

There is also no way of optionally unwrap data which is of type NIOAny since all tryAs methods are internal.

### Expected behavior
No crash 

### Actual behaviour
It crashes

### Steps to reproduce
Not sure as it happens very rarely

### SwiftNIO version/commit hash

c3e2359c55cd8b47207ab7363b77c9c398a95294

### Swift & OS version (output of `swift --version && uname -a`)

Swift version 5.2.2 (swift-5.2.2-RELEASE)
Target: x86_64-unknown-linux-gnu

**Comment by Lukasa** [comment]
> There is also no way of optionally unwrap data which is of type NIOAny since all tryAs methods are internal.

This is intentional: we'd generally prefer you to remove the channel handler and replace it with another one than to try to conditionalise your handlers.

> I'm not clear how could this happen and if I'm doing something wrong when upgrading channel to websocket, although I can't see anything wrong.

This can happen if you are not removing your handlers fast enough from the pipeline. Can you show me your upgrade code?

**Comment by hieunc278** [comment]
Dear @Lukasa 

It seems I met the same issue.

This is my ChannelInboundHandler : 

final class TCPClientHandler: ChannelInboundHandler {
    public typealias InboundIn = Messsage_Response
    public typealias OutboundOut = ByteBuffer


    public func channelRead(context: ChannelHandlerContext, data: NIOAny) {
        let res = self.unwrapInboundIn(data) // Crashed here.
        print("Result code : \(res.resultCode), otp code : \(res.otp)")
    }
}

And this is error description : 

Fatal error: tried to decode as type Messsage_Response but found IOData with contents ioData(IOData { ByteBuffer { readerIndex: 0, writerIndex: 9, readableBytes: 9, capacity: 2048, storageCapacity: 2048, slice: _ByteBufferSlice { 0..<2048 }, storage: 0x00007fd9ea816000 (2048 bytes) } }): file NIO/NIOAny.swift, line 200

So could you please review and let me know how can I decode the data to my model object ( Message_Response ) in this case correctly ?

**Comment by Lukasa** [comment]
> So could you please review and let me know how can I decode the data to my model object ( Message_Response ) in this case correctly ?

I can't answer this without knowing more about your channel handler. How is `Message_Response` encoded? What is it being sent over? How is it delimited?

**Comment by hieunc278** [comment]
Thanks @Lukasa for your feedback.

Regarding Message_response, it is sent from Netty Server, with ProtobufEncoder as encoder. 

I don't get your mean about delimited, could you explain more ?

Message_Response is generated from profile

**Comment by hieunc278** [comment]
@Lukasa 

For more details, at client side, I used swift-protobuf library, so am I need any decoder from swift-protobuf to decoder Message_Response, or I could you unwrapInboundIn is enough

**Comment by Lukasa** [comment]
By "delimited" I mean, how do you know when one message ends and another one begins? Protobuf is not "self-delimiting" (it doesn't have a good marker of where the messages begin and end), which means you have to provide some other way of knowing where the messages start and stop. Normally this uses length-prefixed framing or something similar.

> so am I need any decoder from swift-protobuf to decoder Message_Response, or I could you unwrapInboundIn is enough

Yes, you need a decoder from swift-protobuf. `unwrapInboundIn` does not do any decoding, it is effectively just a type assertion.

**Comment by hieunc278** [comment]
Thank you very much for your patient @Lukasa .

And you are right. I have could decode that data to Message_Response as well by below code section

            var buffer = self.unwrapInboundIn(data)
            let bytes = buffer.readBytes(length: buffer.readableBytes)!

            let receivedData = Data(bytes: bytes, count: bytes.count)
            let decodedInfo = try Messsage_Response(serializedData: receivedData)

Thank you again
