### ISSUE TITLE
TimeAmount does not support +=, -=, etc...

### ISSUE THREAD

**Issue by dimitribouniol** [apple/swift-nio#1690]
### Expected behavior
Sometimes it is useful to manipulate time amounts when building up a delay for `.scheduleTask()` for instance, and if that iteration fails, we would want to `delay += .milliseconds(5)` to add 5 milliseconds to our delay and try again.

### Actual behavior
You would get a lovely `Referencing operator function '+=' on 'FloatingPoint' requires that 'TimeAmount' conform to 'FloatingPoint'` compile time error if such a statement were attempted.

In general, this is not strictly _necessary_ (I can get by with my local extension, for instance), but is certainly a good quality of life improvement to save a future developer's marbles when they don't realize `+=` conformance from `+` isn't automatic 🙃.

I'm mostly writing this to field input to see if such a PR would be welcome or not (besides, makes for a great first issue for newcomers 😉)

### If possible, minimal yet complete reproducer code (or URL to code)

```
var retryDelay = TimeAmount.milliseconds(0) // <-- A `.zero` here would also be stellar,
                                        // but maybe conforming to `AdditiveArithmetic` would be even better?

// (in your favorite accent): One Iteration Later...
retryDelay += .milliseconds(5) // Compiler error 😔
retryDelay = retryDelay + .milliseconds(5) // Works, but 🙃
```

### SwiftNIO version/commit hash

2.23.0

### Swift & OS version (output of `swift --version && uname -a`)

```
Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)
Target: x86_64-apple-darwin19.6.0
Darwin Dimitri-Bouniols-16-inch-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
```

**Comment by Lukasa** [comment]
I think an `AdditiveArithmetic` conformance isn’t unreasonable here.

**Comment by dimitribouniol** [comment]
@joshrutkowski @Lukasa Thank you both for getting this in so quickly!
