### ISSUE TITLE
Arm64 Architecture Missing

### ISSUE THREAD

**Issue by bdkjones** [apple/swift-nio#1693]
I rely on Swift-NIO in my app. I'm installing it via the Swift Package Manager in Xcode 12.2 on Big Sur 11.0.1 running on a 13" M1 MacBook Pro.

When I attempt to build, Xcode informs me that it can't find the `arm64` architecture for Swift-NIO:

<img width="347" alt="Screen Shot 2020-11-21 at 00 18 07" src="https://user-images.githubusercontent.com/926566/99871618-ef006e80-2b90-11eb-8a9e-2e6d5458f0b9.png">

Xcode auto-builds packages as they're downloaded, I guess, so I don't have any manual control over the build settings (that I'm aware of; I'm fairly new to SPM). Here are the packages I have installed in this project:

<img width="626" alt="Screen Shot 2020-11-21 at 00 18 35" src="https://user-images.githubusercontent.com/926566/99871647-18b99580-2b91-11eb-9681-028347c9aee5.png">

Since this is an Apple-provided framework, I had assumed `arm64` support would be in place. I'm sure I've simply screwed something up, but I'd appreciate a tip on how to fix this. Thanks!

**Comment by Lukasa** [comment]
SwiftNIO is shipped as source-only: we don’t ship binaries. Our source supports arm64, but whether or not the arm64 version is available is not up to us: your software needs to build it locally.

How is your build system set up? Are you targetting both architectures? It may be worth clearing out your DerivedData folder and performing a complete rebuild.

**Comment by Lukasa** [comment]
As you also commented [on the forums](https://forums.swift.org/t/xcode-12-2-spm-swift-nio-fails-to-build-for-apple-silicon-arm64/42197/2) I’m going to close this to centralise conversation there.
