### ISSUE TITLE
ByteToMessageDecoder needs documentation update for #1426

### ISSUE THREAD

**Issue by mlilback** [apple/swift-nio#1714]
The documentation for ByteToMessageDecoder says

> A type that implements `ByteToMessageDecoder` must implement two methods: `decode` and `decodeLast`.

#1426 added a default implementation of `decodeLast` that calls `decode`. This documentation needs to be updated appropriately.

**Comment by Lukasa** [comment]
Yup, seems right. Would you like to make a patch to amend that?

**Comment by mlilback** [comment]
I started to, but was unsure of how to do it (as a trained copy editor, I'm a perfectionist). Less than 10 hours with nio, after almost 30 years of using blocking sockets, makes me hesitant. I was stumbling around for most of that until I switched to reading Netty documentation/example. I do plan on contributing doc and bug fixes once I have a handle on everything.
 Just not yet.

**Comment by Lukasa** [comment]
So I think the documentation alone is wrong. This means we can simply amend the documentation comment. It lives here: https://github.com/apple/swift-nio/blob/8ea391a77d62953c6cbb56b94717b144b62edec8/Sources/NIO/Codec.swift#L63

I think at this stage the change can simply be to say "may implement two methods: `decode` and `decodeLast`. Implementations _must_ implement `decode`: if they do not implement `decodeLast`, a default implementation will be used that simply calls `decode`."
