### ISSUE TITLE
How to use SwiftNIO to parse multiple files uploaded from html?

### ISSUE THREAD

**Issue by Jinxiansen** [apple/swift-nio#1724]
Hello! This is my HTML sample code:
```
<form action="/upload" method="POST" enctype="multipart/form-data">
     <input type="file" id="filename" name="file" onchange="onchanged()" multiple="multiple" />
     <input type="submit" value="Upload">
</form>
```

I want to use SwiftNIO as the server, add a post method **/upload** API to receive files uploaded from html, but the current received is a **ByteBuffer or Data** data, the size of the data data is multiple files I uploaded The sum of the sizes; I want to read Data and store it according to the name, but I did not find how to parse this Data in sections to distinguish the data Range of different files.

Is there such a sample code for reference?

> English is not my native language; please excuse typing errors.

**Comment by weissi** [comment]
Thanks for your question! SwiftNIO does not provide functionality like this itself. SwiftNIO does support HTTP but it only supports the HTTP wire protocol and seems like you're looking for a fully fledged web framework (with support for APIs, routing, uploads, ...). We would recommend you pick one of the Swift web frameworks that are implemented using SwiftNIO. For example [Vapor](https://github.com/vapor/vapor) or [Amazon Smoke](https://github.com/amzn/smoke-framework) but there are other options too.

**Comment by Jinxiansen** [comment]
@weissi 
Thank you very much. You are right, but Vapor framework is too heavy for my needs, I will refer to its code.

**Comment by weissi** [comment]
@Jinxiansen I see. You could also try more lightweight frameworks like https://github.com/Macro-swift/MacroExpress ?

**Comment by weissi** [comment]
CC @helje5 the author of MacroExpress

**Comment by helje5** [comment]
Hi. MacroExpress has bodyParser implementations for text, url-form-encoded and json, but I don't do multipart/form-data yet. That's primarily because I didn't need it yet, I might just add at least a basic implementation in the next few days :-)

**Comment by Jinxiansen** [comment]
@helje5 @weissi 

Great! Very happy to meet you here!👏  I have seen MacroExpress a few days ago, but it cannot meet my needs.

```html
<form action="/upload" method="POST" enctype="multipart/form-data">
     <input type="file" id="filename" name="file" onchange="onchanged()" multiple="multiple" />
     <input type="submit" value="Upload">
</form>
```

Because I want to use the above code to select multiple files of any type in `html`, and then call the `/upload` interface to save multiple files to the specified directory.

I saw a method like ```app.on(.POST, "upload", body: .stream) { req in ... }``` in **Vapor**, although it can transfer large file data streams after multiple selections, such as a.png(1.0MB) and b.avi(5.0 MB), the data size after I received it was 6.0MB; but I couldn't distinguish the received file fragment and file name/type; this made me a little bit distressed; I look forward to your ways to do it. 🍦🍦
