### ISSUE TITLE
WebSocket continuation (Fragmentation)

### ISSUE THREAD

**Issue by dnadoba** [apple/swift-nio#1811]
Hi everyone,

Does SwiftNIO include something similar to [`WebSocketFrameAggregator`](https://github.com/netty/netty/blob/e5951d46fc89db507ba7d2968d2ede26378f0b04/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketFrameAggregator.java) from Netty?
It buffers incoming WebSocketFrames with the continuation opcode.

I didn't found anything in the swift-nio repository.
[Vapor has implemented buffering to handle the continuation opcode](https://github.com/vapor/websocket-kit/blob/bc3c30d6bb7a970b36ae933646750c4cc6109356/Sources/WebSocketKit/WebSocket.swift#L226-L234), but does not enforce a maximum buffer size.

Thanks
David

**Comment by Lukasa** [comment]
Nope, SwiftNIO does not provide such a thing. If you wanted to implement it we'd be more than happy to accept the patch.

**Comment by dnadoba** [comment]
Thank you for your quick response! I will implement it and open a PR.
