### ISSUE TITLE
Darwin: switch lock implementation to os_unfair_lock

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1828]
`pthread_mutex_t` is much slower than `os_unfair_lock` on Darwin because (contrary to Linux) `pthread_mutex_t` is fair on Darwin.

We should just switch to `os_unfair_lock` for the Darwin versions where that's available.

**Comment by PeterAdams-A** [comment]
I've just seen a slack thread where it's recommend that you don't use os_unfair_lock from swift because using the `&` operator to pass in the lock is likely to copy before passing.  You need to use UnsafeMutablePointer and allocate on the heap - which is expected to be no faster than NSLock.

**Comment by Davidde94** [comment]
`os_unfair_lock` will burn CPU inside `ConditionLock`, as there's no built-in condition support like in `pthread_mutex_t`. I'll make a PR and measure perf.

**Comment by weissi** [comment]
ConditionLock should stay on pthread, just Lock should use unfair_lock

**Comment by Davidde94** [comment]
I don't follow. `ConditionLock` uses `Lock`, which you're saying should use `unfair_lock`?

**Comment by weissi** [comment]
It does today because it made the implementation easier and ConditionLock can just reach into the implementation details of Lock. For layering reasons this isn’t ideal anyway but so far there wasn’t enough of a reason to change it.

In the future, there’s no reason that ConditionLock uses Lock internally because we can use a faster underlaying mutex for Lock (but not for ConditionLock)

**Comment by weissi** [comment]
I think on Darwin `pthread_mutex_t` is now itself backed by a `os_unfair_lock` but this needs to be checked. Maybe this can be closed.

**Comment by Lukasa** [comment]
This can be closed.
