### ISSUE TITLE
No non-blocking file-open operation

### ISSUE THREAD

**Issue by helje5** [apple/swift-nio#185]
### Expected behavior

The way to open files seems to be:

   `NIO.FileHandle.init(path:)`

which is a blocking operation. That seems no good.

### Actual behavior

A non-blocking way to open a file. Maybe this belongs into `NonBlockingFileIO`.

### SwiftNIO version/commit hash

The HEAD when I pressed "Submit".

**Comment by Lukasa** [comment]
Yup, we should extend the `NonBlockingFileIO` struct to add support for this.

**Comment by Lukasa** [comment]
Resolved by #256.
