### ISSUE TITLE
Rename `BlockingIOThreadPool` to `ThreadPool`?

### ISSUE THREAD

**Issue by helje5** [apple/swift-nio#186]
There doesn't seem to be anything specific to blocking I/O in this and I don't want to create yet another thread pool for other synchronous operations, but just reuse this.

**Comment by Lukasa** [comment]
Yeah, we should definitely consider it. My hesitation comes from the fact that the threadpool was originally built for the non-blocking file I/O, and we made it `public` primarily to avoid restricting people too badly. But it's not necessarily a good replacement for a generalised thread pool executor: for example, it isn't capable of doing any kind of dynamic scaling of parallelism.

In general if you're not doing asynchronous file I/O, I'd probably recommend using Dispatch directly. The best reason to use this thread pool is if you've got one already for some other reason, at which point you can save yourself some resources by using the threads we already established.

We will probably never make this thread pool any more capable than it is right now: Dispatch is the best answer for most uses.

**Comment by weissi** [comment]
@Lukasa should we just do this?

**Comment by Lukasa** [comment]
`NIOThreadPool` probably, but sure.

**Comment by weissi** [comment]
oh yes, that's good. +1 on `NIOThreadPool`
