### ISSUE TITLE
Use of unresolved identifier 'SO_TIMESTAMP'

### ISSUE THREAD

**Issue by picnicbob** [apple/swift-nio#1861]
I'm attempting to recompile a Swift package on my Raspberry Pi 4 originally built with swift-nio-ssl 2.10.0 and now I'm getting multiple errors along the lines of:

.../.build/checkouts/swift-nio/Sources/NIO/BSDSocketAPI.swift:404:43: error: use of unresolved identifier 'SO_TIMESTAMP'
            NIOBSDSocket.Option(rawValue: SO_TIMESTAMP)

### SwiftNIO version/commit hash
swift-nio-ssl.git at 2.13.1

### Swift & OS version (output of `swift --version && uname -a`)
Swift version 5.1.5 (swift-5.1.5-RELEASE)
Target: armv6-unknown-linux-gnueabihf
Linux pi4 5.10.17-v7l+ #1414 SMP Fri Apr 30 13:20:47 BST 2021 armv7l GNU/Linux

**Comment by picnicbob** [comment]
$ grep -R SO_TIMESTAMP /usr/include
/usr/include/asm-generic/socket.h:#define SO_TIMESTAMP_OLD        29
/usr/include/asm-generic/socket.h:#define SO_TIMESTAMPNS_OLD      35
/usr/include/asm-generic/socket.h:#define SO_TIMESTAMPING_OLD     37
/usr/include/asm-generic/socket.h:#define SO_TIMESTAMP_NEW        63
/usr/include/asm-generic/socket.h:#define SO_TIMESTAMPNS_NEW      64
/usr/include/asm-generic/socket.h:#define SO_TIMESTAMPING_NEW     65
/usr/include/asm-generic/socket.h:#define SO_TIMESTAMP		SO_TIMESTAMP_OLD
/usr/include/asm-generic/socket.h:#define SO_TIMESTAMPNS		SO_TIMESTAMPNS_OLD
/usr/include/asm-generic/socket.h:#define SO_TIMESTAMPING		SO_TIMESTAMPING_OLD
/usr/include/asm-generic/socket.h:#define SO_TIMESTAMP (sizeof(time_t) == sizeof(__kernel_long_t) ? SO_TIMESTAMP_OLD : SO_TIMESTAMP_NEW)
/usr/include/asm-generic/socket.h:#define SO_TIMESTAMPNS (sizeof(time_t) == sizeof(__kernel_long_t) ? SO_TIMESTAMPNS_OLD : SO_TIMESTAMPNS_NEW)
/usr/include/asm-generic/socket.h:#define SO_TIMESTAMPING (sizeof(time_t) == sizeof(__kernel_long_t) ? SO_TIMESTAMPING_OLD : SO_TIMESTAMPING_NEW)
/usr/include/asm-generic/socket.h:#define SCM_TIMESTAMP           SO_TIMESTAMP
/usr/include/asm-generic/socket.h:#define SCM_TIMESTAMPNS         SO_TIMESTAMPNS
/usr/include/asm-generic/socket.h:#define SCM_TIMESTAMPING        SO_TIMESTAMPING
/usr/include/linux/errqueue.h: *	The timestamping interfaces SO_TIMESTAMPING, MSG_TSTAMP_*
/usr/include/linux/net_tstamp.h:#include <linux/socket.h>   /* for SO_TIMESTAMPING */
/usr/include/linux/net_tstamp.h:/* SO_TIMESTAMPING gets an integer bit field comprised of these values */
/usr/include/linux/net_tstamp.h: * SO_TIMESTAMPING flags are either for recording a packet timestamp or for
/usr/include/linux/ethtool.h: * @so_timestamping: bit mask of the sum of the supported SO_TIMESTAMPING flags

**Comment by picnicbob** [comment]
I should add that there's also a matching error for a 'SO_RCVTIMEO' constant:

.../.build/checkouts/swift-nio/Sources/NIO/BSDSocketAPI.swift:381:43: error: use of unresolved identifier 'SO_RCVTIMEO'
            NIOBSDSocket.Option(rawValue: SO_RCVTIMEO)

**Comment by Lukasa** [comment]
It looks highly likely that the Glibc on Raspbian has got a `#define` that is too complex for the clang importer. We may need to thunk this through CNIOLinux to workaround this.

**Comment by picnicbob** [comment]
@Lukasa Is this likely to be fixed in the next few days? If not we might need to spin up some new hardware to get back up temporarily or try to rollback the pi to an older Debian release, neither of which I would enjoy doing unnecessarily.

**Comment by Lukasa** [comment]
Sorry, you hit a nasty time there, I had a 4-day weekend. :wink:

**Comment by picnicbob** [comment]
Yeah I'm not complaining, I was gone until today too. I just want to know so I can plan for the rest of my week.

**Comment by picnicbob** [comment]
@Lukasa The patch allowed me to compile but the NIO function calls are unusable. Calling AdaptiveRecvByteBufferAllocator() causes SIGILL: illegal instruction. I can get around that by using FixedSizeRecvByteBufferAllocator(capacity: 10240) but then the call to ServerBootstrap.bind(host:, port:).wait() has its own illegal instruction.

**Comment by Lukasa** [comment]
You appear to be running a 32-bit toolchain. We don't currently CI on 32-bit so we have an unfortunate tendency to regress. Can you file issues for the ones you hit?

**Comment by picnicbob** [comment]
Bleh, it's been everything so far. I'll just upgrade the pi to the 64-bit kernel and try again later.

**Comment by picnicbob** [comment]
@Lukasa No luck with 64-bit kernel. Still running into illegal instructions.
'$ swift --version && uname -a
Swift version 5.1.5 (swift-5.1.5-RELEASE)
Target: armv6-unknown-linux-gnueabihf
Linux pi4 5.10.17-v8+ #1421 SMP PREEMPT Thu May 27 14:01:37 BST 2021 aarch64 GNU/Linux'

**Comment by Lukasa** [comment]
Ok great, can you file the issues you're hitting with the full tracebacks attached? If you're having trouble symbolicating them you can use [`swift-backtrace` to get better diagnostics](https://github.com/swift-server/swift-backtrace).
