### ISSUE TITLE
fatalError() during high concurrency test

### ISSUE THREAD

**Issue by vlm** [apple/swift-nio#187]
### Expected behavior

Users generally expect Swift NIO not to fail with internal assertions and `fatalError`s they couldn't catch.

### Actual behavior

```
Fatal error: Invalid FSM transition attempt: state complete, input connectTimeoutElapsed: file swift-nio/Sources/NIO/HappyEyeballs.swift, line 417
Illegal instruction: 4
```

### Steps to reproduce

Compile and run the attached code against the master.

### If possible, minimal yet complete reproducer code (or URL to code)

[reproduce.swift](https://github.com/apple/swift-nio/files/1823817/reproduce.swift.txt).

### SwiftNIO version/commit hash

b8d883da2c2090d02ec4890b5ab5c7c9bfa30935

### Swift & OS version (output of `swift --version && uname -a`)

```
Apple Swift version 4.1 (swiftlang-902.0.38 clang-902.0.30)
Target: x86_64-apple-darwin17.4.0
Darwin Levs-MacBook-Pro.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
```

**Comment by Lukasa** [comment]
Should be fixed by #191.
