### ISSUE TITLE
This repo no longer builds with the latest official trunk snapshots for linux: an upstream stdlib change probably broke building NIO

### ISSUE THREAD

**Issue by buttaface** [apple/swift-nio#1892]
### Expected behavior
`swift build` builds NIO.

### Actual behavior
Build fails with this error:
```
> ../src/swift-DEVELOPMENT-SNAPSHOT-2021-07-07-a-centos8/usr/bin/swift build
/home/butta/swift-nio/Sources/_NIO1APIShims/NIO1APIShims.swift:49:1: error: type 'StaticString' does not conform to protocol 'Collection'
extension StaticString: Collection {
^
/home/butta/swift-nio/Sources/_NIO1APIShims/NIO1APIShims.swift:49:1: error: unavailable subscript 'subscript(_:)' was used to satisfy a requirement of protocol 'Collection'
extension StaticString: Collection {
^
Swift.Collection:3:12: note: 'subscript(_:)' declared here
    public subscript(bounds: Range<Self.Index>) -> Self.SubSequence { get }
           ^
Swift.Collection:12:5: note: requirement 'subscript(_:)' declared here
    subscript(bounds: Range<Self.Index>) -> Self.SubSequence { get }
    ^
```
Most likely related to apple/swift#38161?
### SwiftNIO version/commit hash

latest trunk ffa6a87

### Swift & OS version (output of `swift --version && uname -a`)

That is one of the latest official trunk snapshot builds, July 7, running on Fedora Core 33. I can also reproduce with the July 6 trunk source snapshot toolchain built natively on Android AArch64, which is where I first hit this.

**Comment by Lukasa** [comment]
I think this will need a `bugs.swift.org` report. Are you open to filing one?

**Comment by buttaface** [comment]
Will do it now.

**Comment by buttaface** [comment]
Filed SR-14905.

**Comment by glessard** [comment]
This error is triggered because the type's Collection conformance relied on a bad `Range<Index>` subscript. Calling that subscript in your code would have resulted in an accidental infinite recursion [SR-14848](https://bugs.swift.org/browse/SR-14848). The best mitigation in this case is to add the now-missing subscript.

Amusingly this build failure is in a long-deprecated conformance.

**Comment by glessard** [comment]
I'm testing the following fix:
```swift
    @available(*, deprecated, message: "don't use the StaticString: Collection extension please")
    public subscript(bounds: Range<Int>) -> SubSequence {
        precondition(0 <= bounds.lowerBound &&
                     bounds.lowerBound <= bounds.upperBound &&
                     bounds.upperBound <= utf8CodeUnitCount)
        return withUTF8Buffer { return ArraySlice($0[bounds]) }
    }
```
