### ISSUE TITLE
How would you bridge the synchronous world of swift-nio with the rest of an asynchronous application in Swift 5.5?

### ISSUE THREAD

**Issue by kit-981** [apple/swift-nio#1921]
Apologies in advance because I'm fairly new to Swift and this project. I hope questions are welcome.

I've read through the [NIOAsyncAwaitDemo](https://github.com/apple/swift-nio/tree/ca136e8f807f0155c03aa89189348d3ef104f7ad/Sources/NIOAsyncAwaitDemo) example code. From what I can tell, `swift-nio` follows something of a delegate pattern where the last handler in the pipeline should call a method that consumes the data. If I'm wrong here please correct me.

Suppose I want to store all the incoming data in a buffer to be consumed later by another task. [This chapter](https://docs.swift.org/swift-book/LanguageGuide/Concurrency.html) of the Swift book recommends using an Actor when you need to synchronize access to shared mutable state like this buffer of data. Any methods on that Actor that modify the shared state are made to be asynchronous functions that can block. This means that it can't be called from the synchronous channel handler without creating a task block.

I'm not sure I like the idea of creating a task that calls the Actor method each time there's a few bytes to store. It feels like a lot of overhead and I'm not sure how to handle the case where data arrives faster than its processed. In this case I imagine the number of tasks would increase and hang the program?

Is there a common pattern here I can employ? What do most applications do? Feel free to direct me to one if you think the implementation is good.

Thanks!

**Comment by Lukasa** [comment]
Thanks for asking your question!

> I've read through the NIOAsyncAwaitDemo example code. From what I can tell, swift-nio follows something of a delegate pattern where the last handler in the pipeline should call a method that consumes the data. If I'm wrong here please correct me.

This is not necessarily true, it depends on what exactly your application is. However, in general we expect the last handler in the pipeline to do something appropriate with inbound data, yes.

> I'm not sure I like the idea of creating a task that calls the Actor method each time there's a few bytes to store. It feels like a lot of overhead and I'm not sure how to handle the case where data arrives faster than its processed.

In the first instance I think it's not that much overhead. Task creation should be fairly cheap, and as it's certainly the simplest thing to do I'd recommend trying that first and measuring its performance impact. If your service performs well, no problem! If not, then you have some data you can use to dig in and investigate where your performance problems are. (This is more general performance advice: when you're unsure of the performance impact of something, it's much better to try it out and then load test it under instrumentation than to try to hypothesise about the best performance story.)

> In this case I imagine the number of tasks would increase and hang the program?

You can have a _lot_ of tasks before you hang the program!

> Is there a common pattern here I can employ? What do most applications do?

In the case of using actors, the most common pattern is to do roughly this, but make a few minor optimisations. The first, and easiest, optimisation is to buffer in your `ChannelHandler` until `channelReadComplete` is called, and then use that as your signal to deliver the buffer. That message is a signal from NIO that says we aren't doing any more I/O on that `Channel` for a little bit, and so you can safely do anything that's a little more expensive. You can then deliver all your bytes in one go over to the actor.

The other, further optimisation is to use a locked buffer. This is dangerous territory, as you need to manage the locking yourself, but in general this lock will be cheaper than the Task, though note that if your actor is consuming data faster than it comes from the network then the performance will degenerate to the Task case anyway. However, this can be a nice win in cases where the network code is faster than the async/await code.

**Comment by kit-981** [comment]
That makes sense. Thank you so much for the detailed response!
