### ISSUE TITLE
Broken links on README.md

### ISSUE THREAD

**Issue by ldewailly** [apple/swift-nio#1986]
### Expected behavior

Clicking on say `EventLoopFuture` in https://github.com/apple/swift-nio#basic-architecture should take me to the documentation for it.

### Actual behavior

404

### Steps to reproduce

Click on any links related to NIO's types 

### If possible, minimal yet complete reproducer code (or URL to code)

n/a

### SwiftNIO version/commit hash

HEAD

### Swift & OS version (output of `swift --version && uname -a`)

n/a

**Comment by Lukasa** [comment]
This is a dupe of #1983.
