### ISSUE TITLE
Event loop for synchronisation?

### ISSUE THREAD

**Issue by lmcd** [apple/swift-nio#1989]
I have a situation in which multiple event loops are serving requests, but the requests are sharing a resource in memory.
At the moment I'm controlling access to this resource with a `Lock`. The two requests sharing this resource are highly trafficked streaming requests, and the lock alone is resulting in a 4% CPU penalty.

I've figured out that instead of locking in 4 different places, I can instead achieve the same synchronisation by eliminating three of these calls, and wrap the remaining one in an `eventLoop.submit(_:)`.

My question is: is there a significant performance penalty to forcing something to run on an event loop?

**Comment by Lukasa** [comment]
Yes. Forcing something to run on an event loop is strictly more expensive than acquiring a lock. How expensive is the operation within the lock?

**Comment by lmcd** [comment]
Got it, I thought that might be the case.

Nothing expensive at all, just controlling access to a few properties to avoid races.
I think it might be a trade off though, as the most heavily trafficked parts are the locks that would be eliminated in this case, and less frequent path could be made to wait for an event loop pass.

**Comment by lmcd** [comment]
Actually, I misinterpreted the profiling data here. The lock was actually occurring further up the chain in `NonBlockingFileIO`, and not in my own code.
