### ISSUE TITLE
consider adding a new suite of functions named `EventLoopFuture.flatMapWithEventLoop` or so

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1996]
Sometimes in NIO programs you're stuck in this situation:

```swift
doSomething().flatMap { result in
    guard iLikeTheShape(of: result) else {
        struct IDontLikeIt: Error {}
        //     vvvvvvvvv---- where do I get that from?
        return eventLoop.makeFailedFuture(IDontLikeIt())
    }
    return doMore()
}
```

that's all okay, but where do we get `eventLoop` from? In many cases, it's passed in but that's not always the case, I would like a suite of new functions (everything that allows to return `-> EventLoopFuture<...>`) which are named like the existing ones with an additional `WithEventLoop` at the end. Such that I can write

```swift
doSomething().flatMapWithEventLoop { result, eventLoop /* <- thank you */ in
    guard iLikeTheShape(of: result) else {
        struct IDontLikeIt: Error {}
        return eventLoop.makeFailedFuture(IDontLikeIt())
    }
    return doMore()
}
```

The implementation would be trivial:

```swift
extension EventLoopFuture {
    @inlinable
    public func flatMapWithEventLoop<NewValue>(file: StaticString = #file, line: UInt = #line, _ callback: @escaping (Value, EventLoop) -> EventLoopFuture<NewValue>) -> EventLoopFuture<NewValue> {
        let eventLoop = self.eventLoop
        return self.flatMap(file: file, line: line) {
            callback($0, eventLoop)
        }
}
```

**Comment by Lukasa** [comment]
Sounds reasonable to me.

**Comment by fabianfett** [comment]
Good first starter issue?

**Comment by Lukasa** [comment]
Yup.

**Comment by dnadoba** [comment]
I think it would be even more convenient if we had a version of `flatMap` which allows the closure to throw. `Combine` prefixes those methods with `try` e.g. `tryMap`. 
We could also add a similar function for `flatMap`:
```swift
extension EventLoopFuture {
    public func tryFlatMap<NewValue>(
        transform: @escaping (Value) throws -> EventLoopFuture<NewValue>
    ) -> EventLoopFuture<NewValue>
}
```
which could be used like this:
```swift
doSomething().tryFlatMap { result in
    guard iLikeTheShape(of: result) else {
        struct IDontLikeIt: Error {}
        throw IDontLikeIt()
    }
    return doMore()
}
```
This would remove the need for the `eventLoop` entirely.

Note: We already have a method called `flatMapThrowing` which behaves more like a `tryMap`, IMHO.

**Comment by fabianfett** [comment]
@dnadoba I'm not sure this would be a valuable addition, since it mixes synchronous and asynchronous patterns for adopters. It would be really hard to explain to users, why this program would crash:

```swift
doSomething().tryFlatMap { result in
    guard iLikeTheShape(of: result) else {
        struct IDontLikeIt: Error {}
        throw IDontLikeIt()
    }

    let result1 = try httpClient.get("https://foo.org").wait()
    let result2 = try httpClient.get("https://foo.org").wait()

    return doMore(with: result1, result2)
}
```

If you are required to return a future and can not throw, people are less likely to wait in a flatMap.

Of course people can also await in today's `flatMap`. But I think the very clear divide in a sync and an async callback is vital for users to understand the fundamentals, of waiting for another event.

Lastly, the addition you mention above would mean at least two internal promises with kind of weird semantics. The first promise would only be created to catch the thrown error or void if the user actually returns a future. If the user returns a future we have created a void promise just in case.

The issue you illustrate above can be accomplished by a `throwingMap`:

```swift
doSomething().flatMapThrowing { result in
    guard iLikeTheShape(of: result) else {
        struct IDontLikeIt: Error {}
        throw IDontLikeIt()
    }
    return result
}.flatMap { checkedResult in
    return doMore()
}
```

**Comment by glbrntt** [comment]
> ... I would like a suite of new functions (everything that allows to return `-> EventLoopFuture<...>`) which are named like the existing ones with an additional `WithEventLoop` at the end.

I'm not sure if this adds enough value to justify adding a new variant of _every function that returns an ELF_: that's quite a lot of new API!

---

I appreciate the problem though, I've hit this a few times and usually end up just grabbing the event loop from `doSomething()` which is a little cumbersome.

```swift
let f = doSomething()
let eventLoop = f.eventLoop
return f.flatMap { result in
    guard iLikeTheShape(of: result) else {
        struct IDontLikeIt: Error {}
        return eventLoop.makeFailedFuture(IDontLikeIt())
    }
    return doMore()
}
```

The other concern I have is that I'm not sure that the average user would run into the problem and think 'ah yes, I need an event loop to return a failed future here'. 

I wonder if there's space for an API to filter values like we have for `unwrap`:

```swift
public func filter(orError: Error, isIncluded: @escaping (Value) -> Bool) -> EventLoopFuture<Value> {
  // ...
}
```

Of course this incurs an extra allocation which is unfortunate. We could supplement this with something that provides either the future or the future and its event loop to a closure:

```swift
extension EventLoopFuture {
  @inlinable
  public func withSelf<NewValue>(_ transform: (EventLoopFuture<Value>) -> EventLoopFuture<NewValue>) -> EventLoopFuture<NewValue> {
    return transform(self)
  }
}

doSomething().withSelf { 
  let eventLoop = $0.eventLoop
  return $0.flatMap {
    guard iLikeTheShape(of: result) else {
        struct IDontLikeIt: Error {}
        return eventLoop.makeFailedFuture(IDontLikeIt())
    }
    return doMore()
  }
}
```

This is a bit of an awkward API but it would be just one addition as opposed to a suite of additions.

**Comment by glbrntt** [comment]
@weissi points out this would only actually be three additions, which is totally fine.

**Comment by weissi** [comment]
> > ... I would like a suite of new functions (everything that allows to return `-> EventLoopFuture<...>`) which are named like the existing ones with an additional `WithEventLoop` at the end.
> 
> I'm not sure if this adds enough value to justify adding a new variant of _every function that returns an ELF_: that's quite a lot of new API!

It's every function that has a callback that returns an ELF only. So only `func foo(_ body: @escaping (...) -> EventLoopFuture<...>) -> EventLoopFuture<...>`. We're talking about 3 new functions if I counted correctly.

> I appreciate the problem though, I've hit this a few times and usually end up just grabbing the event loop from `doSomething()` which is a little cumbersome.

Yes, but users will reach for `group.next().makeXYZ()` which is much worse but easier to reach.

> The other concern I have is that I'm not sure that the average user would run into the problem and think 'ah yes, I need an event loop to return a failed future here'.

Very hard disagree. In the product I work on, there are _literally_ hundreds of lines which contain `roup.next().make(Succeeded|Failed)Future`.

> [...]
> This is a bit of an awkward API but it would be just one addition as opposed to a suite of additions.

One could also argue that we messed up the existing ones. How are you supposed to generate a future if you can't without an `EventLoop`?
