### ISSUE TITLE
ChannelInvoker.newPromise should pass file and line to eventLoop.newPromise

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio#202]
We normally want debugging information to keep track of where our promises are allocated in debug modes. However, if someone does `Channel.newPromise` instead of `eventLoop.newPromise`, that information is lost. The core issue is here: https://github.com/apple/swift-nio/blob/fef728cab0cdb65459e3028d7ab7ffece0f34f6f/Sources/NIO/ChannelInvoker.swift#L182-L184

This indirection should preserve the #file and #line specific debugging logic we use elsewhere.

**Comment by tib** [comment]
Hey guys, I think I've fixed this with my [PR](https://github.com/apple/swift-nio/pull/208).
