### ISSUE TITLE
Problem: swift-server-bot

### ISSUE THREAD

**Issue by bobychaudhary** [apple/swift-nio#2025]
# swift-server-bot sending same message 12 times 🙄

![Screenshot (60)](https://user-images.githubusercontent.com/73424060/147866284-3be90dd5-e69e-4286-ad48-45e91e3d9b02.png)

**Comment by Lukasa** [comment]
Yup, we know. It only happens the first time on a PR, so it’s low urgency, but if @tomerd wanted to fix it we wouldn’t mind.
