### ISSUE TITLE
Split basic HTTP types into separate package

### ISSUE THREAD

**Issue by tkrajacic** [apple/swift-nio#2028]
Types like `HTTPMethod`, `HTTPHeaders`, etc. are very useful in contexts outside NIO. 

Libraries like Alamofire, that are primarily used on clients do not import NIO, and have their own copy of implementation for those types ([HTTPHeaders](https://github.com/Alamofire/Alamofire/blob/master/Source/HTTPHeaders.swift), [HTTPMethod](https://github.com/Alamofire/Alamofire/blob/master/Source/HTTPMethod.swift), [HTTPResponseStatus](https://github.com/stairtree/StructuredAPIClient/blob/main/Sources/StructuredAPIClient/HTTP/HTTPStatusCode.swift)) that are mostly copies of the same.

It would be convenient to split out those types from NIO (I created a blunt sample repo [here](https://github.com/tkrajacic/http-support)) so packages that are used in client contexts without NIO, and server code where NIO is usually imported anyway, could rely on the same types.

Especially now that NIO 3.0 might be on the horizon, this would be the right time for such a change.

**Comment by Strobocop** [comment]
Currently facing this exact issue in our codebase.

**Comment by stevapple** [comment]
I thought this package is related👀 But not sure how we should deal with it. I guess no SSWG project is using it at the time.

[apple/swift-http-structured-headers](https://github.com/apple/swift-http-structured-headers)

**Comment by Lukasa** [comment]
Thanks for filing this!

Ultimately, the types that exist in NIO HTTP1 are purpose-built for our use-case. They exist to facilitate rapid encode/decode from our currency types and to provide a low-level NIO-focused API. 

Currency types for expressing HTTP would not look like ours. They’d have different trade offs in their representation and API, perhaps preferring to maximally flatten or expand list headers as an example. While this is a worthy effort, simply extracting NIO’s types will not do a good job of achieving this goal.
