### ISSUE TITLE
Flaky test: EventLoopTest.testRepeatedTaskThatIsCancelledAfterRunningAtLeastTwiceNotifies

### ISSUE THREAD

**Issue by buttaface** [apple/swift-nio#2053]
### Expected behavior
It should pass every time.

### Actual behavior
It [failed](https://github.com/buttaface/swift-android-sdk/runs/5300969936?check_suite_focus=true#step:3:3062) 3 [out of](https://github.com/buttaface/swift-android-sdk/runs/5271676891?check_suite_focus=true#step:3:3072) the [last](https://github.com/buttaface/swift-android-sdk/runs/5263684710?check_suite_focus=true#step:3:3068) 21 times I ran it in the last week in an Android x86_64 emulator on macOS 11 for [my daily Android CI that runs on github actions](https://github.com/buttaface/swift-android-sdk/actions). That CI cross-compiles the 5.5.3 and latest 5.6 and trunk snapshots of the stdlib and corelibs for Android x86_64 from Ubuntu 20.04, cross-compiles NIO and its tests against that Android SDK, then runs the tests serially in the official Android emulator, which runs at close to native speed on macOS 11 x86_64. This test has been flaky for a long time, just reporting it now.

Two of this week's failures were with a trunk SDK, the other with 5.5.3, so it doesn't depend on the Swift version, all the same error:
```
swift-nio/Tests/NIOPosixTests/EventLoopTest.swift:772:
error: EventLoopTest.testRepeatedTaskThatIsCancelledAfterRunningAtLeastTwiceNotifies :
XCTAssertEqual failed: ("timedOut") is not equal to ("completed") - 
```
I cannot reproduce on Android AArch64 running on my phone, implying this is either specific to Android x86_64 or resource constraints in the emulator, more likely the latter.

### Steps to reproduce

1. Follow [the instructions for my Android SDKs](https://github.com/buttaface/swift-android-sdk/#swift-cross-compilation-sdks-for-android), building and testing for Android x86_64 instead.

An easier way may be to try to reproduce on a small linux x86_64 VPS.

### SwiftNIO version/commit hash

latest trunk commit on every day the CI ran, currently d489d9f

### System & version information

Building on Ubuntu 20.04 x86_64 and running on Android x86_64 at API 24

@gwynne, [you added this test three years back](https://github.com/apple/swift-nio/pull/783/files#diff-9e84892fe707b6079ac2981fba2b834a1b2a4e027aacd1f1b7d64eda1f9867a7R598), maybe you know what to do.

**Comment by Lukasa** [comment]
The expectation that is awaited on line 772 has an _extremely_ tight deadline:

https://github.com/apple/swift-nio/blob/d489d9f38f9bea8da3252d42632b18244b137a14/Tests/NIOPosixTests/EventLoopTest.swift#L769-L772

We expect two runs, with 10ms in between, to occur. We wait 0.05s (50ms) for that to happen before we time out. It's totally possible for a machine that is running with limited resources to fail to meet this target. The fact that you're not successfully reproducing this elsewhere suggests that a useful first step may be to just double the amount of time we're willing to wait to 100ms and see if that resolves the issue.

**Comment by buttaface** [comment]
I'll patch the test on my Android CI as you suggest, and report back next week with the results.

**Comment by Lukasa** [comment]
Shiny, I really appreciate that! :pray:

**Comment by buttaface** [comment]
I think you can go ahead and merge your fix: I've now run the NIO tests 23 times on the Android CI with it, buttaface/swift-android-sdk@1c5f71b, without this test flaking once (should have run more but [an unrelated trunk stdlib bug caused problems](https://bugs.swift.org/browse/SR-15912) running the NIO tests against the trunk toolchain, until I pulled in the upstream patches to my CI).
