### ISSUE TITLE
work around SR-7242

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#206]
Swift does a pretty terrible job with global constants that are C functions unless they're annotated `@convention(c) ...`. This is filed as [SR-7242](https://bugs.swift.org/browse/SR-7242) and will hopefully be fixed soon however we should probably work around as it's very simple.

This is quite a straightforward fix, just all instances of `let sysSomething = something` need to be changed to `let sysSomething: @convention(c) (SomethingParam1, SomethingParam2, ...) -> SomethingReturn = something`. For example `let sysWrite = write` needs to become `let sysWrite: @convention(c) (CInt, UnsafeRawPointer?, size_t) -> ssize_t = write` (or very similar).

**Comment by normanmaurer** [comment]
@weissi oh my... thanks for reporting it.
