### ISSUE TITLE
announcement that NIO 1.x will not receive security updates anymore

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#2081]
As of 1 May 2022, NIO 1.x will _not_ receive security updates anymore should there be a vulnerability.

More than 3 years after its de-facto deprecation with the release of NIO 2.0.0 I think this is more than reasonable. This should however be communicated to the community, at the very least through the Swift Forums and probably via Twitter too.

Oh, and big NIO 1.x users like Vapor 3 (which uses NIO 1.x in Vapor's 3.x versions) should also be notified so they can notify their users.

**Comment by weissi** [comment]
CC @gwynne / @0xTim

**Comment by Lukasa** [comment]
This is a good idea.

**Comment by 0xTim** [comment]
Vapor 3 has been EOL for a while now so this shouldn't be an issue. Would be good to add a post on the forums announcing the above though to make sure people are aware

**Comment by weissi** [comment]
@Lukasa / @glbrntt WDYT, I think we should pull the trigger on this.

**Comment by weissi** [comment]
@Lukasa I thought this has been done?
