### ISSUE TITLE
agree on `EventLoop{Future,Promise}<Void>` vs `EventLoop{Future,Promise}<()>`

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#211]
In our code base we use both `EventLoop{Future,Promise}<Void>` and `EventLoop{Future,Promise}<()>`. We should probably be consistent but we need to decide what we want first :).

**Comment by weissi** [comment]
@weissi's personal opinion: should be `()` because we succeed the promise with the type `()`'s only value `()`. I know `Void` is equivalent to `()` so it's not a strong feeling but got to have an opinion, right ;)?

**Comment by normanmaurer** [comment]
@airspeedswift is there a preference ?

**Comment by airspeedswift** [comment]
I think our style is to prefer `<Void>`. We use that form in a couple of places in the documentation. But I don't think we have a hard rule – the only one of those we have is that it's `()->Void`, not `Void->Void` or `()->()`.

**Comment by normanmaurer** [comment]
@weissi are you ok with doing the same in our code-base ? if so I will do a pr....

**Comment by weissi** [comment]
@normanmaurer sure. You _could_ also leave that as a starter bug if you wanted.

**Comment by weissi** [comment]
but I'm totally fine with the change

**Comment by normanmaurer** [comment]
@weissi sounds good... I marked it as such but may just do it if I have a few cycles if no-one else does it first.

**Comment by tib** [comment]
@normanmaurer I've made the required changes, please check PR. Thanks.
