### ISSUE TITLE
rename `then` -> `flatMap`

### ISSUE THREAD

**Issue by tanner0101** [apple/swift-nio#213]
Swift's standard library makes extensive use of the map/flatMap pattern for working with generics. The basic concept behind this pattern is preventing generics from becoming nested (i.e., keeping them "flat"). 

The concept of map/flatMap can be represented abstractly like so:

|before|signature|after|
|-|-|-|
|`T<U>`|`map(_: U -> V)`|`T<V>`|
|`T<U>`|`flatMap(_: U -> T<V>)`|`T<V>`|

`map` is used to change the generic's wrapped type to another type. `flatMap` is used to change the generic's wrapped type to the wrapped type of _another_ instance of the generic type.

There was some misconception surrounding `flatMap` and the old method on array that would remove optional elements. This was fixed by [SE-0187](https://github.com/apple/swift-evolution/blob/master/proposals/0187-introduce-filtermap.md), replacing the incorrectly labelled `flatMap` with `compactMap`. I believe that is a strong signal from the Swift team that map/flatMap is a more abstract concept for working with (and not nesting) generics, and not just a term associated with optionals.

If you look at NIO's `.map` method, the signature directly corresponds to usages of map in the standard library. 👍 

```swift
extension EventLoopFuture {
    func map<U>(_ callback: (T) -> U) -> EventLoopFuture<U>
}

/// identical to...

extension T {
    func map<V>(_ callback: (U) -> V) -> T<V>
}

/// identical to...

extension Optional {
    func map<U>(_ transform: (Wrapped) throws -> U) rethrows -> U?
}

/// identical to...

extension Array {
    func map<T>(_ transform: (Element) throws -> T) rethrows -> [T]
}
```

If you look at NIO's `.then` method, the signature matches what is called `.flatMap` in other places.

```swift
extension EventLoopFuture {
    func then<U>(_ callback: (T) -> EventLoopFuture<U>) -> EventLoopFuture<U>
}

/// signature matches...

extension T {
    func flatMap<V>(_ callback: (U) -> T<V>)) -> T<V>
}

/// signature matches...

extension Optional {
    func flatMap<U>(_ transform: (Wrapped) throws -> U?) rethrows -> U?
}

/// signature matches...

extension Array {
    func flatMap<U>(_ transform: (Element) throws -> [U]) rethrows -> [U]
}
```

I think all uses of `.then` in NIO should be renamed (with deprecation fix-its) to `flatMap` to further enforce this pattern and make NIO fit in better with the Swift standard library.

**Comment by tanner0101** [comment]
@normanmaurer yeah, definitely. :)

**Comment by helje5** [comment]
I don't particularly care, but to me this feels wrong for two reasons:

a) flatMap just does a flatMap function on some entity. It is pure functional and there is no timing aspect to it. `then` attaches an event handler to the future, which may *or may not* be called. In other words, the `then`/timing aspect is the focus of the call, not the mapping aspect.

b) `then` is not always called, there can be multiple thens, and error thens, etc. This doesn't map to any 
of the functional stuff.

But maybe `asyncFlatMap` or something? I would just keep `then` to be honest :-)

**Comment by airspeedswift** [comment]
> `then` attaches an event handler to the future, which may or may not be called.

Same goes for the other cases. The function you pass to `Optional.flatMap` may or may not be called depending on whether the value is `nil`. The difference is when it is called, not if it is.

**Comment by tanner0101** [comment]
@helje5 by your argument `.map` should be renamed to something else then because it also has an async nature to it.

**Comment by airspeedswift** [comment]
I am a bit conflicted. Consistency is good, but so is clarity. There isn't a clearly better name for `Optional.flatMap` (only bad verbose alternatives like `mapAndUnwrap`). `then` OTOH is a pretty nice name for what this particular method does.

**Comment by John-Connolly** [comment]
I prefer flatmap, I think its consistent with other monadic types that are commonly used in swift. The result type [https://github.com/antitypical/Result](url) also uses this naming.

**Comment by helje5** [comment]
> @helje5 by your argument .map should be renamed to something else then because it also has an async nature to it.

I think I agree with this. As mentioned not only because it is async (the significance being on the temporal part), but also because you can attach multiple handlers in a non-functional way.

Guesswork: Presumably `map` is only not-named `then` because otherwise you would end up having to type the return values explicitly? (to disambiguate)

Two other suggestions which come to mind: `thenMap` and `thenFlatMap`? (but what about the error cases, thenMapIfError? - all this looks just wrong to me).
Or maybe something similar to `lazy`: `async.map` and `async.flatMap`. But again, what about the error cases? Or redo them to be actually functional and get passed a Result or Error/T?

As mentioned I don't particularly care, but it seems pretty weird to me to map functional conventions on something which is not composed in a functional way.

**Comment by Lukasa** [comment]
> Guesswork: Presumably `map` is only not-named then because otherwise you would end up having to type the return values explicitly?

This is historically true for our implementation: we split `then` up into two largely in order to help the Swift compiler do the right thing with type inference.

---

So I'm basically -0 on this. I don't care very much, and I buy the arguments in favour of changing. However, I also think that the name change is basically a bikeshed: the `.then` name is not a source of confusion, and the value of changing it to `flatMap` is probably less than the work required to get everyone to change `.then` to `.flatMap`.

But if everyone else wants to change it I certainly won't kick up a fuss.

**Comment by weissi** [comment]
Couldn’t have commented better than @airspeedswift . Why could have both `then` and `flatMap`? I don’t think deprecating `then` is a good call right now as it’s everywhere and `then` arguably sounds nicer.
Once Swift gains higher kinded types, we should obviously follow what the `Applicative`/`Monad` or whatever they’ll be called protocol mandate. But I don’t think there’s anything from with having the nicer name `then`

**Comment by helje5** [comment]
But what about the reverse thing. Should `map` be called differently? Maybe `now`? 🤪

**Comment by tomerd** [comment]
cc @scottmitch @niteshkant

**Comment by vlm** [comment]
Having both `.then` and `.flatMap` is a source of confusion. Even having `.map` and `.flatMap` is a source of confusion, and you'll have a fun time explaining all that in the documentation. I prefer `map`+`then`.

**Comment by gps** [comment]
FWIW, [Ratpack](https://ratpack.io) has both [then](https://ratpack.io/manual/current/api/ratpack/exec/Promise.html#then-ratpack.func.Action-), and [flatMap](https://ratpack.io/manual/current/api/ratpack/exec/Promise.html#flatMap-ratpack.func.Function-), but they do different things. They also have [flatLeft](https://ratpack.io/manual/current/api/ratpack/exec/Promise.html#flatLeft-ratpack.func.Function-), [flatRight](https://ratpack.io/manual/current/api/ratpack/exec/Promise.html#flatLeft-ratpack.func.Function-), etc. which I find quite useful.

IMO, something else worth considering is a problem that arises from having `then` do more than one thing. This is something that plagued PromiseKit, IMO. From http://promisekit.org/news/2018/02/PromiseKit-6.0-Released/:

> With PromiseKit our then did multiple things, and we relied on Swift to infer the correct then from context. However with multiple line thens it would fail to do this, and instead of telling you that the situation was ambiguous it would invent some other error. Often the dreaded cannot convert T to AnyPromise. We have a troubleshooting guide to combat this but I believe in tools that just work, and when you spend 4 years waiting for Swift to fix the issue and Swift doesn’t fix the issue, what do you do? We chose to find a solution at the higher level.

**Comment by Lukasa** [comment]
Right now `then` only does one thing, and I don't think there's any plan to move to only having `then`. We pulled `then` and `map` apart for good reason. :smile:

**Comment by helje5** [comment]
But don’t you think that `map` is a little confusing wrt the original question? Specifically considering that it really is a `then` and just named differently to pleaze the compiler?

(I‘m not really suggesting we should rename it, but maybe it is worth a consideration to create consistency „the other way around“ as originally proposed)

**Comment by Lukasa** [comment]
I think `map` is a fine name, tbh. It doesn't have an asynchronous property, nor does it claim to: it takes a concrete value and maps it to a new concrete value.

**Comment by airspeedswift** [comment]
FWIW, it's very likely the swift std lib will get a future at some point, which will get bikeshod on evolution. Renaming stuff now is probably tempting fate for the new name to conflict with whatever the std lib implementation ends up being.

**Comment by tanner0101** [comment]
I'm OK sticking with `then` if it seems everyone likes that name. It's less inconsistent with the rest of stdlib, but more consistent with other promise implementations which may be more important. 

I do agree that we should definitely not add any overloads to `then`. Swift's type system already has a hard enough time inferring the return type as is. 

I'm fine closing this. :)
