### ISSUE TITLE
Enable Documentation building on the Swift Package Index

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#2160]
Swift Package Index just launched the awesome feature which [generates docs](https://blog.swiftpackageindex.com/posts/auto-generating-auto-hosting-and-auto-updating-docc-documentation) for any package. SwiftNIO should enable this by adding the required `.spm.yml` etc.

**Comment by glbrntt** [comment]
This was done in https://github.com/apple/swift-nio/pull/2324
