### ISSUE TITLE
task done error: missing required module 'CNIOAtomics'

### ISSUE THREAD

**Issue by bimawa** [apple/swift-nio#2222]
### Expected behavior
I have dependency GRPC-Swift with my Protofiles. And want to include my dependency to host app like a framework. 

### Actual behavior
Host App receive the error in compilation time: 

![CleanShot 2022-07-06 at 22 41 04](https://user-images.githubusercontent.com/1393809/177610976-d8b147be-5bca-4aec-b87f-fe39ec503f81.png)

### Steps to reproduce

1. Create #one project with protofiles and describe depencency GRPC-Swift
2. Create #second one and set target dependency on project #one
3. Wait until SPM resolved all dependency

### If possible, minimal yet complete reproducer code (or URL to code)
My example how I described the manifest Project.swift

![CleanShot 2022-07-06 at 22 34 01@2x](https://user-images.githubusercontent.com/1393809/177609892-e3dfc06e-afd2-4167-b956-9e95294bd555.png)

### SwiftNIO version/commit hash

 "2.36.0"

### System & version information

xcode13.4

Also related issue: https://github.com/grpc/grpc-swift/issues/683

**Comment by bimawa** [comment]
Host app Package.swift
```
// swift-tools-version: 5.6
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "testSLProtofiles",
    platforms: [.iOS(.v13)],
    products: [
        .library(
            name: "testSLProtofiles",
            targets: ["testSLProtofiles"]),
    ],
    dependencies: [
        .package(url: "git@github.com:*****SLProtofiles.git", from: "0.0.6"),
    ],
    targets: [
        .target(
            name: "testSLProtofiles",
            dependencies: [
                .product(name: "SLProtofiles", package: "SLProtofiles"),
                .target(name: "SLProtofiles"),
            ]),
    ]
)
```

**Comment by Lukasa** [comment]
SwiftNIO does not define a binary stable ABI and must not be compiled with library evolution mode enabled. Please import it using `@implementationOnly` if you intend to compile it into a static binary.

**Comment by Lukasa** [comment]
It would need to be done everywhere. However, grpc-swift itself doesn't support doing this with its dependencies because they are exposed as part of its public API. So normally you'd have to make grpc-swift _itself_ implementation only.
