### ISSUE TITLE
swift-nio as proxy server for iOS 15 ，springboard restart

### ISSUE THREAD

**Issue by Huyusha25** [apple/swift-nio#2252]
crash：
"build" : "iPhone OS 15.6 (19G71)",
  "product" : "iPhone12,8",
  "socId" : "0x00008030",
  "kernel" : "Darwin Kernel Version 21.6.0: Sat Jun 18 18:56:53 PDT 2022; root:xnu-8020.140.41~4\/RELEASE_ARM64_T8030",
  "crashReporterKey" : "433b355ce720957d8948b6b72d1fb143bdedb513",
  "date" : "2022-08-17 18:23:19.79 +0800",
  "panicString" : "panic(cpu 3 caller 0xfffffff023e9d120): userspace watchdog timeout: no successful checkins from SpringBoard in 180 seconds\nservice: backboardd, total successful checkins since load (3010 seconds ago): 302, last successful checkin: 0 seconds ago\nservice: SpringBoard, total successful checkins since load (3000 seconds ago): 280, last successful checkin: 180 seconds ago\nservice: mediaserverd, total successful checkins since load (3010 seconds ago): 302, last successful checkin: 0 seconds ago\nservice: logd, total successful checkins since load (3010 seconds ago): 302, last successful checkin: 0 seconds ago\nservice: thermalmonitord, total successful checkins since load (3010 seconds ago): 286, last successful checkin: 70 seconds ago\nservice: runningboardd, total successful checkins since load (3010 seconds ago): 286, last successful checkin: 100 seconds ago\nservice: wifid, total successful checkins since load (3010 seconds ago): 295, last successful checkin: 10 seconds ago\n\nDebugger message: panic\nMemory ID: 0x1\nOS release type: User\nOS version: 19G71\nKernel version: Darwin Kernel Version 21.6.0: Sat Jun 18 18:56:53 PDT 2022;

**Comment by Lukasa** [comment]
Userspace watchdog timeouts are unlikely to be related to SwiftNIO. Please file a bug report using [Feedback Assistant](https://feedbackassistant.apple.com).
