### ISSUE TITLE
IdleStateHandler's IdleStateEvent is not delivered to MyHandler. Processed by `extension _ChannelInboundHandler { }` instead.

### ISSUE THREAD

**Issue by genkernel** [apple/swift-nio#2268]
### Expected behavior
IdleStateEvent delivered to MyHandler and not to _ChannelInboundHandler's ```userInboundEventTriggered(context: , event:)```.

### Actual behavior
`IdleStateHandler` sends `IdleStateEvent` that is processed in `_ChannelInboundHandler::userInboundEventTriggered()`

### Steps to reproduce
Use example: https://github.com/apple/swift-nio/blob/main/Sources/NIOChatClient/main.swift
Register `IdleStateHandler` in addition to your MyHandler like so:
```
channel.pipeline.addHandlers(
                        [
                            IdleStateHandler(
                                readTimeout: .seconds(10),
                                writeTimeout: .seconds(10),
                                allTimeout: .seconds(30)
                            ),
                            MyHandler(),
                        ]
                    )
```
Implement `func userInboundEventTriggered(ctx: ChannelHandlerContext, event: Any)` in `MyHandler`.
Note `MyHandler::userInboundEventTriggered()` is not called when IdleStateHandler sends an event.
Event is caught by `extension _ChannelInboundHandler { }` that also implements `userInboundEventTriggered()` (noop).

### If possible, minimal yet complete reproducer code (or URL to code)
Use swiftNIO's own example from https://github.com/apple/swift-nio/blob/main/Sources/NIOChatClient/main.swift
and throw IdleStateHandler into the mix like described above.

### SwiftNIO version/commit hash
2.40.0 (pulled by XCode)

### System & version information
swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)

**Comment by genkernel** [comment]
Let me say that I don't know how IdleStateHandler is supposed to work.
It is my understanding that logical way would be to deliver emitted `IdleStateEvent` to MyHandler and not silently process it by SwiftNIO's internal `_ChannelInboundHandler ` in a noop way.
After reviewing other PRs I understand that SwiftNIO is very opinionated and so Im looking for guidance here and an answer whether IdleStateHandler is intended for public use.

**Comment by Lukasa** [comment]
Can you show me the definition of `MyHandler`, please?

**Comment by genkernel** [comment]
It is unmodified Handler from example (https://github.com/apple/swift-nio/blob/main/Sources/NIOChatClient/main.swift) with an exception of added `userInboundEventTriggered()` method.
Here is a full snippet of the handler:
```
private final class MyHandler: ChannelInboundHandler {
    public typealias InboundIn = ByteBuffer
    public typealias OutboundOut = ByteBuffer

    private func printByte(_ byte: UInt8) {
        #if os(Android)
        print(Character(UnicodeScalar(byte)),  terminator:"")
        #else
        fputc(Int32(byte), stdout)
        #endif
    }
    
    func userInboundEventTriggered(ctx: ChannelHandlerContext, event: Any) {
        fatalError() // Never invoked for me
    }

    public func channelRead(context: ChannelHandlerContext, data: NIOAny) {
        var buffer = self.unwrapInboundIn(data)
        while let byte: UInt8 = buffer.readInteger() {
            printByte(byte)
        }
    }

    public func errorCaught(context: ChannelHandlerContext, error: Error) {
        print("error: ", error)

        // As we are not really interested getting notified on success or failure we just pass nil as promise to
        // reduce allocations.
        context.close(promise: nil)
    }
}
```

and client bootstrapping is the same as in the example also with an addition of IdleStateHandler:
```
let bootstrap = ClientBootstrap(group: group)
    // Enable SO_REUSEADDR.
        .channelOption(ChannelOptions.socketOption(.so_reuseaddr), value: 1)
        .channelInitializer { channel in
            channel.pipeline.addHandlers(
                [
                    IdleStateHandler(
                        readTimeout: .seconds(10),
                        writeTimeout: .seconds(10),
                        allTimeout: .seconds(30)
                    ),
                    
                    MyHandler()
                ]
            )
        }
```

Im expecting `MyHandler::userInboundEventTriggered()` to fire after 10s interval which does not happen.

**Comment by Lukasa** [comment]
You have misspelled the signature of `userInboundEventTriggered`, which is why you aren't receiving it. Change:

```swift
func userInboundEventTriggered(ctx: ChannelHandlerContext, event: Any)
```

to 

```swift
func userInboundEventTriggered(context: ChannelHandlerContext, event: Any)
```

**Comment by genkernel** [comment]
Thanks for looking into this. Confirming that it works correctly from my side.
