### ISSUE TITLE
Guidance to implement a client with starttls

### ISSUE THREAD

**Issue by mremond** [apple/swift-nio#227]
Hello,

Do you have any tips, pointers or guidance on how to upgrade a channel to use TLS (to support starttls on a client)?

**Comment by mremond** [comment]
Thanks!

**Comment by mremond** [comment]
Hi, I have a bit more context on my need.

First of all, I am writing a client library, so I am adding a client handler:

```
let configuration = TLSConfiguration.forClient()
let sslContext = try SSLContext(configuration: configuration)
let handler = try OpenSSLClientHandler(context: sslContext)
_ = _channel.pipeline.add(handler: handler, first: true)
```

Strangely, negociation is failing, with server return error "alert unknown ca"

Second point is about iOS support. What are my option if I am writing a client library for iOS ?

Thanks !

**Comment by Lukasa** [comment]
Is the server attempting to authenticate your client? If it is, you'll need to add certificates etc. to your client TLS configuration.

For iOS support, if you are willing to support only iOS 12 or later then you can use [swift-nio-transport-services](https://github.com/apple/swift-nio-transport-services) to use Network.framework to provide your I/O. This does not give you STARTTLS support, so you'd still need to build a copy of OpenSSL to take with you and use swift-nio-ssl for that instead of swift-nio-transport-services TLS support.

**Comment by mremond** [comment]
Thanks !

No, the server part is not triggering authentication, so there should be an issue somewhere. I will try to gather more info.

Regarding iOS TLS, I need STARTTLS (writing a new XMPP library from scratch and this is mandatory), so I guess I need to package OpenSSL with my lib.

**Comment by Lukasa** [comment]
Ah, the error is probably not triggered on the server, it's communicated *to* the server, and the server reports that error.

You can relax this by using `TLSConfiguration.forClient(certificateVerification: .none)`.

**Comment by mremond** [comment]
ah yes, sorry, I missed that obvious way of tweaking this.

Any idea how I could get the error from the client ?
I do not seem to have errorCaught triggered, only channelInactive saying when connection is closed.

**Comment by Lukasa** [comment]
If the handshake is failing, we absolutely should be firing an error before we get `channelInactive`.

**Comment by mremond** [comment]
Yes, strange. I have been spending sometime checking the code path and it seems this line of code does not call the next handler errorCaught function:

https://github.com/apple/swift-nio-ssl/blob/master/Sources/NIOOpenSSL/OpenSSLHandler.swift#L211

The pipeline is correctly set and in right order (I guess, the SSL one is first) and as the inactive function is call, I guess it propagate fine.

I could not yet spot the issue, but I will keep on investigating.

**Comment by mremond** [comment]
Trying to debug it, it feels that it does execute `errorCaught0` on `BaseSocketChannel` implementation. Indeed, this one does nothing.

**Comment by Lukasa** [comment]
`errorCaught0` does do nothing: if you want the error you need to insert a channel handler to catch it.

**Comment by mremond** [comment]
I already have errorCaught function on my main ChannelInboundHandler and I am adding the OpenSSLClientHandler in front, so I expected my main ChannelHandler error to be trigger.
I think I am indeed doing something wrong, but not sure yet what I am missing.

**Comment by Lukasa** [comment]
Are you sure the `errorCaught` function definitely matches the signature required by the protocol?

**Comment by mremond** [comment]
yes, but it definitely looks likes it is falling back to the default protocol implementation, so there should be something wrong in my code.
I am using an older version of the framework, so I also guess I should update my code for the latest version to avoid discrepancies.

 I will dig more and keep you posted.
Thanks for your help !

**Comment by helje5** [comment]
Blind guess:

> is falling back to the default protocol implementation

In Swift that usually is a sign that you adopt a protocol in a superclass which doesn't implement an extension method. Like so:

```swift
protocol DoIt {
  func doIt()
}
extension DoIt { func doIt() { print("default") } }

class A: DoIt {
}
class B: A {
  func doIt() { print("B doit") }
}

let a : A = B()
a.doIt()
```
This will print "default" (unexpectedly for many people).

**Comment by mremond** [comment]
I tracked it down to the `Error` name being overriden in my library namespace.
The signature looked the same, but the error was not actually `Swift.Error`.

I will rename properly the Error type to avoid conflict in the future.

XMPP.Error had been handy for the consuming library but is a time bomb for the library maintainers.

Thanks for your help tracking this down. I confirm that Swift-NIO properly reports SSL certificate errors.

**Comment by helje5** [comment]
Ah right, yes. This is actually pretty common in Swift code, lotsa people do this. I resorted to explicitly typing `Swift.Error` if that is meant.
