### ISSUE TITLE
_NIOBeta doesn't compile with Swift 5.7

### ISSUE THREAD

**Issue by adam-fowler** [apple/swift-nio#2279]
_NIOBeta is assuming `Swift.Duration` is a valid symbol in Swift 5.7 when it is not.

### System and version information
swift-nio: [dee448a](https://github.com/apple/swift-nio/commit/dee448ac8b7dd0f80a48bc0b2e59aec68c651b88)
swift: swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
Target: arm64-apple-macosx12.0

**Comment by Lukasa** [comment]
The bigger issue is that the symbol _is_ valid in Swift 5.7 on every platform except macOS.

**Comment by Lukasa** [comment]
But more broadly, yes, it's possible to run Swift 5.7 with a newer SDK.
