### ISSUE TITLE
Failing to archive via xcodebuild when inside an iOS Framework when building for an XCFramework

### ISSUE THREAD

**Issue by empowerMax** [apple/swift-nio#2280]
> **Warning**
> It's possible this issue doesn't describe a valid use case for this package, having looked at this for a wee while I could have tunnel vision on this! Especially as no one else has raised this. 

### Expected behavior
I have an iOS framework target that depends on swift-nio via SPM. When I try to archive said target with the following incantation 
```
 xcodebuild archive \
-scheme "FooiOSFramework" \
-destination "generic/platform=iOS" \
-archivePath FooiOSFramework \
SKIP_INSTALL=NO \
BUILD_LIBRARY_FOR_DISTRIBUTION=YES
```

I'd expect it to compile swift-nio and it's pals without compile error. Note that I **can** archive this same scheme via Xcode directly, and swift-nio builds just fine when I use it as a package dependency in an iOS app - although in that case it's being pulled in via Vapor.

### Actual behavior

It starts to compile but alas I hit this (note I've trimmed the front of these paths to not include my machine specific stuff)
```
The following build commands failed:
	SwiftCompile normal arm64 Compiling\ PriorityQueue.swift checkouts/swift-nio/Sources/_NIODataStructures/PriorityQueue.swift (in target '_NIODataStructures' from project 'swift-nio')
	CompileSwift normal arm64 checkouts/swift-nio/Sources/_NIODataStructures/PriorityQueue.swift (in target '_NIODataStructures' from project 'swift-nio')
(2 failures)
```

scrolling up the archive log I see:
 
```
/checkouts/swift-nio/Sources/_NIODataStructures/PriorityQueue.swift:21:20: error: 'self' used before 'self.init' call or assignment to 'self'
        self._heap = Heap()
                   ^
/checkouts/swift-nio/Sources/_NIODataStructures/PriorityQueue.swift:22:5: error: 'self.init' isn't called on all paths before returning from initializer
    }
    ^
/checkouts/swift-nio/Sources/_NIODataStructures/PriorityQueue.swift:76:25: error: 'self' used before 'self.init' call or assignment to 'self'
            self._queue = queue
                        ^
/checkouts/swift-nio/Sources/_NIODataStructures/PriorityQueue.swift:77:9: error: 'self.init' isn't called on all paths before returning from initializer
        }
```

As I say, very strange as this archives fine from Xcode directly - however I don't think I can make the archive slices I need to make an XCFramework from Xcode. _For context, as I need both the generic iOS device and generic iOS simulator, and I can't figure out how to archive the latter from Xcode._ 

### Steps to reproduce

I've provided my sample framework. It just links swift-nio and imports it into a dummy file for now.

1. Grab the sample
2. Inside the sample directory try and archive 

```
xcodebuild archive \
-scheme "ArchiveExample" \
-destination "generic/platform=iOS" \
-archivePath Example \
SKIP_INSTALL=NO \
BUILD_LIBRARY_FOR_DISTRIBUTION=YES
```
3. It should fail to compile.

### If possible, minimal yet complete reproducer code (or URL to code)

[ArchiveExample.zip](https://github.com/apple/swift-nio/files/9717981/ArchiveExample.zip)

### SwiftNIO version/commit hash

[2.42.0](https://github.com/apple/swift-nio/releases/tag/2.42.0)

### System & version information

I can't really run nit-diagnose as this pertains to compilation but I'll try and grab this manually 

- MacOS Version: 12.6
- MacOS Arch: m1
- Xcode Version: 14.0 (14A309), note I saw the same behaviour in the latest Xcode 13 as well.
- Swift Version: 5.7 (although I've tried 5.6 as well with no luck)
- swift-nio version: the latest at time of writing [2.42.0](https://github.com/apple/swift-nio/releases/tag/2.42.0). I've tried dialing this back a versions (to 2.40.0 but I'm still seeing issues).
- Min Deployment target of the framework that includes swift-nio: iOS 15.0

**Comment by Lukasa** [comment]
SwiftNIO doesn't define a stable ABI, so it doesn't promise that it will compile cleanly with BUILD_LIBRARY_FOR_DISTRIBUTION=YES. To use SwiftNIO embedded within an ABI-stable framework, you'd need to hide SwiftNIO from your ABI by importing it as `@_implementationOnly`. Doing so should allow you to compile NIO without setting `BUILD_LIBRARY_FOR_DISTRIBUTION=YES`, thereby avoiding the errors.

**Comment by empowerMax** [comment]
Ah wonderful thanks :) , closing this.

**Comment by Hugo-Persson** [comment]
@empowerMax could you share how you fixed the issue? I am facing the same issue

**Comment by empowerMax** [comment]
@Hugo-Persson ah we changed tack in the end. For context I was using Vapor as a mock server for our UI test suite. We changed approach such that we didn't need to depend on Vapor. 

As I wasn't pulling SwiftNIO in directly, I couldn't change how it was imported without forking and editing the consuming package that I was importing (Vapor).

**Comment by Hugo-Persson** [comment]
Okay @empowerMax I am using BSON library which uses Nio. Which puts me in the same situation :/
