### ISSUE TITLE
`NIOAsyncTestingChannel` not working as expected

### ISSUE THREAD

**Issue by adam-fowler** [apple/swift-nio#2283]
### Expected behavior
`NIOAsyncTestingChannel` works with a channel handler that has a `Task` with a suspension point that lasts longer than a few microseconds

### Actual behavior
If Task suspends for longer than a few microseconds then `NIOAsyncTestingChannel` will return `nil`

### If possible, minimal yet complete reproducer code (or URL to code)

The following ChannelHandler should return a number incremented by 1 but it returns `nil`

```swift
final class AsyncChannelHandler: ChannelDuplexHandler {
    typealias InboundIn = Int
    typealias OutboundIn = Never
    typealias OutboundOut = Int

    func channelRead(context: ChannelHandlerContext, data: NIOAny) {
        let number = self.unwrapInboundIn(data)
        let promise = context.eventLoop.makePromise(of: Int.self)
        promise.completeWithTask {
            // if you reduce this to 1000 it works
            try await Task.sleep(nanoseconds: 1_000_000)
            return number + 1
        }
        promise.futureResult.whenComplete { result in
            switch result {
                case .success(let number):
                    context.writeAndFlush(self.wrapOutboundOut(number), promise: nil)
                case .failure(let error):
                    print("\(error)")
            }
        }
    }
}

func testAsyncTestingChannel() async throws {
    let channel = NIOAsyncTestingChannel()
    try await channel.pipeline.addHandler(AsyncChannelHandler())
    // write to channel
    try await channel.writeInbound(1)
    // run
    await channel.testingEventLoop.run()
    // read from channel
    let outbound = try await channel.readOutbound(as: Int.self)
    print(outbound?.description ?? "nil")
}
```

### SwiftNIO version/commit hash

cdeffe8c5bb88288ee624bb81fefe0508abe5a29

### System & version information

Swift version: swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
Target: x86_64-apple-macosx12.0
System: Darwin Adams-iMac-Pro-2.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

**Comment by adam-fowler** [comment]
Actually just found you don't need a suspension point. The task just needs to take some amount of time eg
```swift
promise.completeWithTask {
    var number = number
    for i in 0..<10000 {
        number += I
    }
    return number
}
```

**Comment by Lukasa** [comment]
I suppose one possible interpretation of what you might want is a way to _wait_ for an I/O operation. That’s a useful API extension, I think.

**Comment by adam-fowler** [comment]
> You aren’t waiting for your background task to complete,

Fair point, but where would I wait for this Task to finish. I can't in `channelRead`

**Comment by adam-fowler** [comment]
That was what I was thinking, either `waitForChannelRead` or `waitForFlush` would work. You know the channel is going to produce an output, so you should wait for it (perhaps with a deadline just to be safe).
