### ISSUE TITLE
NIOLock: Reduce indirection/allocations by tail-allocating the mutex

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#2298]
NIOLock should leverage `ManagedBuffer(Pointer)` to tail-allocate the `pthread_mutex_t` in its `class Storage`.

This will reduce indirection & allocations for every `NIOLock` instance.

---

related issue: #2299

**Comment by Lukasa** [comment]
FYI, there's an existing PR at #2349

**Comment by agnosticdev** [comment]
> FYI, there's an existing PR at #2349

Ah, okay very good.  Disregard my comment then 👍

**Comment by Lukasa** [comment]
Resolved by #2349.
