### ISSUE TITLE
NIOLockedValueBox: tail allocate the mutex

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#2299]
`NIOLockedValueBox` should leverage `ManagedBuffer(Pointer)` to tail-allocate the `pthread_mutex_t` in its `class Storage`.

This will reduce indirection & allocations for every `NIOLockedValueBox` instance.

Very similar to #2298 & #1039

**Comment by Lukasa** [comment]
Despite your optimism I'm going to remove the "good first issue" tag here: I don't think anything that touches ManagedBuffer(Pointer) is a good first issue.

**Comment by weissi** [comment]
@Lukasa Well, requires 0 SwiftNIO knowledge (but of course low-level Swift knowledge).

**Comment by agnosticdev** [comment]
Looks like this one can be closed too by the work done on https://github.com/apple/swift-nio/issues/2298 ?

**Comment by dnadoba** [comment]
Indeed, thanks!
