### ISSUE TITLE
Special case `EventLoopPromise.succeed()` when `Value` is `Void`

### ISSUE THREAD

**Issue by glbrntt** [apple/swift-nio#2310]
To succeed an `EventLoopPromise<Void>` users must pass a void-value to it, e.g.:
- `promise.succeed(())` 
- `promise.succeed(Void())`

It would be nice if we could spell this as `promise.succeed()`.

**Comment by mob-connection** [comment]
Maybe something like this ?
```
extension EventLoopPromise where Value == Void {
    @inlinable
    public func succeed() {
        succeed(Void())
    }

}
```

**Comment by glbrntt** [comment]
Yes, something like that. Would you like to open a PR for this @mob-connection?
