### ISSUE TITLE
What are the plans to support HTTP2?

### ISSUE THREAD

**Issue by MrMage** [apple/swift-nio#232]
First of all, thanks for all this great work! I am a contributor to the [`grpc-swift`](https://github.com/grpc/grpc-swift) project and interested in building a fully Swift-native gRPC implementation on top of SwiftNIO. Having an existing HTTP2 stack to build on would greatly simplify that, and the docs say that such a stack is planned. Is there any information to that module's development plans and schedule?

(This should then also greatly improve interoperability between gRPC and Vapor, as both would then run on the same event loop for much less impedance mismatch. @tanner0101 is interested in that as well.)

**Comment by Lukasa** [comment]
HTTP/2 support is being actively worked on, but we want to build a few abstractions on top of it to make it easier to use in the HTTP server/client case as well. This means it's a TBD as to exactly when it'll ship. We are at this stage reluctant to commit to any timeline more aggressive than Soon™️.

**Comment by Lukasa** [comment]
(See also #55.)

**Comment by Lukasa** [comment]
Hoping to open the beta repo today.

**Comment by kylebrowning** [comment]
@Lukasa Im sorry to have made you say a date!

Cant wait for this so I can use it for new push notifications setup.
