### ISSUE TITLE
EventLoopFuture should have an `assertSuccess()` (and maybe `assertFailure()` methods)

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#2359]
Futures are in many places used in ways that make sure that a certain future will only ever succeed (and never fail). In those cases, it'd be nice to write

```
someFuture
    .assertSucceess()
    .map { value in
        [...]
    }
```

**Comment by dkz2** [comment]
Overall idea: we want to ensure that a future will only succeed and never fail. If it does fail, we trigger an assertion failure, causing a runtime error during development. Similarly, the assertFailure() method would ensure that a future will only fail and never succeed.

**Comment by weissi** [comment]
@dkz2 exactly!
