### ISSUE TITLE
EmbeddedChannel.readOutbound should be able to deal with types other than IOData

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#243]
### Expected behavior

You'd expect that with an `EmbeddedChannel` you can read any type from the outbound buffer. Unfortunately the signature is `public func readOutbound() -> IOData?`. This should be changed to `public func readOutbound() -> NIOAny?` or `public func readOutbound() -> Any?`.

The reason that this is important is that for testing you don't want to serialise everything before testing what went through the `ChannelPipeline`. Sure you can workaround with an `OutboundChannelHandler` that collects everything but that's rather annoying and isn't necessary.

Annoyingly `EmbeddedChannel` is `public` that means this will need to wait until we make a 2.0 release.

### Actual behavior

can only read `IOData`.

### Steps to reproduce

1. Make an `EmbeddedChannel`
2. Write some arbitrary type that isn't `IOData` to it (for example `String`)
3. try to read it out

### SwiftNIO version/commit hash

1.x

### Swift & OS version (output of `swift --version && uname -a`)

any

**Comment by IOOI-SqAR** [comment]
I think this should have Milestone 2.0.0 too

**Comment by weissi** [comment]
fixed now with #763
