### ISSUE TITLE
ByteBuffer docs: ByteBuffer docs explain sequential and random access but not wholesale conversion

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#2468]
The best way to convert `ByteBuffer` to `String`/`Array<UInt8>`/`Data` is

```
TargetType(buffer: byteBuffer)
```

e.g. `Data(buffer: myByteBuffer`. But the ByteBuffer docs don't explain that.

**Comment by natikgadzhi** [comment]
I'm on it — will put up a PR in a couple of days. My knowledge of `ByteBuffer` is far from deep, but I think I've read up on the basics enough to write a coherent explanation.
