### ISSUE TITLE
ByteBuffer docs issue: Does not dissuade users from using `get*`

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#2469]
`ByteBuffer.get*` is very often abused/misused. For example, what I see a lot is `buf.getData(at: 0, length: buf.readableBytes)!`.

Obviously the user should do `Data(buffer: buf)` here because it's nicer and shorter.

But most importantly, the `at: 0` is actually wrong. We should very much dissuade users from doing `get*`. They should do `TargetType(buffer: buf)` or `read*`. The docs don't say that.

**Comment by natikgadzhi** [comment]
Uh oh. So I was working on the hexdump helpers (https://github.com/apple/swift-nio/pull/2475), and very much used `getInteger(at:` and `getString(at:`. While I access bytes at specific indices and don't just do `at: 0`, can you point me at why using 0 as index is wrong?

**Comment by weissi** [comment]
> Uh oh. So I was working on the hexdump helpers (#2475), and very much used `getInteger(at:` and `getString(at:`. While I access bytes at specific indices and don't just do `at: 0`, can you point me at why using 0 as index is wrong?

The `get*` methods are very low-level and most of the time dangerous. The readable bytes of a `ByteBuffer` start are `readerIndex ..< writerIndex` (see doc comments). So `0` might be before `readerIndex` so you can't use that. For users we actually very much recommend not to use `get*` at all unless you have a special network protocol that talks in byte positions (and you'd need to make sure that your readerIndex is 0). See also #2468

**Comment by natikgadzhi** [comment]
As the hex dump PR is close to a wrap, I think I stumbled at this enough times to try and put up a PR. I'll start with #2468, that one seems to be smaller.
