### ISSUE TITLE
Futures: expose quick init

### ISSUE THREAD

**Issue by vlm** [apple/swift-nio#248]
We'd like to use something like that:

```swift
Future(eventLoop: group.next(), result: T.self)
```

however, this specialization is not public. So instead we have to go through the promise, and it adds boilerplate and affects performance a bit:

```swift
let promise = Promise<T>()
promise.succeed(result: T.self)
return promise.futureResult
```

And we can't fix the boilerplate, because the EventLoopFutures class is final.

Please advise.

**Comment by Lukasa** [comment]
Is `eventLoop.newSuccededFuture()` not sufficient?

**Comment by vlm** [comment]
* Missed that for some reason, thanks!
 * it calls `EventLoopFuture<T>(eventLoop: self, result: result, file: "n/a", line: 0)`, which robs it from the useful debug information, probably makes sense to address the file/line properly.
 * Same for newFailedFuture().

**Comment by Lukasa** [comment]
Yeah, they should probably do better.
