### ISSUE TITLE
onboard to CodeQL

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#2492]
From https://forums.swift.org/t/codeql-updates/66540 I understand that SwiftNIO needs to be onboarded, this is probably a good idea :)

**Comment by 1proprogrammerchant** [comment]
this may be worth it well after we fix of the problems and issues with swift-nio we'll consider it

**Comment by Lukasa** [comment]
CodeQL relies on Github actions, which we do not use.

**Comment by 1proprogrammerchant** [comment]
> CodeQL relies on Github actions, which we do not use.

oh yea almost forgot we didn't have that sorry for the confusion
