### ISSUE TITLE
ByteBuffer should be Codable

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#2507]
`ByteBuffer` should implement `Codable` in way that makes

```
struct FooBB: Codable {
   var bytes: ByteBuffer
}
```

encode/decode into the same `.json` as

```
struct FooData: Codable {
  var bytes: Data
}
```

does for

`JSONEncoder().encode(FooData(bytes: Data(buffer: fooBB.bytes)))`

Clarifying note: I very much do _not_ want to be able to encode as `FooBB` and decode as `FooData` (or vice versa) but I want a refactoring of `FooData` to `FooBB` to result in the same `.json` files.

**Comment by Lukasa** [comment]
The only way we can achieve this is to import `Foundation`.

**Comment by weissi** [comment]
> The only way we can achieve this is to import `Foundation`.

Why? `Codable` is stdlib, not Foundation

```
$ cat test.swift 
import DataTypeOnlyNoFoundation
import Foundation

print(String(
    decoding: try JSONEncoder().encode(MyStruct("hello")),
    as: UTF8.self
))

// MODULE: DataTypeOnlyNoFoundation
public struct MyStruct: Codable {
    var x: (String, ())

    public init(_ s: String) {
        self.x = (s, ())
    }

    public init(from decoder: Decoder) throws {
        let str = try decoder.singleValueContainer().decode(String.self)
        self.x = (str, ())
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(self.x.0)
    }
}
```

run 

```
$ ~/devel/swift-nio/dev/make-single-file-spm test.swift run
all extra modules: DataTypeOnlyNoFoundation
SwiftPM package in:
  /tmp/test_package_BuBCEU
  /tmp/test_package_BuBCEU/.build/release/TestApp
Building for production...
[3/3] Linking TestApp
Build complete! (22.52s)
Building for production...
Build complete! (0.24s)
"hello"
```

**Comment by weissi** [comment]
@Lukasa I just want to match `Data`'s encoding/decoding _format_ not the actual implementation. I think it does base64, so we can base64 the BB's bytes and encode it.

**Comment by Lukasa** [comment]
Because if the requirement is to encode as if ByteBuffer were Data, then it needs to actually encode a Data. Coders [frequently type-check the thing they've been asked to encode](https://github.com/apple/swift-foundation/blob/cdf40169dce02ad77a87f646ff37d551ad01a689/Sources/FoundationEssentials/JSON/JSONEncoder.swift#L1116-L1118).

On the other hand, if the requirement is only to encode _like_ `Data`, then we need to double-up our Base64 encoder from WebSocket. Not the end of the world, but just an FYI.

**Comment by weissi** [comment]
> Because if the requirement is to encode as if ByteBuffer were Data, then it needs to actually encode a Data. Coders [frequently type-check the thing they've been asked to encode](https://github.com/apple/swift-foundation/blob/cdf40169dce02ad77a87f646ff37d551ad01a689/Sources/FoundationEssentials/JSON/JSONEncoder.swift#L1116-L1118).

Sorry, I very much do _not_ want you to encode as `FooData` and then decode as `FooBB`, that'd be bad. I want that refactoring `FooData` to `FooBB` on _both_ the encoding/decoding side results in no change to your `.json`s.


> On the other hand, if the requirement is only to encode _like_ `Data`, then we need to double-up our Base64 encoder from WebSocket. Not the end of the world, but just an FYI.

Yes, that's the goal and yes, that's understood. The base64 encoder would need to probably go into `_NIOBase64` or smth assuming that we don't want to ship it.

**Comment by weissi** [comment]
Added clarification to what I mean in the OP.

**Comment by weissi** [comment]
@fabianfett This might actually retroactively be the reason for why you made the base64 code fast :). In WebSocket it's a fixed 64 byte (or whatever it actually is) string so speed doesn't matter but if we implement this, then it _will_.

**Comment by Lukasa** [comment]
>  I want that refactoring FooData to FooBB on both the encoding/decoding side results in no change to your .jsons.

Excluding any customised `DataEncodingStrategy`?

**Comment by weissi** [comment]
> > I want that refactoring FooData to FooBB on both the encoding/decoding side results in no change to your .jsons.
> 
> Excluding any customised `DataEncodingStrategy`?

Yes. Given that this only(?) affects JSONEncoder/JSONDecoder which are only in Foundation I wonder if we can add extra stuff into `NIOFoundationCompat`. But I'd assume that there's no way to even invoke a custom `DataEncodingStrategy` for non-`Data` types.

**Comment by Lukasa** [comment]
Yeah, there isn't.

FWIW, `Data`s [default `Codable` implementation isn't base64](https://github.com/apple/swift-foundation/blob/cdf40169dce02ad77a87f646ff37d551ad01a689/Sources/FoundationEssentials/Data/Data.swift#L2597-L2627). So there's definitely some weirdness here.

**Comment by weissi** [comment]
> Yeah, there isn't.
> 
> FWIW, `Data`s [default `Codable` implementation isn't base64](https://github.com/apple/swift-foundation/blob/cdf40169dce02ad77a87f646ff37d551ad01a689/Sources/FoundationEssentials/Data/Data.swift#L2597-L2627). So there's definitely some weirdness here.

Weird!

```
$ cat test2.swift
import Foundation

print(String(
    decoding: try JSONEncoder().encode(Data("hello".utf8)),
    as: UTF8.self
))
$ swift test2.swift
"aGVsbG8="
```

Is `JSONEncoder`'s default data encoding strategy just `.base64` then?

Anyway, I should rephrase my ask to just base64 en/decode BB then. Seems more convoluted than I thought it is.

**Comment by weissi** [comment]
Ah yes

```
$ swift test2.swift
"aGVsbG8="
base64
```

for

```
$ cat test2.swift
import Foundation

print(String(
    decoding: try JSONEncoder().encode(Data("hello".utf8)),
    as: UTF8.self
))

print(JSONEncoder().dataEncodingStrategy)
```

**Comment by fabianfett** [comment]
The default impl of data is an int array. Why? Because Codable! That's why!

**Comment by 1proprogrammerchant** [comment]
hmmm!

**Comment by natikgadzhi** [comment]
@weissi, so it doesn't have to be more complicated than:

```swift
extension ByteBuffer:Codable {
    public init(from decoder: Decoder) throws {
        var container = try decoder.unkeyedContainer()
        // make a bytebuffer from the cotainer
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.unkeyedContainer()
        for byte in self.readableBytesView {
            try container.encode(byte) // rethrow errors 
        }
    }
}
```

Am I missing anything? I don't know if iterating over the `readableBytesView` and encoding bytes one by one is performant — my gut tells me perhaps dumping the whole thing as an `UnsafePointer` into `encode` could be faster.

Want me to push up a PR with this and a few tests?

**Comment by Lukasa** [comment]
I think @weissi wants this to encode through Base64, so we need to move the Base64 code from NIOWebsocket to NIOCore and use that.

**Comment by weissi** [comment]
Yes, I was thinking base64 makes the most sense. But apart from shuffling the base64 code around it wouldn't be much more complicated than what @natikgadzhi posted, just encoding into a single-value String container instead of an unkeyed container.

**Comment by fabianfett** [comment]
@Lukasa Get a newer copy of it though. And do we want to have two copies of it or do we create another underscored module?

**Comment by Lukasa** [comment]
We could safely expose it as SPI I think, or an underscored module. Either works.

**Comment by natikgadzhi** [comment]
I'd love to learn how to expose it as SPI. I can tinker and learn, I've seen other SPIs in NIO codebase already. @weissi if it's okay that it would take 1-3 weeks to get this in, I can work on this.

**Comment by weissi** [comment]
> I'd love to learn how to expose it as SPI. I can tinker and learn, I've seen other SPIs in NIO codebase already. @weissi if it's okay that it would take 1-3 weeks to get this in, I can work on this.

Time is not an issue. Thank you for your time in advance!

Regarding `@_spi`: There's a bunch of info here: http://wanderwaltz.github.io/2022/02/23/Swift-SPI.html and yes, there are examples in the NIO repo.

Unfortunately, `@_spi` isn't compatible with `@usableFromInline` at this point in time so that could cause trouble. The workaround would be just `_NIOUnderscoredTypesAreNotPartOfThePublicAPI` or `_NIOUnderscoredModule`.

**Comment by Lukasa** [comment]
Totally happy with an underscored module for this.

**Comment by natikgadzhi** [comment]
Speaking of underscored modules, `_NIOConcurrency` was last updated 23 months ago in #1970 — should we rip it out, or is it still used out there?

**Comment by Lukasa** [comment]
At this stage I'm inclined to leave it until we do a breaking change.
