### ISSUE TITLE
Sending/Receiving IP Packets Without Root Privilege

### ISSUE THREAD

**Issue by johnnzhou** [apple/swift-nio#2514]
### Expected behavior
Send and receive IP packets (i.e. ICMP Request/Response) without needing to acquire root privilege on macOS or Linux. It would be more user-friendly if swift-nio could allow user to choose between different `socketType` (`.raw` or `.datagram`) to run under various permission and privilege to send and receive IP packets.

### Actual behavior
Using `NIORawSocketBootstrap` in swift-nio requires the caller to execute under `sudo` command. Otherwise, `Operation not permitted (errno: 1)` will be thrown.

### Steps to reproduce
Run the following code snippet will result in the following error:
`socket(domain:type:protocolSubtype:): Operation not permitted (errno: 1)`

```swift
import Foundation
import NIO
import NIOCore
import NIOPosix

@main
struct Test {
    public static func main() async {
        let group = MultiThreadedEventLoopGroup(numberOfThreads: 2)
        let client = NIORawSocketBootstrap(group: group)
        let channel = try! await client.connect(host: "google.com", ipProtocol: .icmp).get()
    }
}
```

### SwiftNIO version/commit hash

SwiftNIO 2.58.0

### System & version information

Please provide at the very least your operating system and Swift version
information.

macOS Version: Version 13.2.1
platform: MacBook Pro 15 (Intel-based)
swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: x86_64-apple-macosx13.0

**Comment by Lukasa** [comment]
Thanks for this! This is a reasonable feature request.

Can you try to investigate a few things for me? Firstly, can you try creating the `SOCK_DGRAM`/`IPPROTO_ICMP` socket yourself and then using [`withBoundSocket`](https://swiftpackageindex.com/apple/swift-nio/main/documentation/nioposix/datagrambootstrap/withboundsocket(descriptor:)) to create a `DatagramChannel`? I'm curious if this gets you enough functionality to get going.

**Comment by johnnzhou** [comment]
Creating `DatagramChannel` through `socket(AF_INET, SOCK_DGRAM, IPPROTO_ICMP)`  and `withBoundSocket` eliminate raw socket permission issue, although I haven't tried sending anything through the channel. It seems to get things move forward. :). Writing C with Swift is definitely not pleasant.

**Comment by Lukasa** [comment]
I think that's the short-term alternative. If it actually works (that is, if the I/O functions for your use-case) then it's a small enhancement to enable datagram channel to do this with a Swift API.

**Comment by johnnzhou** [comment]
Great! Look forward to seeing official implementation coming to swift-nio in the future!

**Comment by Lukasa** [comment]
Take a look at #2516 and see if that's useful for you.

**Comment by johnnzhou** [comment]
Thanks for adding the support this fast! I replaced the `socket(AF_INET, SOCK_DGRAM, IPPROTO_ICMP)` with the new implementation. The channel is able to send and receive ICMP packets, as expected. This is hugely helpful! Thanks
