### ISSUE TITLE
Needs Pods Support for latest 2.59.0 SwiftNIO version

### ISSUE THREAD

**Issue by kanjsahu** [apple/swift-nio#2555]
### Request
SwiftNIO no longer supports Pods after version 2.40.0. As we all know, the 2.40.0 Lib has several security issues, thus I wanted to use the most recent version of SwiftNIO, 2.59.0. I've been using SwiftNIO in my projects for many years, and it's now pretty tough to fast SPM instantly.
It would be beneficial if you could also support Pods.

**Comment by 0xTim** [comment]
@kanjsahu SwiftNIO dropped support for Cocoapods long ago https://forums.swift.org/t/swiftnio-is-dropping-support-for-cocoapods/56840

**Comment by Lukasa** [comment]
This is correct: we have no intention of supporting Cocoapods.

**Comment by weissi** [comment]
@kanjsahu FWIW, if you are willing to support Cocoapods for SwiftNIO that's absolutely possible in a repository that is not `apple/swift-nio`. For example see [this comment](https://forums.swift.org/t/swiftnio-is-dropping-support-for-cocoapods/56840/7) and the ones further down. From what I know, nobody in the community stepped up to create and maintain NIO podspecs and most people seem to have moved on to SwiftPM.
