### ISSUE TITLE
NonBlockingFileIO has no async APIs 

### ISSUE THREAD

**Issue by adam-fowler** [apple/swift-nio#2565]
It appears that the best option for file access is still `NonBlockingFileIO`. Currently to use `NonBlockingFileIO` in a Swift concurrency context you are required to use the `EventLoop` based API and `EventLoopFuture.get`. This is unsatisfactory because 

1) You need an EventLoop to call any of the functions
2) Waiting on a process running on the NIOThreadPool requires two hops: one to the EventLoop and then one to your async task.

Are there any plans to produce async `NonBlockingFileIO` APIs?

**Comment by Lukasa** [comment]
We certainly plan to produce _a_ solution in this area. However, in our ideal world this wouldn't be NIO-based at all, as the solution should be more general purpose than that.

**Comment by adam-fowler** [comment]
Would you be adverse to me producing a temporary solution that still uses NIOThreadPool but skips the EventLoopPromise and uses a Continuation instead?

This is basically the last barrier to removing EventLoops from Soto.

**Comment by Lukasa** [comment]
I'd be happy for you to do that work.

**Comment by JawadHF** [comment]
> We certainly plan to produce _a_ solution in this area. However, in our ideal world this wouldn't be NIO-based at all, as the solution should be more general purpose than that.

Just to understand, would that be something like [Swift System](https://github.com/apple/swift-system) ?
