### ISSUE TITLE
Deinited NIOAsyncWriter without calling finish() if socket connection failed

### ISSUE THREAD

**Issue by johnnzhou** [apple/swift-nio#2612]
### Expected behavior
When calling the async version of ClientBootstrap(group:).connect(to:channelInitializer), the connection failure should throw an error, similar to the normal version where connection reset error is thrown.

### Actual behavior
Right now, no error will be thrown and the async channel is deinitialized without properly calling finish() on the NIOAsyncWriter. This causes the fatal error to be thrown and halts the program

### Steps to reproduce

Run the following code with `swift run`.

### If possible, minimal yet complete reproducer code (or URL to code)

```swift
import Foundation
import NIOCore
import NIOPosix
import NIOHTTP1

@main
struct Test {
    public static func main() async {
        do {
            let resolvedAddress = try SocketAddress.makeAddressResolvingHost("127.0.0.1", port: 9090)
            let eventLoopGroup = MultiThreadedEventLoopGroup(numberOfThreads: 1)
            let asyncChannel = try await ClientBootstrap(group: eventLoopGroup).connect(to: resolvedAddress) { channel in
                channel.eventLoop.makeCompletedFuture {
                    try channel.pipeline.syncOperations.addHTTPClientHandlers(position: .last)
                    return try NIOAsyncChannel<ByteBuffer, String>(wrappingChannelSynchronously: channel)
                }
            }
            print("async channel is \(asyncChannel)")
        } catch {
            print("error: \(error)")
        }
    }
}
```

### SwiftNIO version/commit hash

swift-nio version: `2.62.0`

### System & version information

macOS Ventura: Version 13.2.1 (22D68)
swift version: swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: x86_64-apple-macosx13.0

**Comment by FranzBusch** [comment]
Thanks for filing this. We are aware of some cases where the current `deinit` of the `NIOAsyncWriter` gets hit. I am going to look into this one as well

**Comment by johnnzhou** [comment]
Thank you @FranzBusch for your timely response!

**Comment by FranzBusch** [comment]
This should be fixed by https://github.com/apple/swift-nio/pull/2703
