### ISSUE TITLE
SwiftNIO pod spec missing for 2.39.1

### ISSUE THREAD

**Issue by jainricha** [apple/swift-nio#2623]
The pod spec for release 2.39.1 is currently missing here: https://github.com/CocoaPods/Specs/tree/master/Specs/e/8/6/SwiftNIO

Could you please upload podspec for 2.39.1?

**Comment by jainricha** [comment]
At this point it is not possible to migrate and we need to fix the security vulnerability. I even tried the script provided to generate the podspec, but I am not authorised to push those:

`
[!] You are not allowed to push new versions for this pod. The owners of this pod are cocoapods@danielalm.de, cbenfield@apple.com, johannesweiss@apple.com, gbarnett@apple.com, jprickett821@gmail.com, pp_adams@apple.com, and d.evans@apple.com.`

I do not need extensive cocoapod support but just to push this podspec we need your support specifically for 2.39.1 version which was a patch you guys provided. 
Whats the point in releasing a patch if nobody can use it.  

I hope you understand.

**Comment by Lukasa** [comment]
> Whats the point in releasing a patch if nobody can use it.

Many people can use it. Cocoapods users cannot use it, but we did call this out ahead of time, and have very few cocoapods users.

Unfortunately, while I attempted to publish 2.39.1 pods, it seems the pods have rotted in the meantime and can no longer be published in their current form. As the pods aren't supported, I can't justify spending the time required to fix this up. You can fork the pods locally and use those to take new updates.
