### ISSUE TITLE
Proposal: Contributing HTTP Response Status Code Mappings

### ISSUE THREAD

**Issue by nashysolutions** [apple/swift-nio#2644]
Hi there,

I've been using the [HTTPResponseStatus extension](https://github.com/apple/swift-nio/blob/745c79246b6c50ceb8cf315aaae7af1ee073a54d/Sources/NIOHTTP1/HTTPTypes.swift#L814) in Swift-NIO, which maps HTTP response status names to codes. I think this code could be beneficial in the [Swift HTTP Types](https://github.com/apple/swift-http-types) project. Would you be open to including it?

Cheers,
Rob

**Comment by Lukasa** [comment]
I believe that project already has the equivalent mappings. Is there anything you think you’re missing?

**Comment by nashysolutions** [comment]
> I believe that project already has the equivalent mappings. Is there anything you think you’re missing?

The extension I've mentioned includes some additional functionality that I believe could complement the existing mappings in the project. I've outlined the specifics in the linked document, which details the features that are currently not covered. Could we discuss the potential integration of these additional features?

Unless they are in fact covered and I'm looking in the wrong place?
