### ISSUE TITLE
NIOFileSystem uses yet another thread pool instead of NIOThreadPool

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#2653]
This is quite an important issue for adopting NIOFileSystem in real world systems: It needs to use the same thread pool as NIOThreadPool.

Larger scale real-world systems carefully size NIO's thread pool for blocking I/O. They will of course expect to not have another pool spawned by a random module like NIOFileSystem.

The fix should be really straightforward by just removing the custom threads code in NIOFileSystem and using NIOThreadPool instead. That's literally exactly what NIOThreadPool got created for.

Additionally, NIOFileSystem should also accept other NIOThreadPools. But that's less critical for right now.

**Comment by adam-fowler** [comment]
I was quite surprised to see NIOFileSystem setup its own thread pool as well. Has there been anymore discussion around this as there is no response here.

**Comment by Lukasa** [comment]
There's no disagreement on whether this needs fixing, it's just a matter of us scheduling the work.

**Comment by glbrntt** [comment]
Fixed by #2692
