### ISSUE TITLE
NIOFileSystem's BufferedWriter produces empty files when they shouldn't be empty

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#2663]
```
try await FileSystem.shared.withFileHandle(
    forWritingAt: "/tmp/testy",
    options: .newFile(replaceExisting: true)
) { fileHandle in
    var writer = fileHandle.bufferedWriter()
    try await writer.write(contentsOf: "hello\n".utf8)
}
```

results in an empty file `/tmp/testy`.

It's really non-obvious that I'll lose some parts of the file if I don't `flush`.

**Comment by glbrntt** [comment]
The obvious fix here is adding a `withBufferedWriter`. As an extension we _could_ turn `BufferedWriter` into a `class` and assert on `deinit` that there are no unflushed bytes.
