### ISSUE TITLE
NIOFileSystem: BufferedReader.read(while:) doesn't say if it stopped reading because the condition was met or because or EOF

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#2665]
It's quite hard to hold `BufferedReader.read(while:)` correctly because when it returns with an empty chunk it's unclear if that's because EOF has been reached or because the condition hit.

For example

```
let line = try await reader.read(while: { $0 != UInt8(ascii: "\n") })
```

may return an empty line if `\n\n` has been hit or if EOF has been hit. I couldn't find anything to let me tell this apart.

**Comment by glbrntt** [comment]
Fixed by #2688
