### ISSUE TITLE
NIOFileSystem: BufferedReader can only return `[UInt8]` and not `ByteBuffer`

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#2666]
The main APIs return only `ByteBuffer`s, but `BufferedReader` returns `Array<UInt8>`

**Comment by glbrntt** [comment]
Oof, thanks. Looks like an oversight when we switched to `ByteBuffer`.

**Comment by glbrntt** [comment]
`BufferedReader` already uses `ByteBuffer`
