### ISSUE TITLE
Not working on iPadOS 17.4.1

### ISSUE THREAD

**Issue by pTech01** [apple/swift-nio#2698]
### Expected behavior
import

### Actual behavior
>The target type "ClangTarget" is not supported" <

### Steps to reproduce

1. Importing on Swift Playground using iPadOS 17.4.1
2. add -> Swift Package -> inserting package URL

### SwiftNIO version/commit hash
newest version

_[the SwiftNIO tag/commit hash]_

### System & version information
iPadOS 17.4.1, Playground 4.5 using Swift 5

**Comment by Lukasa** [comment]
Thanks for filing this issue and sorry for my delay in responding. This is a known limitation in Swift Playgrounds: https://forums.swift.org/t/adding-packages-in-swift-playgrounds-4/54173/2. Sadly, we have C targets that we cannot remove, and so this is not supported by Playgrounds at this time. If you feel it should be, please file a Feedback Assistant report and post it here.

**Comment by glebone** [comment]
It would be very useful to have ability to play with NIO code in Playgrounds.. Would be good to have instruction how to modify package for Playground import
