### ISSUE TITLE
Multicast UDP

### ISSUE THREAD

**Issue by khoogheem** [apple/swift-nio#270]
Anywork being done on Multicast for UDP?

wanted to see where that is on the priority and if I can lend a hand here or if someone else is already working on it.

**Comment by Lukasa** [comment]
Currently we're not actively working on it, but it's something we want. If you're interested in doing the work we'd be happy to review a patch.

You may find it useful to kick API design ideas around before you get too far into coding though!

**Comment by normanmaurer** [comment]
We did not start it yet... that said we Love PRs

**Comment by Lukasa** [comment]
This has shipped.
