### ISSUE TITLE
Crash in NIOFileSystem

### ISSUE THREAD

**Issue by MahdiBM** [apple/swift-nio#2701]
### Expected behavior
No crash.

### Actual behavior
We’re getting some weird crashes on SwiftNIO 2.64.0 + Swift 5.10.
They seem to be coming from the NIOFileSystem.
<kbd>
<img width="1353" alt="Screenshot 2024-04-15 at 10 53 25 AM" src="https://github.com/apple/swift-nio/assets/54685446/18430635-1866-42ce-a9bb-e4213c2d33f5">
<img width="1230" alt="Screenshot 2024-04-15 at 10 52 57 AM" src="https://github.com/apple/swift-nio/assets/54685446/c53ffe90-ea21-449c-9028-d46d56788385">
</kbd>

### Steps to reproduce

n/a

### If possible, minimal yet complete reproducer code (or URL to code)

n/a

### SwiftNIO version/commit hash

2.64.0

### System & version information

Swift 5.10, Ubuntu 22.04, amd64.

**Comment by Lukasa** [comment]
NIOFileSystem is not on your stack there, so this is definitely not a NIOFileSystem issue. This is a NULL pointer deref deep in the Swift runtime, which might well be caused by thread-safety issues in your code or in Vapor. Can I suggest filing this as a Vapor issue?

**Comment by MahdiBM** [comment]
Oops, sorry it's only in NIOFileSystem's target, not in the type itself. We'll have a look at it on the Vapor side 🙂
