### ISSUE TITLE
QUIC support in Swift

### ISSUE THREAD

**Issue by palfonsoilluscio** [apple/swift-nio#2705]
Hi SwiftNIO team:

We know this topic has been discussed before, however we just wanted to double check with you if QUIC is something that you are supporting now or if it is still not on your plans.

Really appreciate your thoughts.

Thanks in advance.

**Comment by Lukasa** [comment]
I'm going to close this to keep the focus on #1730. The answer remains that we think it's important, but that we do not have a specific roadmap item to do the work at this time.
