### ISSUE TITLE
Document the behaviour of the promise in `close` and the channel `closeFuture`.

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio#271]
It's not necessarily totally apparent to users how `close` and `closeFuture` work, nor is it clear that the promise passed to `close` will fire *way* before the `closeFuture` completes. The two have very different signals but very similar names, which could easily cause confusion. We should document the difference.

**Comment by agnosticdev** [comment]
I took a first attempt at this with PR#419: https://github.com/apple/swift-nio/pull/419
