### ISSUE TITLE
'LockStorage<Void>' has no member 'mutex' on Win11

### ISSUE THREAD

**Issue by xinye0123** [apple/swift-nio#2720]
C:\Users\User\Desktop\AvocadoToast\.build\checkouts\swift-nio\Sources\NIOConcurrencyHelpers\lock.swift:225:74: error: value of type 'LockStorage<Void>' has no member 'mutex'
            if !SleepConditionVariableSRW(self.cond, self.mutex._storage.mutex,
                                                     ~~~~~~~~~~~~~~~~~~~ ^~~~~
error: fatalError

**Comment by Lukasa** [comment]
Currently SwiftNIO does not compile on Windows, unfortunately. For a number of reasons this is not a supported platform. Closing this to keep everything tracked under #2065.
