### ISSUE TITLE
MessageToByteHandler never shrinks its buffer (it should!)

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#2734]
https://github.com/apple/swift-nio/blob/e2aef20375a9626b4ce3a32786a6626678e9f19c/Sources/NIOCore/Codec.swift#L748

NIO's `MessageToByteHandler` tries to reuse its existing `self.buffer` to save allocations. It doesn't however ever shrink that buffer. So if the user ever sends something super large, the buffer will forever be super large. I reckon even potential CoW copies will just reallocate a huge buffer.

Anyway, M2BH should shrink the buffer just like B2MD does if it's too large.

(This is not a security issue though because M2BH is in the _outbound_ pipeline, so the data is user controlled and not network controlled.)

**Comment by ali-ahsan-ali** [comment]
Hi, trying to take a look at this one 👍 . "M2BH should shrink the buffer just like B2MD does." This suggests that there is a solution in mind. 

I have taken some time to look at the code, wondering if said solution is to copy the implementation for discardReadBytes but instead shrink the buffer size to the writeIndex after the context.write operation has been completed?

Any pointers would be appreciated. Thanks for your time 😄 .

**Comment by ali-ahsan-ali** [comment]
I think this can be closed
