### ISSUE TITLE
ChannelTests - testBasicLifecycle fatal error

### ISSUE THREAD

**Issue by karim-elngr** [apple/swift-nio#282]
### Expected behavior
ChannelTests - testBasicLifecycle should pass 

### Actual behavior
ChannelTests - testBasicLifecycle - on very rare occasions throws fatal error when trying to execute `serverAcceptedChannel!` in this line of code `try EventLoopFuture<Void>.andAll([clientChannel.closeFuture, serverAcceptedChannel!.closeFuture], eventLoop: group.next()).map`:

Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

Fatal error: Unexpectedly found nil while unwrapping an Optional value
2018-04-05 17:52:39.328613+0200 xctest[4665:220134] Fatal error: Unexpectedly found nil while unwrapping an Optional value
(lldb) 

### Steps to reproduce

1. Repeat test multiple times 
2. Test throws fatal error

### If possible, minimal yet complete reproducer code (or URL to code)

This fatal error is very rare it only happened once, in order to reproduce it, I had to surround test case with a `while(true)`.

https://gist.github.com/karim-elngr/4fcf887d8739ca2c3b9b19d1cbb30aed

### SwiftNIO version/commit hash

d58fa23e56614c53d0707bb11472fbdeaaddcdb1

### Swift & OS version (output of `swift --version && uname -a`)

Apple Swift version 4.0.3 (swift-4.0.3-RELEASE)
Target: x86_64-apple-macosx10.9
Darwin Karims-MacBook-Pro.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

**Comment by Lukasa** [comment]
Yup, this should probably use a `Promise` to communicate rather than this unsynchronized cross-thread communication.
