### ISSUE TITLE
Compiling NIOFileSystem on Mac Catalyst: No such module 'SystemPackage'

### ISSUE THREAD

**Issue by makaGeorge** [apple/swift-nio#2821]
### Expected behavior
Build with no errors

### Actual behavior
No such module 'SystemPackage'

### Steps to reproduce

1. Add NIOFileSystem to an empty iOS Xcode project. Select the Mac Catalyst platform
2. Build

First noticed when building a project using Vapor, which uses swift-nio. Found out I couldn't build for MacCatalyst so I tried an empty project and the same happens. 

### SwiftNIO version/commit hash
2.69.0

### System & version information
Swift 5.10 and Swift 6 (Xcode 16 beta 4)

**Comment by Lukasa** [comment]
Can you please attach a complete build log?

**Comment by makaGeorge** [comment]
[Build testrv_2024-08-19T09-46-54.txt](https://github.com/user-attachments/files/16657350/Build.testrv_2024-08-19T09-46-54.txt)

Here's the build log. Thanks!

**Comment by Lukasa** [comment]
It seems that `_NIOFileSystem`'s `System` dependency is not being picked up:

```
    Target 'NIOFileSystem' in project 'swift-nio'
        ➜ Explicit dependency on target 'CNIOAtomics' in project 'swift-nio'
        ➜ Explicit dependency on target 'NIOConcurrencyHelpers' in project 'swift-nio'
        ➜ Explicit dependency on target '_NIOBase64' in project 'swift-nio'
        ➜ Explicit dependency on target 'CNIODarwin' in project 'swift-nio'
        ➜ Explicit dependency on target 'CNIOLinux' in project 'swift-nio'
        ➜ Explicit dependency on target 'CNIOWindows' in project 'swift-nio'
        ➜ Explicit dependency on target '_NIODataStructures' in project 'swift-nio'
        ➜ Explicit dependency on target 'NIOCore' in project 'swift-nio'
        ➜ Explicit dependency on target 'NIOPosix' in project 'swift-nio'
        ➜ Explicit dependency on target '_NIOFileSystem' in project 'swift-nio'
        ➜ Explicit dependency on target 'DequeModule' in project 'swift-collections'
        ➜ Explicit dependency on target 'Atomics' in project 'swift-atomics'
```

@glbrntt what is the intention of having [constrained the use of the dependency](https://github.com/apple/swift-nio/blob/a4e0a13c8b8d5b63e81be2b672230a334e78ed44/Package.swift#L27)?

**Comment by Lukasa** [comment]
In the meantime, `macCatalyst` should be added to the list linked above.

**Comment by glbrntt** [comment]
> It seems that `_NIOFileSystem`'s `System` dependency is not being picked up:
> 
> ```
>     Target 'NIOFileSystem' in project 'swift-nio'
>         ➜ Explicit dependency on target 'CNIOAtomics' in project 'swift-nio'
>         ➜ Explicit dependency on target 'NIOConcurrencyHelpers' in project 'swift-nio'
>         ➜ Explicit dependency on target '_NIOBase64' in project 'swift-nio'
>         ➜ Explicit dependency on target 'CNIODarwin' in project 'swift-nio'
>         ➜ Explicit dependency on target 'CNIOLinux' in project 'swift-nio'
>         ➜ Explicit dependency on target 'CNIOWindows' in project 'swift-nio'
>         ➜ Explicit dependency on target '_NIODataStructures' in project 'swift-nio'
>         ➜ Explicit dependency on target 'NIOCore' in project 'swift-nio'
>         ➜ Explicit dependency on target 'NIOPosix' in project 'swift-nio'
>         ➜ Explicit dependency on target '_NIOFileSystem' in project 'swift-nio'
>         ➜ Explicit dependency on target 'DequeModule' in project 'swift-collections'
>         ➜ Explicit dependency on target 'Atomics' in project 'swift-atomics'
> ```
> 
> @glbrntt what is the intention of having [constrained the use of the dependency](https://github.com/apple/swift-nio/blob/a4e0a13c8b8d5b63e81be2b672230a334e78ed44/Package.swift#L27)?

swift-system didn't compile for visionOS so we dropped support for it in file system so that NIO could still be built (https://github.com/apple/swift-nio/commit/53965cc3487f3417226f07b9791940c4b25be76c)

That may well have changed so we might be able to remove the condition entirely.

**Comment by ali-ahsan-ali** [comment]
I am pretty sure https://github.com/apple/swift-nio/pull/2947 closes this issue.
