### ISSUE TITLE
WebSocketFrame should have a nice description

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#2828]
### Expected behavior

`WebSocketFrame.description` outputs something nice.

### Actual behavior

`WebSocketFrame.description` outputs something that's not nice at all

```
WebSocketFrame(_storage: NIOWebSocket.WebSocketFrame.(unknown context at $1084150f8)._Storage, maskKey: nil, firstByte: 138)
```

### Steps to reproduce

- print any `WebSocketFrame`

**Comment by supersonicbyte** [comment]
Made a [PR ](https://github.com/apple/swift-nio/pull/2862) for this.

**Comment by ali-ahsan-ali** [comment]
Can this be closed?
