### ISSUE TITLE
Bogus error messages "BUG in SwiftNIO, unleakable promise leaked"

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#2855]
If a user accidentally shuts down the ELG before actually being done, they often get

```
BUG in SwiftNIO (please report), unleakable promise leaked.:486: Fatal error: leaking promise created at (file: "BUG in SwiftNIO (please report), unleakable promise leaked.", line: 486)
```

which is both

1. wrong (in all cases that I've seen)
2. Misleading

the message should be adjusted to say that it's likely that the EventLoop (which we can actually print!) was likely shut down already (and that it's a bug in NIO if it isn't shut down)

**Comment by weissi** [comment]
CC @Lukasa

**Comment by Lukasa** [comment]
Do we think having this message is pulling its weight at all? We already print a message about shutting down the ELG in most of these cases.

**Comment by weissi** [comment]
> Do we think having this message is pulling its weight at all? We already print a message about shutting down the ELG in most of these cases.

Are you suggesting to delete the message entirely and just making it `preconditionFailure()`? Fine by me, but I'd probably put something like `promise of already-shutdown EventLoop leaked` or smth.

**Comment by Lukasa** [comment]
I don't have a strong opinion either way, honestly.
