### ISSUE TITLE
Make ByteBuffer.description useful and pretty

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#2863]
Right now, `ByteBuffer`'s `description` is ugly and not very useful (doesn't print the bytes). With #2856 being merged, I'm proposing to make `ByteBuffer`'s description the following:

```
[ hex bytes, maximum 64 or something ](length bytes)
```

so `hello world` would be

```
[68656c6c6f20776f726c64](11 bytes)
```

and 256 0 bytes would be

```
[00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000...00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000](256 bytes)
```

the empty string would be `[](0 bytes)`

**Comment by FranzBusch** [comment]
Onboard with this idea. The current description is not really helpful in most cases and I always do a hexDump manually while debugging. We should also change the `debugDescription` of `ByteBuffer` while we are it.

**Comment by weissi** [comment]
> Onboard with this idea. The current description is not really helpful in most cases and I always do a hexDump manually while debugging. We should also change the `debugDescription` of `ByteBuffer` while we are it.

_Normally_ I'd say that we shouldn't change `debugDescription` (because that actually has the bytes and when debugging a ByteBuffer the other stuff is interesting too). _However_, if you do `Array<ByteBuffer>.description` then that will invoke the element's `debugDescription`!?... So yeah, I guess we should just make `.description == .debugDescription`

**Comment by FranzBusch** [comment]
Yes `CustromStringConvertible` and `CustomDebugStringConvertible` are a bit messy. The latter is used by collection types to print their contents. So you should always implement both. At least that's my latest understanding @dnadoba dove into this a bit a while ago.

**Comment by supersonicbyte** [comment]
I can pick this one up also 👋

**Comment by supersonicbyte** [comment]
@weissi since @FranzBusch mentioned [here](https://github.com/apple/swift-nio/pull/2862#discussion_r1741892580 ) that `()` are preferred, should the output of `ByteBuffer's` description be wrapped with `()` or should we stick with `[]`? IMO, `[]` feels more natural for `ByteBuffer`.

**Comment by dnadoba** [comment]
> Normally I'd say that we shouldn't change debugDescription (because that actually has the bytes and when debugging a ByteBuffer the other stuff is interesting too). However, if you do Array<ByteBuffer>.description then that will invoke the element's debugDescription!?... So yeah, I guess we should just make .description == .debugDescription


Good! Then please approve: https://github.com/apple/swift-nio/pull/2495

**Comment by supersonicbyte** [comment]
Here it [is](https://github.com/apple/swift-nio/pull/2864)

**Comment by ali-ahsan-ali** [comment]
Can this be closed?

**Comment by dnadoba** [comment]
Yes, we can close this as we have update the description
