### ISSUE TITLE
Support for Vision

### ISSUE THREAD

**Issue by felswa** [apple/swift-nio#2900]
Hi. In certain places like Source/NIOFileSystem/FileSystem there is:

#if os(macOS) || os(iOS) || os(tvOS) || os(watchOS) || os(Linux) || os(Android)

Can you please add os(visionOS) to this across the project. Thanks.

**Comment by Lukasa** [comment]
@glbrntt we should replace the Apple OSes with `canImport(Darwin)`

**Comment by glbrntt** [comment]
The `#if os(...)` guards in all of the file system code were to work around Swift System not knowing about visionOS (see: https://github.com/apple/swift-nio/pull/2636). 

However, support for visionOS was added in [Swift System 1.3.0](https://github.com/apple/swift-system/releases/tag/1.3.0).

I think the fix here should be to:
1.  remove the top-level `#if os(macOS) || os(iOS) || os(tvOS) || os(watchOS) || os(Linux) || os(Android)` from the file system code, 
2. bump the minimum version of swift-system required to 1.3.0
3. remove the conditional dependency on swift-system from `Package.swift`

**Comment by mpapple-swift** [comment]
In light of commit Issue-2900 - Add VisionOS support #2947, can this be closed or is further testing needed?

**Comment by Lukasa** [comment]
I think we can close this.
