### ISSUE TITLE
Need to upgrade to Swift 6

### ISSUE THREAD

**Issue by Medef** [apple/swift-nio#2903]
### Expected behavior
Successful build using Swift 6

### Actual behavior
Build Failed

### Steps to reproduce

1. Update project and swift-nio using Tuist from Swift 5 -> Swift 6

![image](https://github.com/user-attachments/assets/b262d61d-8bbf-4694-aef8-f5eb6c363f1a)

swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
Target: arm64-apple-macosx14.0

**Comment by Lukasa** [comment]
Can you show the actual compile error? NIO builds fine with the Swift 6 compiler, though not in Swift 6 language mode.

**Comment by Medef** [comment]
> Can you show the actual compile error? NIO builds fine with the Swift 6 compiler, though not in Swift 6 language mode.
<img width="632" alt="Снимок экрана 2024-10-04 в 11 56 29" src="https://github.com/user-attachments/assets/835a60d0-1f69-4172-a812-ffcdddd05d57">

SwiftCompile normal arm64 /Users/<ProjectPath>/Tuist/.build/checkouts/swift-nio/Sources/_NIOBase64/Base64.swift (in target '_NIOBase64' from project 'swift-nio')

There is no exact issue 🤔

**Comment by Medef** [comment]
The error only appears if I add the parameter “SWIFT_VERSION”: “6.0” in Tuist (settings is empty by default). 
```
.debug(
    ...
    settings: ["SWIFT_VERSION": "6.0"],
    ...
)
```

**Comment by Lukasa** [comment]
SwiftNIO does not expect to compile cleanly in Swift 6 language mode at this time. You can still use the Swift 6 compiler, but we require the Swift 5 language mode.
