### ISSUE TITLE
ChannelPipeline.SyncOperations is missing `removeHandler(context:)`

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#2906]
### Expected behavior

I should be able to synchronously remove a `ChannelHandler` by `ChannelHandlerContext`, just like I can with the regular async ops... Sadly, that's not possible :|.

The fix should be pretty straightforward: Adding a `func removeHandler(context: ChannelHandlerContext) throws` to `SyncOperations`.

**Comment by Lukasa** [comment]
Note that while this will still be a sync operation, it must return a future [like its partner does](https://swiftpackageindex.com/apple/swift-nio/main/documentation/niocore/channelpipeline/synchronousoperations/removehandler(_:)).

**Comment by supersonicbyte** [comment]
Made a [PR](https://github.com/apple/swift-nio/pull/2912l) for this!

**Comment by ali-ahsan-ali** [comment]
Can this be closed?
