### ISSUE TITLE
EmbeddedEventLoop/Channel violates Sendable: Store the current thread in `init()` and then assert that we're on that thread

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#2949]
`EmbeddedChannel` & `EmbeddedEventLoop` currently violate `Sendable`. They should store the current thread in `init` and then implement `inEventLoop` with `precondition(self.myThread == Thread.current); return true`.

Otherwise, EmbeddedChannel/EventLoop are just trivially violating the rules.

**Comment by Lukasa** [comment]
Yes, there's no dispute about this. They have always historically broken the rules, and that remains true today.

**Comment by weissi** [comment]
> Yes, there's no dispute about this. They have always historically broken the rules, and that remains true today.

Right, I have no idea why that wasn't already in NIO 1.0... The real selectors (kqueue/epoll/uring) do actually have `myThread` and are asserting it -- despite the fact that they really don't need it, that would be an insane bug if that ever failed :P

**Comment by weissi** [comment]
@Lukasa Do you think this needs to be staged with a `NIO_STRICT` thing? This might break random test suites

**Comment by Lukasa** [comment]
Yeah, I think it does. Environment variable is an option, another option is to just have a static flag on `EmbeddedEventLoop` that you can use to flip the behaviour..

**Comment by weissi** [comment]
> Yeah, I think it does. Environment variable is an option, another option is to just have a static flag on `EmbeddedEventLoop` that you can use to flip the behaviour..

cool, done
