### ISSUE TITLE
NIOFileSystem operations thread warnings

### ISSUE THREAD

**Issue by fortmarek** [apple/swift-nio#2960]
### Expected behavior

Not to see thread warnings when running `NIOFileSystem` methods in a Task in a SwiftUI app.

### Actual behavior

I believe this is very similar to: https://github.com/apple/swift-nio/issues/2686

That specific issue was fixed by: https://github.com/apple/swift-nio/pull/2687

In `NIOFileSystem`, the usage of `DispatchSemaphore` seems to cause the same issues. I created a reproducible repo that you can check out here: https://github.com/fortmarek/NIOFileSystemThreadWarningReproduction

Note you will need to change the path [here](https://github.com/fortmarek/NIOFileSystemThreadWarningReproduction/blob/main/App/Sources/ContentView.swift#L12) to point to an existing file on your local disk. Once you run the app, you will see the following thread warning:
<img width="1483" alt="image" src="https://github.com/user-attachments/assets/28acfbd1-ac62-4b64-9e16-03db6805dfd5">

### Steps to reproduce

1. Clone the [repro repo](https://github.com/fortmarek/NIOFileSystemThreadWarningReproduction)
2. Update the path to point to an existing file
3. Run the macOS app
4. See the thread warning

### If possible, minimal yet complete reproducer code (or URL to code)

```swift
import SwiftUI
import NIOFileSystem

public struct ContentView: View {
    public init() {}

    public var body: some View {
        Text("Hello, World!")
            .padding()
            .onAppear() {
                Task {
                    let handle = try await NIOFileSystem.FileSystem.shared.openFile(forReadingAt: .init("/Users/marekfort/Downloads/devices.json"), options: .init())
                    try await handle.close()
                }
            }
    }
}
```

### SwiftNIO version/commit hash

`2.76.1`

### System & version information

[nio-diagnose.md](https://github.com/user-attachments/files/17600640/nio-diagnose.md)

**Comment by glbrntt** [comment]
Thanks for filing this @fortmarek – I'll try to take a look at this today.
