### ISSUE TITLE
put a websockets test client/server in the allocation tests

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#306]
by having HTTP (and soon a ping/pong --> #305) in the allocation counter tests, we cover a lot of NIO's code in the allocation counting. However we now have web sockets and we should put something simple there just to make sure we don't regress there.

**Comment by weissi** [comment]
@Lukasa you fixed this, right?

**Comment by Lukasa** [comment]
Not quite: I only wrote the server bit. I didn't do a ping-pong.

**Comment by Lukasa** [comment]
@marlimox fixed this in #1210.
