### ISSUE TITLE
more performant uri access

### ISSUE THREAD

**Issue by tanner0101** [apple/swift-nio#342]
Currently the only way to access a request head's uri is via a computed property that converts it to a String. The internal storage however is usually a byte buffer. For vapor's purpose, being able to access the uri bytes without going through String would be a performance win. 

Here is an idea I have on how this could work:

### HTTPURI

```swift
public struct HTTPURI {
    private var storage: URIStorage

    public func withUnsafeBytes<T>(_ closure: (UnsafeRawBufferPointer) -> T) -> T {
        switch storage {
        case .string(let s): /* cString + utf8 codeunit count -> raw buffer pointer */
        case .buffer(let b): /* point to readable byte region */
        }
    }
    
    public var string: String {
        get {       
            switch storage {
            case .string(let s): return s
            case .buffer(var b): return b.readString()
            }
        }
        set {
            storage = .string(newValue)
        }
    }
}

private enum URIStorage {
    case string(String)
    case buffer(ByteBuffer)
}

```

### HTTPRequestHead.rawURI

```swift
public struct HTTPRequestHead: Equatable {
    ...

    public var rawURI: HTTPURI

    public var uri: String {
        get { return rawURI.string }
        set { rawURI.string = newValue }
    }

    ...
}
```

Interested to hear what you guys think!

**Comment by normanmaurer** [comment]
@Lukasa @weissi what are your thoughts on this ? I think there is probably no harm supporting this.

**Comment by helje5** [comment]
I'd like that too, though not for performance. I'm working on a proxy for a telco, and that essentially gets any kind of URI crap you can possibly imagine. For this, it would be nice to be able to pass over the thing as a buffer, as it doesn't always form a valid UTF-8 string.

Technically this is true for any header field too. Though UTF-8 is common today, HTTP headers at least used to be spec'ed as Latin-1, not UTF-8. And you'll find surprisingly many clients still doing this ...

**Comment by tanner0101** [comment]
> we could also hand out a S: Sequence where S.Element == UInt8 in the with
as long as I can get the count of bytes and iterate over them to do comparison (for routing) I will be happy 👍

**Comment by weissi** [comment]
@tanner0101 good point, probably `C: Collection where C.Element == UInt8`

**Comment by normanmaurer** [comment]
@tanner0101 want to take a stab on this ?

**Comment by tanner0101** [comment]
@normanmaurer sure

**Comment by Lukasa** [comment]
I mean, it's not within spec, but people do all kinds of insane nonsense and call it HTTP.

**Comment by helje5** [comment]
@Lukasa probably knows better, my assumption is that there is an addendum RFC which say that those fields must be UTF-8 (probably this one: [RFC 8187](https://tools.ietf.org/html/rfc8187)).
My point is that the original HTTP/1.1 ([RFC 2616](https://www.ietf.org/rfc/rfc2616.txt)) was explicitly spec'ed to not use UTF-8 but ISO-Latin-1. So while this will hopefully die eventually, it'll take a long time until this is a non-issue (there are a lot of companies which simply won't touch their stack, it's not only startups in the world ;-) ). Probably until HTTP/2.0 replaced 1.0.

**Comment by weissi** [comment]
@Lukasa in other words we should support it, right? So maybe we should take @tanner0101’s patch and later introduce a bool flag for HTTPDecoder and configureHTTPServerHandlers whether to eagerly decode the URI as String or not. Then most people should set that to `true` but @helje5’s proxy should set it to `false` and @tanner0101 can do either depending on the outcome of the String benchmarks

**Comment by Lukasa** [comment]
Works for me.

**Comment by helje5** [comment]
i would rather opt for one choice instead of complicating the code. if you really think it should be string, do that.

special purpose stuff can always do the parsing manually, that is not my main point against string. i personally think that string is wrong here for the reasons mentioned.

**Comment by weissi** [comment]
@helje5 I personally think `String` should definitely be a possibility. But given what you posted we can not only do `String` as that would prevent certain use-cases (like your proxy which needs to proxy non compliant stuff) so I don't think we have choice...

**Comment by helje5** [comment]
My point is that certain use-cases, like my proxy (and I'm not even sure whether I can ever redo that in NIO yet, we'll see), do not warrant complicating the code in this way. So if it is just this specific thing, opt for the choice you prefer (or which is more performant). We (or I) could have a NIOHTTP1Raw module if necessary or deemed worthwhile.

I think my main argument against doing the string is the extra allocation for nothing, and that URL processors have to do percent-decoding and path splitting in any case. That is better done on a byte buffer. (which you can still get w/ String, so whatever :-) )

**Comment by weissi** [comment]
this will all be easy in Swift 5 :).

**Comment by weissi** [comment]
URI access should now be really fast :)
