### ISSUE TITLE
Missing error codes in WebSocketErrorCode 

### ISSUE THREAD

**Issue by pushkarnk** [apple/swift-nio#345]
This isn't affecting my work as such for now, but I just noticed that we haven't included codes 1005(`no reason code`),  1006 (`closed abnormally`) and 1015(`TLS handshake error`) in the WebSocketErrorCode enum. Is there any specific reason for that?

See: https://tools.ietf.org/html/rfc6455#section-7.4

**Comment by Lukasa** [comment]
Yeah, they're RFC-excluded. :smile:

1005 is guarded by a MUST NOT, as is 1006, and 1015. The purpose of those codes is to be synthesised up to applications whose primary signaling mechanism is error codes. Generally speaking this doesn't include NIO applications, which have a substantial number of alternative mechanisms for signalling these errors.

The error codes in the `enum` are intended to be the ones that can be serialized/deserialized to the network. As there is no structure that stores a `WebSocketErrorCode` in NIO, this seemed like a reasonable definition: it is not required to store all possible hypothetical error codes.

Does that make sense? Is that compatible with Kitura's uses here?

**Comment by pushkarnk** [comment]
Ah, makes sense. I now looked more closely at the `MUST NOT`. 

Kitura-WebSocket does permit their use, because the `WebSocketCloseReasonCode` enum includes them. Nevertheless, given your reasoning it makes sense to not include them here. I'll close this issue. 

Thanks @Lukasa !
