### ISSUE TITLE
[feature request] pipeline debug logger

### ISSUE THREAD

**Issue by tanner0101** [apple/swift-nio#364]
A generic channel handler for verbose logging of pipeline activity would be really helpful. I'm not sure exactly what that would look like, but opening this issue up for discussion. I think at a minimum the logger should show all incoming and outgoing `NIOAny`s.

**Comment by Lukasa** [comment]
Good idea! I think this may be better handled by a special debug-only mode for channel pipelines that updates the contexts to do the logging. The context is intentionally opaque to handlers, and it’d be good for it to stay that way.

**Comment by normanmaurer** [comment]
Not 100 % what you are looking for but we provide some sort of logging handler for netty that can be used for something like this:

https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/logging/LoggingHandler.java

Maybe this can give some inspiration

**Comment by tanner0101** [comment]
@normanmaurer as long as it prints a readable form of the data getting passed between handlers I would be happy. I think a big advantage to having something like this built into NIO (with an easy way to enable it) is that it provides a consistent, reliable method for developers to share and parse this debug info. I imagine ones' eye could become fairly well trained to reading them eventually.

**Comment by helje5** [comment]
A log would be a great starting point, but an actual visualisation of the message flow (an app or an Instrument thing showing this) would be really cool. In Node you get this kind of thing for free w/ the event listeners. In NIO I think one would need to (optionally) replace the pipeline driver with a debug variant offering the additional listener delegate (which could then log or do fancier stuff).

**Comment by weissi** [comment]
done in swift-nio-extras
