### ISSUE TITLE
NonBlockingFileIO should be extended with write methods

### ISSUE THREAD

**Issue by rafiki270** [apple/swift-nio#406]
Could we get better file streaming support please?

CC: @Lukasa

**Comment by Lukasa** [comment]
This specifically covers the fact that there is no way to do non-blocking *writes* with the `NonBlockingFileIO` method.

This would be a good external contributor task if none of the core team gets to it: following the example of `read` is the place to start.

**Comment by abhishek7** [comment]
@Lukasa I'm happy to give this a try if this is still outstanding.

**Comment by Lukasa** [comment]
I believe it is.
