### ISSUE TITLE
Shouldn't this comment read a successful event loop future?

### ISSUE THREAD

**Issue by Andrewangeta** [apple/swift-nio#409]
Xcode hint confused me saying it was a failed future being returned. A simple update will help 👍 
https://github.com/apple/swift-nio/blob/e029edef2a70422759a08986c0a781ed01f1b8cd/Sources/NIO/EventLoop.swift#L200-L213

**Comment by Lukasa** [comment]
Yes it should! Want to open a PR with a fix?

**Comment by Andrewangeta** [comment]
@Lukasa https://github.com/apple/swift-nio/pull/412

**Comment by weissi** [comment]
fixed when #412 was merged
