### ISSUE TITLE
HTTPHeaders.isKeepAlive(...) does only match the first value.

### ISSUE THREAD

**Issue by normanmaurer** [apple/swift-nio#410]
HTTPHeader.isKeepAlive(...) must check all header values,  not only the first one:

https://github.com/apple/swift-nio/blob/master/Sources/NIOHTTP1/HTTPTypes.swift#L302

**Comment by fadi-botros** [comment]
This is just an initial solution, built on the hypothesis that using String api may be somewhat slow, so made the comma separator and the extractor low-level. Unit tests included for those buffer utilities.
If this was an approved approach, we should cache the `keep-alive` and `close` conversion to bytes

**Comment by fadi-botros** [comment]
You could check the pull request again, there is a new commit
#414 

@weissi
