### ISSUE TITLE
New assertion failure seen with 1.7.0

### ISSUE THREAD

**Issue by pushkarnk** [apple/swift-nio#417]
In Kitura-NIO, we have a test where we try to bind two servers to the same port (without setting `SO_REUSEPORT` to 1) and make sure the second bind fails! With 1.7.0, I see a new assertion failure while trying to bind the second server.

Here's the repro test:

```
import NIO

let group = MultiThreadedEventLoopGroup(numThreads: System.coreCount)
defer {
    try! group.syncShutdownGracefully()
}

let serverChannel = try! ServerBootstrap(group: group)
    .bind(host: "127.0.0.1", port: 0)
    .wait()

let port = Int(serverChannel.localAddress!.port!)
do {
    _ = try ServerBootstrap(group: group)
        .bind(host: "127.0.0.1", port: port)
        .wait()
} catch let error {
    print(error)
}
```

Output with 1.6.1:
`bind(descriptor:ptr:bytes:) failed: Address already in use (errno: 98)`

Output with 1.7.0:
`Assertion failed: leak of open Channel: file /root/pushkar/bugs/.build/checkouts/swift-nio-3867413520604177634/Sources/NIO/BaseSocketChannel.swift, line 399`

**Comment by Lukasa** [comment]
Huh. @weissi has been looking at this area most recently, and we have two PRs open that should entirely resolve this error: #415 and #413. Hopefully @weissi will be able to diagnose why exactly the channel is leaking before we land #415, which would prevent it leaking altogether.

**Comment by weissi** [comment]
Thanks very much @pushkarnk for your report! Indeed, I’ll finish my PRs on Monday and then we should be all good here.

**Comment by weissi** [comment]
@pushkarnk yes, so #413 fixes that but I added your specific repro as a test case too. thank you!

**Comment by pushkarnk** [comment]
Thanks for the fix, @weissi !
