### ISSUE TITLE
Add method to `EventLoop` that is to `EventLoop.submit` as `Future.then` is to `Future.map`.

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio#426]
Currently `EventLoop.submit` is defined like this: `func submit<T>(_ task: @escaping () throws -> T) -> EventLoopFuture<T>`.

The problem here is that `T` may be `EventLoopFuture<U>`. In this instance, you end up with `EventLoopFuture<EventLoopFuture<U>>` as the return type of `submit`, and double futures are annoying to work with.

It would be very helpful to have a method that can deal with this. To add this in a backward-compatible way, we could add the method to the `EventLoop` protocol, and also provide an extension with a default implementation that just does `.then { $0 }` on the returned double-future from the default method.

**Comment by Lukasa** [comment]
Whoever does this should also clean up the workarounds from #424.

**Comment by karim-elngr** [comment]
Any name suggestions for the new function?

**Comment by weissi** [comment]
@karim-elngr really sorry for the _huge_ delay, this just slipped through. We just talked about it and `flatSubmit` (similar to `flatMap` and `map`) sounds like the best name to us.

**Comment by weissi** [comment]
fixed in #1174
