### ISSUE TITLE
flaky testPortNumbers

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#429]
on macOS (virtualised) this test seems to fail every now and then 
```
13:03:15 - Test Case '-[NIOTests.EchoServerClientTest testPortNumbers]' started.
13:03:15 - <unknown>:0: error: -[NIOTests.EchoServerClientTest testPortNumbers] : failed: caught error: The operation couldn’t be completed. (NIO.ChannelError error 0.)
13:03:15 - Test Case '-[NIOTests.EchoServerClientTest testPortNumbers]' failed (10.016 seconds).
```

NIO.ChannelError error 0 should be this guy

```
public enum ChannelError: Error {
    /// Tried to connect on a `Channel` that is already connecting.
    case connectPending
```

so `connectPending` 🤔

**Comment by Lukasa** [comment]
Given the output, which indicates this is an uncaught error, this can only happen on this line:

https://github.com/apple/swift-nio/blob/80363d9d8c1c572d228350ea87132bfa49c8ca03/Tests/NIOTests/EchoServerClientTest.swift#L770-L771

That's the only line with a `try` not surrounded by a `catch` or an `XCTAssertNoThrow`.

**Comment by Lukasa** [comment]
However, `connectPending` is simply not a possible error there, so I just don't believe that that's the error we're seeing.

**Comment by weissi** [comment]
@Lukasa yes I was wondering if that might be that problem where the `Error` to `NSError` bridging loses the error number. But last time I checked it then always went for code `1` not `0`...
But we should keep in mind that might be the wrong error code.

**Comment by Lukasa** [comment]
I'm running this test in a `while true` inside Xcode to see if I can trigger the failure and so far it's passing.

**Comment by weissi** [comment]
@Lukasa you might want to change the `try` to `try!` just to be sure XCTest isn't holding the errors up until the test "finishes"

**Comment by Lukasa** [comment]
@weissi It can't, it's an un-wrapped `try` so it'll throw all the way out of the test. The test should fail immediately. I've been running it for 30 minutes now and still no failure locally.

**Comment by normanmaurer** [comment]
@Lukasa famous last words 🤣 "works on my machine"

**Comment by normanmaurer** [comment]
@Lukasa was just joking ... I am also sure there must be a bug. Bullying @weissi sounds good to me :)

**Comment by weissi** [comment]
better diagnostics for this in #512

**Comment by weissi** [comment]
No seen in ages
