### ISSUE TITLE
numOfThreads/numberOfThreads inconsistency

### ISSUE THREAD

**Issue by gmosx** [apple/swift-nio#432]
### Expected behavior

```
let group = MultiThreadedEventLoopGroup(threadCount: System.coreCount)
let threadPool = BlockingIOThreadPool(threadCount: 6)
```

### Actual behavior

```
let group = MultiThreadedEventLoopGroup(numThreads: System.coreCount)
let threadPool = BlockingIOThreadPool(numberOfThreads: 6)
```

Please notice the inconsistency between `numThreads` and `numberThreads`. Also, it would be better to use the `count` name used in the standard library.

**Comment by normanmaurer** [comment]
@Lukasa @weissi WDYT... I am also ok with `count` but I think `numberThreads` or `numThreads` are a bit more descriptive... At least we should make it consistent :)

**Comment by weissi** [comment]
I think that's a fair enough issue and I think we should fix `numThreads` at least. Whether the parameters should be `threadCount:` or `numberOfThreads:` or something can be bikeshed I don't really mind

**Comment by gmosx** [comment]
I don't mind `numberOfThreads` but I think `numThreads` should be renamed.
