### ISSUE TITLE
Suggestion: Form data handler and JSON Handler

### ISSUE THREAD

**Issue by fadi-botros** [apple/swift-nio#433]
Suggestion: We have HTTP header parsing utilities, so why not also HTTP body parsers ?
We could make it with an event driven way, like in multipart form data for example: when a full field header is encountered, it would be passed through the channel pipeline, then its value should be sent as chunked buffers. Also in JSON, each token should be passed to the channel pipeline.

**Comment by normanmaurer** [comment]
Honestly I think its a bit out of scope for swift-nio directly but could just be something that is provided as an "extension" by the community. @Lukasa @weissi let me know what you think

**Comment by Lukasa** [comment]
Agreed, I think this is out of scope for NIO. The core implementation will contain header parsers for whatever the HTTP implementation itself needs to understand, but shouldn’t contain more than that. 

In general, modularity is good: we should let the community implement these things without running them all through our release and review schedules.

**Comment by weissi** [comment]
agreed.
