### ISSUE TITLE
HTTPRequestHead.uri is not really a URI

### ISSUE THREAD

**Issue by gmosx** [apple/swift-nio#446]
### Expected behavior

`HTTPRequestHead.uri` should return the full request URI.

### Actual behavior

`HTTPRequestHead.uri` returns just the path component of the URI.

**Comment by Lukasa** [comment]
> HTTPRequestHead.uri is not really a URI

Sure it is. 😀

What it is not guaranteed to be is a *fully-qualified* URI, but that’s ok, for a few reasons. 

1. It is not generally possible for a HTTP server to reconstruct the absolute request URI requested by the client. Scheme and host are not necessarily transmitted losslesssly. 
2. `HTTPRequestHead.uri` represents a specific thing. Specifically, it represents one of the three components of what RFC 7230 calls the “request line”. Those three components are the *method*, the *HTTP version*, and the *request-target*, also sometimes called the *request URI*. `.uri` is intended to accurately reproduce exactly the content of that field. 

To understand this decision, bear in mind that NIO’s HTTP stack is not intended to provide high level tools: it deliberately exposes as many protocol details as possible. This allows you to support as much of this protocol as possible.

**Comment by helje5** [comment]
From [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html):

> Request-URI    = "*" | absoluteURI | abs_path | authority

So in a way you are right, it is "not really a URI", it is a HTTP Request-URI. Including stuff like `OPTIONS *` or `CONNECT blub:443`.

I don't know, maybe that should be an enum, but I guess it is not worth it at this level and rarely useful.

**Comment by Lukasa** [comment]
I'm open to considering changing the name to `.target` in a future 2.0 release, but I don't think there's any need to change the behaviour of the property as it currently stands. :smile:

**Comment by helje5** [comment]
One needs to be careful not to break this, e.g. those are different things obviously:

    GET http://facebook.com/gdrp.html HTTP/1.1
    Host: amp.google:443

and

    GET /gdrp.html HTTP/1.1
    Host: facebook.com:443

I wouldn't call it `target`, `uri` is fine, maybe `requestURI` would be better. The only thing I consider wrong in the current API is that this is a String (i.e. something which already has a specific encoding applied, which is wrong here [and most other places])

**Comment by gmosx** [comment]
Hmm, seems `path` is not a good name either. I guess, to be fully aligned with the latest RFC, we could use `target` but I think uri is good enough.
