### ISSUE TITLE
Consider adding HTTP Cookie helper methods to HTTPHeaders

### ISSUE THREAD

**Issue by gmosx** [apple/swift-nio#448]
### Expected behavior

It would be useful if the `HTTPHeaders` struct provided a couple of Cookie-related helpers, e.g. something like:

```
headers.cookie(named: "session")
headers.addCookie(name: "session", value: "2131241241", httpOnly: true)
```

what do you think?

**Comment by Lukasa** [comment]
I think I’m -1 on this, at least in NIO core. 

The protocol level of HTTP doesn’t know anything about cookies. That means that cookie knowledge is unnecessary for NIO itself. Given that we want NIO to be a low-level tool, I think we should leave utilities like this up to the community.

**Comment by normanmaurer** [comment]
@Lukasa I agree... I think this should be done in an "extension project"

**Comment by gmosx** [comment]
Sounds reasonable.

I will add the extension to my little 'experiment': https://github.com/reizu/swift-nitro
