### ISSUE TITLE
Invalid assertion in BaseSocketChannel.swift

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio#452]
`BaseSocketChannel` currently contains the following assertion in `readEOF`:

https://github.com/apple/swift-nio/blob/25c6cd5982ae0d83092b2bb3a6e160bdc450c72e/Sources/NIO/BaseSocketChannel.swift#L866-L869

This assertion essentially states that we only receive `readEOF` if we are active, or if we are not in any of the registered states (e.g. we are already closed). The reason for this is that we do delayed registration: we don't register for anything (`readEOF` included) until we are ready to begin connecting, and if we're ready to begin connecting we expect to either become active (when the connection succeeds) or have the connection be reset (which, while it does technically trigger `readEOF`, will actually go into the `reset` branch instead and never call `readEOF`).

However, this assertion is a bit overzealous. In particular, it can encounter problems with this specific flow:

```
   NIO               PEER
    +                  +
    |       SYN        |
    |  +------------>  |
    |                  |
    |     SYN/ACK      |
    |  <------------+  |
    |                  |
    |       ACK        |
    |  +------------>  |
    |                  |
(1) |       FIN        |
    |  <------------+  |
(2) |                  |
    +                  +

```

In this instance, the connection is not reset at any stage, so we will not get a `reset` trigger. What we *do* get depends on the platform (which is expected), but frustratingly also on the *timing*.

For Linux, because `epoll` is instantaneous, we will always get all the events for an FD at once. That means that if we `epoll` at `(1)`, we will get only writable, whereas if we do it at `(2)` we will get both writable and readEOF, which will be processed in that order.

For Darwin, this is trickier, because `kqueue` is a temporal protocol. Essentially, kqueue maintains a queue (natch) of events that occurred on the fd. These queues are in order, except with one key constraint: the event cannot be put into the `kqueue` until you've asked for it.

That means that Darwin has an additional variable other than "when did we call `kevent` to ask for events", which is: "when did we call `kevent` to ask the kernel to tell us about events"? Specifically, if we don't register for writable until `(2)`, the `readEOF` event will already be in the `kqueue` before the kernel knows we care about writability. That will lead to the `kqueue` telling us about `readEOF` *before* it tells us about writable, which is not what our code expects.

We could work around this by making kqueue more like epoll, but at the cost of maintaining a bunch of state to essentially "flatten" the event list down. That's probably not worthwhile: instead, we should just allow this series of events to occur, as it's totally safe.

I'm going to split the fix into two parts. First we're just going to fix it, because the fix is trivial: we're just going to widen the assertion. Then I'm going to write tests for it. The tests are complex because this relies on a window condition, which means that I need to finally make the investment we wanted to do for a while: write and allow a dummy selector that we can use to drive real channels.

**Comment by weissi** [comment]
fixed by #453
