### ISSUE TITLE
Could you add an example of handling an HTTP POST request?

### ISSUE THREAD

**Issue by gmosx** [apple/swift-nio#457]
### Expected behavior

An example of handling an HTTP POST request would be really useful.

**Comment by weissi** [comment]
there's a few of those:

- `handleEcho` in the example NIOHTTP1Server which streams (or if called with `balloonInMemory: true` baloons it into memory) the request body back into the response body: https://github.com/apple/swift-nio/blob/master/Sources/NIOHTTP1Server/main.swift#L139-L168
- `handleInfo` which counts the number of bytes in the HTTP body: https://github.com/apple/swift-nio/blob/master/Sources/NIOHTTP1Server/main.swift#L106-L133
- `handleEcho`: https://github.com/apple/swift-nio/blob/master/Sources/NIOHTTP1Server/main.swift#L139-L168

**Comment by weissi** [comment]
@gmosx or did I misunderstand what you wanted? Please feel free to reopen with more details.
