### ISSUE TITLE
Can a ChannelHandler trigger an early exit from a ChannelPipeline

### ISSUE THREAD

**Issue by gmosx** [apple/swift-nio#458]
### Expected behavior

I would like to have an AuthenticationHandler as a first stage (ChannelnboundHandler) in a ChannelPipeline. If the authentication check fails I would like to return an error response and skip the evaluation of the remaining handlers in the pipeline.

I would be nice if the documentation could be amended with some example for such use cases.

**Comment by Lukasa** [comment]
As this is more of a question than anything else, I think [the forum question](https://forums.swift.org/t/can-a-channelhandler-trigger-an-early-exit-from-a-channelpipeline/13102) covers it.

**Comment by gmosx** [comment]
Added it here because last time I was asked to file issues for documentation improvements.

**Comment by Lukasa** [comment]
Sure, but the API docs do already mention this on the various protocol methods. The question is only whether we need a specific example to call this out in narrative documentation, which I don’t think we do to be honest.

**Comment by helje5** [comment]
I guess a higher level overview with some real world examples would be nice. But I guess we have to wait until @normanmaurer writes the Setty 2.0 book ;-)

**Comment by normanmaurer** [comment]
@helje5 lol... I am almost sure I will never ever write a book again ;)

**Comment by ianpartridge** [comment]
Everyone I've ever spoken to who has written a technical book has told me that, @normanmaurer 😉
