### ISSUE TITLE
ByteBuffer doesn't follow Swift naming conventions

### ISSUE THREAD

**Issue by gmosx** [apple/swift-nio#459]
### Expected behavior

```
byteBuffer.getData(at: byteBuffer.readerIndex, count: byteBuffer.readableBytesCount)
```

### Actual behavior

```
byteBuffer.getData(at: byteBuffer.readerIndex, length: byteBuffer.readableBytes)
```

I believe `readableBytes` is especially confusing (I would expect it returns an array/collection of bytes)

**Comment by weissi** [comment]
@normanmaurer / @Lukasa switching `length` to `count`?

**Comment by Lukasa** [comment]
Uh....I'm probably -0 on this?

In this case the code churn involved here is *high*: anyone who has written any code at all that touches `ByteBuffer` is going to need to make changes. If we're going to do this we should deprecate those properties and methods today and ship the deprecation in 1.12 so that people have a migration path, because otherwise this is going to be super annoying.

**Comment by helje5** [comment]
Maybe that should be a `Range`, not "(at:count:)`?

**Comment by weissi** [comment]
@helje5 problem is that range is _super annoying_ with range and count, you'd need to do

    start ..< start + count

so you repeat `start`. Never understood why there's not an operator for not needing to repeat `start`.

CC @airspeedswift / @moiseev

**Comment by helje5** [comment]
You have `.lowerBound` and `.upperBound`, that is not good enough?

**Comment by weissi** [comment]
> You have `.lowerBound` and `.upperBound`, that is not good enough?

how does that help if I want to construct a thing that goes on for `y` elements, starting at index `x`, then I need to do `x ..< x + y` but I don't want to repeat `x`

**Comment by helje5** [comment]
`NSMakeRange` then? ;-) No just kidding, good point. I would have expected that `Range` has a "distance" variant (and maybe it has? 🤔)

**Comment by weissi** [comment]
talked to the stdlib folks and they suggested leaving it as `length:` because we're talking a continuous amount of bytes here. `count` would be misleading because when we do `readString(count: 7)`, we're not reading 7 strings off but rather a byte range of length 7 that gets turned into one String
