### ISSUE TITLE
Line-delimited frame decoder

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio#473]
It may be helpful to have a generic `ChannelInboundHandler` that can decode line-delimited protocols. That is, a protocol that looks like this:

```
message
new message
other new message
```

This should be split into three separate messages, each containing a `ByteBuffer` that contains only the line (stripped of line endings).

**Comment by normanmaurer** [comment]
See https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/DelimiterBasedFrameDecoder.java and https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/LineBasedFrameDecoder.java

**Comment by weissi** [comment]
implemented in [`swift-nio-extras`](https://github.com/apple/swift-nio-extras/blob/master/Sources/NIOExtras/LineBasedFrameDecoder.swift)
