### ISSUE TITLE
Length-delimited frame encoder

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio#476]
A pair with #474: a `ChannelOutboundHandler` that receives `ByteBuffer` messages and sends a small `ByteBuffer` before them containing the length of that buffer in the appropriate fixed width integer form.

**Comment by normanmaurer** [comment]
See https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/LengthFieldPrepender.java

**Comment by tigerpixel** [comment]
Hi. I was thinking about picking this up. It seems like it should go next to the LengthFieldBasedFrameDecoder in apple/swift-nio-extras#17. It that correct or would you like me to send it to somewhere in this repository?

**Comment by Lukasa** [comment]
Sounds right to me

**Comment by weissi** [comment]
@tigerpixel Correct, that's where I'd put it too.

**Comment by weissi** [comment]
that's https://github.com/apple/swift-nio-extras/pull/19
