### ISSUE TITLE
Add documentation to generate an xcodeproj

### ISSUE THREAD

**Issue by BasThomas** [apple/swift-nio#477]
### Expected behavior
Add instructions on how to generate an `xcodeproj` to work on SwiftNIO from Xcode.

### Actual behavior
There is no documentation I can find on how to do this.

### How to proceed
We can generate an `xcodeproj` with SwiftPM:

```bash
$ swift package generate-xcodeproj
```

We probably want to add this in the [Getting Started](https://github.com/apple/swift-nio#getting-started) part of the README.

**Comment by Lukasa** [comment]
Resolved by #478.
