### ISSUE TITLE
Should unhandled userOutboundEvents have their promises succeed or fail?

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio#487]
Currently `BaseSocketChannel` will succeed the promise for a `userOutboundEvent` that is not handled by the pipeline:

https://github.com/apple/swift-nio/blob/29d6bf029ae12e5bf7b289ce596cc50f66d041d1/Sources/NIO/BaseSocketChannel.swift#L812-L814

I wanted to ask whether that was actually a sensible behaviour. My gut says that we probably should *fail* events that make it that far, on the grounds that whatever outcome you were hoping to get you didn't successfully get it. Maybe with `ChannelError.unsupportedOperation`?

**Comment by normanmaurer** [comment]
Yeah I think we should fail... Not sure if `unsupportedOperation` is a good error tho.

**Comment by weissi** [comment]
I also think we should fail em

**Comment by weissi** [comment]
add a new error to report this
