### ISSUE TITLE
channel.write(buffer).wait() is locking up a thread

### ISSUE THREAD

**Issue by woodcrust** [apple/swift-nio#489]
### Expected behavior
I expected that my code is not going to be frozen when I am trying to call wait() on the write method

### Actual behavior
wait method called from write method is locking up the thread

Is that a bug or a my mistake ?

### Steps to reproduce
```swift
let bootstrap = ClientBootstrap(group: group)
        .channelOption(ChannelOptions.socket(SocketOptionLevel(SOL_SOCKET), SO_REUSEADDR), value: 1)
        .channelInitializer { channel in
                return  channel.pipeline.add(handler: ChatHandler())
        }

channel.write(buffer).wait()

it freezes ...
```
and for example the print method inside this callback function of _whenComplete method inside the wait method can not be call

file EventLoopFuture.swift
```swift
_whenComplete() { () -> CallbackList in
            
            print(" COMPLETE ")
            
            lock.lock()
            v = self.value
            lock.unlock(withValue: 1)
            return CallbackList()
        }
```

if I am calling the wait method from the writeAndFlush(buffer) method its works good

### If possible, minimal yet complete reproducer code (or URL to code)

Works good
```swift
let future = channel.writeAndFlush(buffer).then() {(Void) -> EventLoopFuture<()> in
    print("write and flush whenSuccess")
    return channel.eventLoop.newSucceededFuture(result: ())
    }
    .thenIfError() {error in
        print("write  and flush error \(error)")
        return channel.eventLoop.newFailedFuture(error: error)
}

try? future.wait()
// or just
channel.writeAndFlush(buffer).wait()
```

Thread is getting locked
```swift
let future = channel.write(buffer).then() {(Void) -> EventLoopFuture<()> in
        print("write whenSuccess")
        return channel.eventLoop.newSucceededFuture(result: ())
    }
    .thenIfError() {error in
        print("write error \(error)")
        return channel.eventLoop.newFailedFuture(error: error)
    }

try? future.wait()
// or just
channel.write(buffer).wait() 
```

### SwiftNIO version/commit hash

1.8.0

### Swift & OS version (output of `swift --version && uname -a`)

Apple Swift version 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)
Target: x86_64-apple-darwin17.6.0
Darwin Olehs-MacBook-Pro.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

**Comment by Lukasa** [comment]
That’s your mistake. [As stated in the documentation](https://apple.github.io/swift-nio/docs/current/NIO/Classes/EventLoopFuture.html#/s:3NIO15EventLoopFutureC4waitxyKF), `wait` blocks the thread until the `Future`resolves. 

Unfortunately there is currently no stack-switching model for Swift, which means that the way you need to do concurrent programming is with callbacks.

**Comment by woodcrust** [comment]
I understand that `wait()` will to block a thread. I do not understand why `writeAndFlush(buffer)` method can be resolved in the future, but `write(buffer)` will never be resolved. 
### This code blocks a thread forever
```swift
var line = "string"
var buffer = channel2.allocator.buffer(capacity: line.utf8.count)
buffer.write(string: line)

channel.write(buffer).wait()
```

Please, tell me why?

**Comment by helje5** [comment]
The `write` promise will only resolve when the data is actually written to the socket. Calling `write` only *enqueues* the buffer for writing. The actual writing happens, when you call `flush` (and even that asynchronously).

So in your example you enqueue a buffer and then wait for it to be written out. But that will never happen, because the channel is never flushed. Because *you* block the thread.

**Comment by babakhanov** [comment]
@helje5 how can I call `flush` after `write` if `write` blocks thread forever?

**Comment by Lukasa** [comment]
> (someone correct me if I'm wrong ;-) )

You are right.

@babakhanov Like this:

```swift
var line = "string"
var buffer = channel2.allocator.buffer(capacity: line.utf8.count)
buffer.write(string: line)

let writeFuture = channel.write(buffer)
channel.flush()
writeFuture.wait()
```

Of course, in this simple case where you want to do one write and then immediately flush, just use `writeAndFlush`: that's what it's there for. If you're doing multiple, just save the future off and wait on it *after* the flush.

**Comment by woodcrust** [comment]
@Lukasa now I understand how it works, thanks you very much
