### ISSUE TITLE
No console output when run NIOHTTP1Server inside docker container

### ISSUE THREAD

**Issue by gavrilaf** [apple/swift-nio#490]
### Context

While testing my project written with SwiftNIO, I noticed that no console logs when I run server inside docker container. I've tried to run test NIOHTTP1Server and got the same result.

### Expected behavior

NIOHTTP1Server should print debug messages to the console when running inside docker container.

### Actual behavior

Console after run NIOHTTP1Server through docker-compose

```
http_1               | Compile Swift Module 'NIOHTTP1' (8 sources)
http_1               | Compile Swift Module 'NIOHTTP1Server' (1 sources)
http_1               | Linking ./.build/x86_64-unknown-linux/debug/NIOHTTP1Server
```

Console after run NIOHttpServer throuhg '''swift run NIOHTTP1Server'''

```
Compile Swift Module 'NIOHTTP1' (8 sources)
Compile Swift Module 'NIOHTTP1Server' (1 sources)
Linking ./.build/x86_64-apple-macosx10.10/debug/NIOHTTP1Server
htdocs = /dev/null/
Server started and listening on [IPv6]::1:8888, htdocs path /dev/null/
```

No console output when run NIOHTTP1Server inside docker container (but NIOHTTP1Server works, I've checked it).

### Steps to reproduce

1. `git clone https://github.com/apple/swift-nio.git`
2. `docker-compose -f docker/docker-compose.yaml up http`
3. See console output

### SwiftNIO version/commit hash

master,  29d6bf0

### Swift & OS version (output of `swift --version && uname -a`)

```
Apple Swift version 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)
Target: x86_64-apple-darwin17.6.0
Darwin Eugens-MacBook-Pro.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
```

**Comment by Lukasa** [comment]
Is there anything in `docker logs` for that container?

**Comment by gavrilaf** [comment]
The same with console output, nothing new

Eugens-MacBook-Pro:swift-nio eugenf$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
c81a5923307f        swift-nio:default   "/bin/bash -cl 'swif…"   39 seconds ago      Up 50 seconds       0.0.0.0:8888->8888/tcp   docker_http_1
Eugens-MacBook-Pro:swift-nio eugenf$ docker logs c81a5923307f
mesg: ttyname failed: Inappropriate ioctl for device
Compile CNIOSHA1 c_nio_sha1.c
Compile CNIOAtomics src/c-atomics.c
Compile CNIOLinux shim.c
Compile CNIODarwin shim.c
Compile CNIOZlib empty.c
Compile CNIOHTTPParser c_nio_http_parser.c
Compile Swift Module 'NIOPriorityQueue' (2 sources)
Compile Swift Module 'NIOConcurrencyHelpers' (2 sources)
Compile Swift Module 'NIO' (52 sources)
Compile Swift Module 'NIOHTTP1' (8 sources)
Compile Swift Module 'NIOHTTP1Server' (1 sources)
Linking ./.build/x86_64-unknown-linux/debug/NIOHTTP1Server
Eugens-MacBook-Pro:swift-nio eugenf$

**Comment by gavrilaf** [comment]
But.. If I comment line 

// This will never unblock as we don't close the ServerChannel
// try channel.closeFuture.wait()

Server didn't work in this case of course.
But I got output:

http_1               | Linking ./.build/x86_64-unknown-linux/debug/NIOHTTP1Server
http_1               | htdocs = /dev/null/
http_1               | Server started and listening on [IPv4]0.0.0.0:8888, htdocs path /dev/null/
http_1               | Server closed
docker_http_1 exited with code 0

**Comment by Lukasa** [comment]
Oh interesting, good catch. I wonder if this is a buffering issue.

**Comment by Lukasa** [comment]
This is definitely a buffering issue. Adding `fflush(nil)` on the line after the print statement resolves the issue entirely. This is presumably because bash no longer believes it's attached to a tty, so stops being line-buffered and becomes fixed-size buffered instead. This is easily resolved by adding `tty: true` to the `docker-compose.yaml` for `http`.

If you feel like making a PR, it'd be great to see that added.

**Comment by gavrilaf** [comment]
Cool, thank you )
I'll check and make PR.
