### ISSUE TITLE
Project is doomed because Swift has no memory model or guarantees

### ISSUE THREAD

**Issue by virl** [apple/swift-nio#492]
Swift, compared to Java and Netty, have no well-defined memory model and memory guarantees (like Java JMM).

For example: https://bugs.swift.org/browse/SR-8101

That means that multithreading networking servers such as this project can never reach Java+Netty levels of resilience and reliability.

**Comment by helje5** [comment]
Given that the far majority of the servers on the Interwebs are written in C (Apache, NGINX, OpenResty, Cyrus, Dovecot, Postfix, Samba, Exchange, PostgreSQL, MySQL, Redis, etc etc etc etc etc) I guess the project will be fine wrt that specific issue.
And given that it uses no GC, you'll have less OOM crashes. (is it April 1st already again?)

**Comment by virl** [comment]
@helje5 Erm, so you want this project to have the same reliability/security as projects written in C? I guess it's too bad for the project then, especially if it positions itself as Netty alternative.

> And given that it uses no GC, you'll have less OOM crashes and servicing hiccups.

GC can't lead to OOM, excessive memory usage is. Because OutOfMemoryException in Java is always thrown after GC is free all possible memory.

**Comment by BasThomas** [comment]
There will be [a memory ownership model](https://github.com/apple/swift-evolution#primary-focus-abi-stability) in the future though :)

**Comment by virl** [comment]
@BasThomas This ownership model doesn't solve these multithreading issues, it just implements Rust-style reference counting.

**Comment by Lukasa** [comment]
@virl Doomed? Cool, that takes the pressure off then. 👍

More seriously, it’s without question the case that Swift’s absence of a memory model limits us, but such a problem is solvable in time. The different memory safety rules to Java are just that: different. There are benefits to each approach, just as there are costs.

It’s a big wide world, and the programming language ecosystem is not “zero sum”. Java doesn’t have to lose for Swift to win, and NIO doesn’t succeed by supplanting Netty. Netty will exist for those who want what Java and the JVM gives them: we’ll exist for those who want what Swift gives them. Everyone gets what they want, we can all go home happy.

In future, while I appreciate your concerns, I’d like to encourage you to use this issue tracker for *actionable*  feedback. To discourage the use of the issue tracker for off-topic discussion I’m closing and locking this issue. I invite the interested parties to continue the discussion on forums.swift.org, where it belongs.
