### ISSUE TITLE
Iterating over event loops of an EventLoopGroup

### ISSUE THREAD

**Issue by pushkarnk** [apple/swift-nio#497]
Can we have an iterator over the event loops of an  event loop group? 

This came up during the implementation of a perf improvement suggestion I received on `Kitura-NIO`. We'd want to initialise a `ThreadSpecificVariable` on every event loop of the event group, update it periodically (using a repeating `Scheduled` task) and read from it when needed. The `on every event loop of the event loop group` part would be better implemented if we had an iterator over the event loops. We do have `EventLoopGroup.next()` but some extra logic needs to be added around it to simulate an iterator.

Right now, I can't think of any side-effects of having an iterator over event loops. But I'll be glad to understand them, if there are any!

**Comment by Lukasa** [comment]
This is a nice idea. I’d be fine with this.

**Comment by normanmaurer** [comment]
@pushkarnk @Lukasa sounds like a good idea... For what it worth we also have the same in Netty (at least something similar).

**Comment by pushkarnk** [comment]
Thanks @Lukasa and @normanmaurer !

I tried to implement the iterator on `EventLoopGroup` but we ran into the `Protocol EventLoopGroup can only be used as a generic constraint`error. Working around this will be a big change, I reckon.
Also, with only `EventLoopGroup.next()` which actually provides an infinite stream of `EventLoop`s, it doesn't seem possible to write a stopping condition. `EventLoop` isn't `Equatable` too. 

Implementing an iterator only over `MultiThreadedEventLoopGroup` seems quite simple, but if we have newer implementations of `EventLoopGroup` we'll have to redundantly conform them to Sequence. Here it is: https://github.com/pushkarnk/swift-nio/commit/6ebd7f0e218349b1f05dcffd17ef96c27da6a91b

I felt a little uncomfortable implementing an iterator on a type that has a provision to supply an `infinite stream` of contained objects :) Eager to know what others think!

**Comment by Lukasa** [comment]
`EventLoop` is a class-bound protocol, so the end condition can be defined in terms of object identity I think.

Rather than conform `EventLoopGroup` to `Sequence`, why not instead create an object that can wrap an `EventLoopGroup` and conform it that way? That avoids the redundant conformances but still lets you avoid some of the overhead of making the protocol itself provide the iterator.

**Comment by pushkarnk** [comment]
Thanks for the suggestions @Lukasa ! I've created https://github.com/apple/swift-nio/pull/500

**Comment by Lukasa** [comment]
Fixed in 1.9.0.
