### ISSUE TITLE
ChannelHandlers should not automatically be assumed to be safe to use concurrently in multiple channels.

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio#507]
Related to #506.

Right now it's assumed that all `ChannelHandler` objects are safe to use from multiple channels, and requires user intervention to make the code assert otherwise. We should come up with a scheme that allows us to enforce this, and also use something like a tag protocol to require that users explicitly state if the channel handler is safe to use from multiple channels.

Any change here is likely to be breaking, and so we'll queue this up for 2.0.

**Comment by fadi-botros** [comment]
What about using the reference count itself ??? If the ChannelHandler isn't used except as a parameter to the "addToPipeline" function, so we could atomically check the reference count (well, checking the reference count may not be available in Swift), or

we could make a wrapper that wraps the `ChannelHandler` and not permit using it directly, this wrapper could be like that

```swift
protocol ChannelHandlerWrapper {
    var channelHandler: ChannelHandler? { get }
}
```

```swift
class OneTimeOnlyChannel: ChannelHandlerWrapper {
    private var _channelHandler: ChannelHandler

    var channelHandler: ChannelHandler? {
         get {
             return atomicallyGetAndSetTo(_channelHandler, nil) // Do some atomic GetAndSet here
                             // We may not need atomics if we are always adding from the same thread
         }
    }

    init(channelHandler: ChannelHandler) {
        self.channelHandler = channelHandler
    }
}
```

```swift
class ThreadSafeChannel: ChannelHandlerWrapper {
    var channelHandler: ChannelHandler

    init(channelHandler: ChannelHandler) {
        self.channelHandler = channelHandler
    }
}
```

**Comment by Lukasa** [comment]
We can't use the reference count, sadly, because holding a ref to the channel handler outside the only channel to which it is added is not unreasonable: it's a common pattern in tests at the very least.

The atomic is definitely possible, but it's a bit less clear to me whether it's the best way to handle it.

**Comment by Lukasa** [comment]
I believe this is actually resolved by Swift, as `Sendable` is now an appropriate proxy for this use-case.
