### ISSUE TITLE
in event loop assertion failing with multiple threads

### ISSUE THREAD

**Issue by tanner0101** [apple/swift-nio#51]
[This line](https://github.com/apple/swift-nio/blob/master/Sources/NIO/EventLoopFuture.swift#L523) is getting hit when `MultiThreadedEventLoopGroup` is configured with `numThreads > 1` [right here](https://github.com/apple/swift-nio/blob/master/Sources/NIOHTTP1Server/main.swift#L389). 

You can recreate this with the following steps:

1: clone swift-nio master
2: configure `group` to `System.coreCount` threads or just hard-code to 8
3: run `NIOHTTP1Server` executable
4: run `curl localhost:8888`

This doesn't get hit in release mode (obviously) and `wrk` seems to work fine, but I'm assuming that `assert` there is important for performance / stability reasons.

**Comment by normanmaurer** [comment]
@tanner0101 we will have a look. This is definitely a bug ...

**Comment by normanmaurer** [comment]
@weissi can you have a look ?

**Comment by normanmaurer** [comment]
Was fixed via #63
