### ISSUE TITLE
pass the `RepeatedTask` to its closure

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#514]
when a `RepeatedTask` invokes its closure the user might want to cancel the `RepeatedTask`. Doing that is pretty error-prone without being handed the `RepeatedTask` itself. We should fix this before 1.9.0 gets released.

CC @FranzBusch

**Comment by weissi** [comment]
cc @Lukasa

**Comment by FranzBusch** [comment]
I will implement this weekend.

**Comment by Lukasa** [comment]
Resolved by #515.
