### ISSUE TITLE
Failure in WebSocket protocol upgrade

### ISSUE THREAD

**Issue by nethraravindran** [apple/swift-nio#519]
`Upgrade` header for a web socket upgrade request can either have `Websocket` or `websocket` as its value. 

Upgrade request with ```Websocket``` protocol fails because  the supported protocol is ```websocket```.

However the protocol names should be case-insensitive for the `HTTPServerUpgradeHandler` to handle the upgrade request

**Comment by weissi** [comment]
fixed in #520
