### ISSUE TITLE
internal Socket protocol should use Unsafe(Mutable)RawBufferPointer instead of UnsafePointer<UInt8> and size

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#523]
The `Socket` protocol is one of the oldest bits of NIO code and uses legacy type-signatures like

    func write(pointer: UnsafePointer<UInt8>, size: Int) throws -> IOResult<Int>
    func read(pointer: UnsafeMutablePointer<UInt8>, size: Int) throws -> IOResult<Int>

and others. These should be

    func write(from: UnsafeRawBufferPointer) throws -> IOResult<Int>
    func read(into: UnsafeMutableRawBufferPointer) throws -> IOResult<Int>

and the same for functions like `sendto`.

**Comment by Lukasa** [comment]
This is fixed.
