### ISSUE TITLE
Futures without EventLoops

### ISSUE THREAD

**Issue by MasterSwift** [apple/swift-nio#530]
please add in ability to initialize futures without event loops.

**Comment by MasterSwift** [comment]
it makes It tough when you want to mix sync and async. as much as this is a async library, you will WANT async with sync and sync with async.

**Comment by Lukasa** [comment]
We cannot. 😊

NIO’s `Future` objects are event loop constructs. They make guarantees about scheduling all callbacks on a single event loop, as they are intended to be used for that purpose. As a result they *require* access to an event loop; they literally cannot function without one. 

A more-general `Future` object can definitely be written, but it is not the place of NIO to provide it.
