### ISSUE TITLE
Thoughts on gRPC

### ISSUE THREAD

**Issue by SebastianThiebaud** [apple/swift-nio#55]
Thank you for this library, this is some great work. 
I was wondering if there is any plan to work on a gRPC library in Swift, built on top of `swift-nio`. I'd be more than interested to contribute and wanted to check if gRPC was part of some roadmap, directly (or undirectly) related to `swift-nio` and this project.
Thank you.

**Comment by Lukasa** [comment]
We'd love to have gRPC support. 👍 However, a NIO-native gRPC implementation has some protocol implementation requirements for us to build first: we need HTTP/2. HTTP/2 is pretty early on the roadmap, and some work has been done already, so we're definitely on the way there.

In the meantime, if you need gRPC today you can work with the reference implementation in a background thread and use Dispatch + EventLoopFuture to get work across the thread boundary. That should work pretty well as a stopgap solution.

**Comment by SebastianThiebaud** [comment]
Glad to hear about this! Thanks for the quick answer.
