### ISSUE TITLE
Use of unresolved identifier `WebSocketProtocolErrorHandler`

### ISSUE THREAD

**Issue by TannerJuby01** [apple/swift-nio#570]
https://github.com/apple/swift-nio/blob/131f378d95cd548118a1da3dea249b10b427cbee/Sources/NIOWebSocket/WebSocketUpgrader.swift#L155

After updating running `swift package update` I am receiving the error `Use of unresolved identifier 'WebSocketProtocolErrorHandler'` in using this package in Vapor projects.

**Comment by Lukasa** [comment]
That’s weird, the class is right here: https://github.com/apple/swift-nio/blob/131f378d95cd548118a1da3dea249b10b427cbee/Sources/NIOWebSocket/WebSocketProtocolErrorHandler.swift

**Comment by Lukasa** [comment]
Does it occur even when you build with SwiftPM from the command line?

**Comment by TannerJuby01** [comment]
Strangely enough, I found out that the file existed in the file structure, but it does not get added to the Xcode project upon generation of the Vapor project. Don't know if this would be due to a `Package.swift` issue in the swift-nio target, or due to Vapor's Xcode project generator.

**Comment by Lukasa** [comment]
Does it occur with `swift package generate-xcodeproj`?
