### ISSUE TITLE
More detailed WebSocket upgrade errors

### ISSUE THREAD

**Issue by pushkarnk** [apple/swift-nio#577]
`WebSocketUpgrader.buildUpgradeResponse` throws an `invalidUpgradeHeader` error in three cases:
1. The `Sec-WebSocket-Key` or `Sec-WebSocket-Version` headers are absent
2. The `Sec-WebSocket-Key` or `Sec-WebSocket-Version`  headers have multiple values
3. The `Sec-WebSocket-Version` value is not 13

A caller that catches this error, has no way to determine which one of the three cases caused the error. This caller (server) may want to return a detailed error message to the client that requested the invalid upgrade.

Two ways of implementing this would be:
1. Split `invalidUpgradeHeader` into fine-grained cases in the `NIOWebSocketUpgradeError` enum
2. Provide an associated value (an error code or an error message) for `invalidUpgradeHeader`

Are there any other ways of getting this next detail of information from the upgrader, in its current form?

cc @Lukasa

**Comment by Lukasa** [comment]
Ah, actually, the first option doesn't work, as we have no pipeline context with which to return the additional errors.

**Comment by Lukasa** [comment]
Ok, I think a flag on `init` is bad. So let's re-evaluate.

To get this to work *today*, @pushkarnk, you can write a small delegate object like this:

```swift
public final class WrappingWebSocketUpgrader: HTTPProtocolUpgrader {
    private let _wrappedUpgrader: WebSocketUpgrader
    public var supportedProtocol {
        return self._wrappedUpgrader.supportedProtocol
    }

    public var requiredUpgradeHeaders: [String] {
        return self._wrappedUpgrader.requiredUpgradeHeaders
    }

    // You'd need to provide an init here, I'm not writing it because it's not germane to the example

    public func upgrade(ctx: ChannelHandlerContext, upgradeRequest: HTTPRequestHead) -> EventLoopFuture<Void> {
        return self._wrappedUpgrader(ctx: ctx, upgradeRequest: upgradeRequest)
    }

    public func buildUpgradeResponse(upgradeRequest: HTTPRequestHead, initialResponseHeaders: HTTPHeaders) throws -> HTTPHeaders {
        do {
            return try self._wrappedUpgrader(upgradeRequest: upgradeRequest, initialResponseHeaders: initialResponseHeaders)
        } catch NIOWebSocketUpgradeError.invalidUpgradeHeader {
            let keyHeader = upgradeRequest.headers[canonicalForm: "Sec-WebSocket-Key"]
            let versionHeader = upgradeRequest.headers[canonicalForm: "Sec-WebSocket-Version"]
            
            if keyHeader.count == 0 {
                // throw appropriate sub-error
            } else if keyHeader.count > 1 {
                // throw appropriate sub-error
            } else if versonHeader.count == 0 {
                // throw appropriate sub-error
            } else if versionHeader.count > 1 {
                // throw appropriate sub-error
            } else if version.first! != "13" {
                // throw appropriate sub-error
            } else {
                throw error
            }
        } catch {
            throw error
        }
    }
}
```

The code could be cleaned up slightly, but this would basically work. This gives you a special-case upgrader that delegates its behaviour to the backing upgrader but transforms the errors where necessary. It should be the easiest thing to do without a semver-major.

**Comment by Lukasa** [comment]
For 2.0 I think we need to remove this error enum and replace it with the error pattern we've been using elsewhere involving protocols and structs. We also then obviously need to address the lack of granularity in this error.

**Comment by weissi** [comment]
@Lukasa I agree with everything you said really but maybe instead of a flag for init, we could maybe

- deprecate the old init (and make it set an `self.newErrorStyle = false`)
- deprecate the old error itself
- make up a new init (and make it set `self.newErrorStyle = true`)
- in case of error we check the `newErrorStyleFlag` and propagate the appropriate errors

**Comment by Lukasa** [comment]
Yeah, we could do that. I don't think the flag was the bit of this I liked least, really: I think my biggest problem is that it essentially becomes a boolean flag passed at one line of code to change the return value of a function at a completely different place. In essence this function just has two APIs, which is pretty sad and weird.

**Comment by weissi** [comment]
@Lukasa agreed. Your call if the status quo or the flag is worse :)

**Comment by pushkarnk** [comment]
Thanks @Lukasa for helping me work around this limitation!

**Comment by Lukasa** [comment]
Splitting this into two issues. We'll move to the struct errors in 2.0, but will delay adding the more detailed errors until after the 2.0 release. This issue will track the more detailed errors: #839 will track the move to structs. Removing from 2.0.
