### ISSUE TITLE
ByteToMessageDecoder's state should be private

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#584]
Currently, `ByteToMessageDecoder` requires the user to create a `var cumulationBuffer: ByteBuffer?`. That invites the user to directly alter this `cumulationBuffer` but in many cases that's not actually allowed (re-entrancy). Also it's impossible for us to add further state. I'd argue to create a new

    public struct ByteToMessageDecoderState {
        internal init (...) {
            [...]
        }
        internal var ...
    }

So the type itself should be public but all members and inits should be internal only. That way the user cannot do operations that aren't actually legal.

Clearly this is public API breaking so will be 2.0.

**Comment by Lukasa** [comment]
Yeah, this is definitely a good idea. I'm strongly in favour.

**Comment by weissi** [comment]
done with #675
