### ISSUE TITLE
Name is silly, take Swift out of the name

### ISSUE THREAD

**Issue by uchuugaka** [apple/swift-nio#588]
### Expected behavior
Name should be nio or NIO not SwiftNIO

### Actual behavior
Name made me cry.

### Steps to reproduce

Read it.
Get some tissue.

### If possible, minimal yet complete reproducer code (or URL to code)

https://github.com/apple/swift-nio

### SwiftNIO version/commit hash

N/A

### Swift & OS version (output of `swift --version && uname -a`)
N/A

**Comment by Lukasa** [comment]
Eh, it's basically fine.
