### ISSUE TITLE
consider exposing the current `EventLoop`

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#59]
In certain cases nicer APIs can be created if there's a public way to get the _current_ `EventLoop` from within a SwiftNIO app. We should consider doing that. The most straight-forward implementation is obviously to just store in in a `ThreadSpecificVariable`.

**Comment by normanmaurer** [comment]
@weissi This sounds very reasonable and cheap to support... +1 for this.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/apple/swift-nio/pull/120
