### ISSUE TITLE
Make CI jobs for Swift 4.2 & Ubuntu 18.04

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#606]
this is for the CI jobs in Jenkins, the work to support Swift 4.2 & Ubuntu 18.04 in docker is in #604.

In total I think we need the following new CI jobs (ordered by how important @weissi thinks they are):

- [x] Swift 4.2 on Ubuntu 18.04
- [ ] Swift 4.2 on Ubuntu 16.04
- [ ] Swift 4.2 on Ubuntu 14.04

note: there are no Swift 4.0 or 4.1 binaries available for Ubuntu 18.04, hence we won't have Swift 4.0 or 4.1 on Ubuntu 18.04

CC @tomerd who holds the CI 🔐

**Comment by tomerd** [comment]
added PRB for Swift 4.2 on Ubuntu 18.04

we can add the others as nightly if we think its required

**Comment by weissi** [comment]
thanks @tomerd
