### ISSUE TITLE
consider making ThreadSpecificVariable public

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#61]
We should consider making [`ThreadSpecificVariable`](https://github.com/apple/swift-nio/blob/master/Sources/NIO/Thread.swift#L133) public.
Related to #60 (consider having an API to allow attaching metadata to an `EventLoop`)

**Comment by normanmaurer** [comment]
@Lukasa are you cool with this change ? If so I will make it happen

**Comment by Lukasa** [comment]
Yeah, I'm happy enough to do that.

**Comment by normanmaurer** [comment]
Was merged...
