### ISSUE TITLE
IdleStateHandler should forward forward channelActive events

### ISSUE THREAD

**Issue by ldewailly** [apple/swift-nio#614]
### Expected behavior
If I add a `ChannelInboundHandler` after a `IdleStateHandler`, I'd expect to receive the `channelActive` event in my handler

### Actual behavior
`channelActive(ctx)` is never invoked on the channel inbound handler.

### Steps to reproduce

Create a pipeline as illustrated below and establish a connection. The second handler doesn't receive the `channelActive` event

### If possible, minimal yet complete reproducer code (or URL to code)

```swift
// start the server
let group = MultiThreadedEventLoopGroup(numberOfThreads: 1)
final class ServerHandler: ChannelInboundHandler {
    typealias InboundIn = ByteBuffer
}
defer { try? group.syncShutdownGracefully() }
let serverChannel = try ServerBootstrap(group: group)
    .serverChannelOption(ChannelOptions.socket(SocketOptionLevel(SOL_SOCKET), SO_REUSEADDR), value: 1)
    .childChannelInitializer { channel in
        channel.pipeline.add(handler: ServerHandler())
    }.bind(host: "127.0.0.1", port: 0).wait()

// connect the client
class MyChannelHandler: ChannelInboundHandler {
    typealias InboundIn = NIOAny
    func channelActive(ctx: ChannelHandlerContext) {
        print("-> channelActive")
    }
}
_ = try ClientBootstrap(group: group)
    .channelInitializer { channel in
        channel.pipeline.add(handler: IdleStateHandler()).then {
            channel.pipeline.add(handler: MyChannelHandler())
        }
    }.connect(to: serverChannel.localAddress!).wait()
```

I would expect `-> channelActive` to be printed to the console, but it's not

### SwiftNIO version/commit hash

59ad7133484eec63ff5d75d407b7b84b87d7589b

### Swift & OS version (output of `swift --version && uname -a`)

n/a

**Comment by normanmaurer** [comment]
@ldewailly PTAL https://github.com/apple/swift-nio/pull/615
