### ISSUE TITLE
documentation https link doesn't work

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#628]
### Expected behavior
- https://docs.swiftnio.io works
### Actual behavior
just hangs

### Steps to reproduce

1. open https://docs.swiftnio.io

### further info:

```
$ curl -v https://docs.swiftnio.io
* Rebuilt URL to: https://docs.swiftnio.io/
*   Trying 52.219.24.35...
* TCP_NODELAY set
[hangs]
```

**Comment by weissi** [comment]
ping @tomerd

**Comment by tomerd** [comment]
fixed
