### ISSUE TITLE
Deprecated use: '@_versioned' & '@_inlineable'

### ISSUE THREAD

**Issue by marc-medley** [apple/swift-nio#631]
### Expected behavior

General interest in using _warnings-clean_ packages when developing projects. 

The expected behavior was that a current release of `swift-nio` build warnings-clean with the latest full production release of Swift (4.2).

### Actual behavior

Xcode 10.0 (10A255) produces approx 129 warnings relating to the deprecated use of `@_versioned` and `@_inlineable` when built with the Swift 4.2 that ships with same Xcode. 

### Steps to reproduce

Build `swift-nio` with the Swift 4.2 that ships with Xcode 10.

### If possible, minimal yet complete reproducer code (or URL to code)

In my case, `swift-nio` is built as a depedency of [Vapor](https://github.com/vapor/vapor).  A minimal reproduder would be to just build `swift-nio` with Xcode 10 + Swift 4.2.  

### SwiftNIO version/commit hash

SwiftNIO 1.9.5

* https://github.com/apple/swift-nio/tree/1.9.5 
* https://github.com/apple/swift-nio/commit/5d8148c8b45dfb449276557f22120694567dd1d2

### Swift & OS version (output of `swift --version && uname -a`)

Apple Swift version 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1)
Target: x86_64-apple-darwin17.7.0
Darwin Candela.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

**Comment by AlanQuatermain** [comment]
As it stands, SwiftNIO supports versions of Swift prior to 4.2, so it can't directly use the new versions of these keywords (`@inlinable` and `@usableFromInline`). Ideally we'd be able to make that break for SwiftNIO v2.0, but for now I believe the lowest target is Swift 4.1, which would require these attributes remain as-is for now.

**Comment by Lukasa** [comment]
Additionally my understanding is that these should not fire warnings when using Swift 4.0 language mode, per [SR-7578](https://bugs.swift.org/browse/SR-7578).

Unfortunately our hands are tied here: we do not want to drop Swift 4.1 support at this time, and removing the annotations would lead to a substantial performance regression. For now I’m afraid this is just something we have to live with.
