### ISSUE TITLE
CNIOZlib Xcode build error

### ISSUE THREAD

**Issue by noahemmet** [apple/swift-nio#643]
### Expected behavior
The ability to build the latest SwiftNIO release from within Xcode.

### Actual behavior
I'm getting a build error `Include of non-modular header inside framework module 'CNIOZlib': '/opt/local/include/zlib.h'` inside the `CNIOZlib.h` file at `#include <zlib.h>`.

### Steps to reproduce

1. Download the latest release
2. Run `swift package update; swift package generate-xcodeproj`
3. Open the generated Xcode project, and try building the `swift-nio-Package` schema.

### SwiftNIO version/commit hash

[Release 1.10.0](https://github.com/apple/swift-nio/releases/tag/1.10.0)

### Notes

It seems that `swift build --target NIO` builds successfully; this problem exists solely when building from Xcode.

I think https://github.com/apple/swift-nio/commit/9bae007a15b49d7fe685b6b33308822c6d0536c0 is the culprit, as I can build successfully from the previous commit, https://github.com/apple/swift-nio/commit/ed28803a78b187e202c27a62c7a497fbe9cfbbd7.

I am running MacOS 10.14.1 Beta (18B73a).

**Comment by Lukasa** [comment]
Do you have zlib installed from Homebrew, MacPorts, or any other source? It seems like we're getting a conflicting include of `zlib.h`, where we're expecting the platform header (which is a module header) but getting a shadow copy.

**Comment by mixio** [comment]
I have the same issue,

When updating to swift-nio-1.10.0, I get the following compiler error:

`Include of non-modular header inside framework module 'CNIOZlib': '/amp/sw/zlib/include/zlib.h'`

When building with swift-nio-1.9.5, everything compiles fine.
    
I can see a difference in `*.xcodeproj/GeneratedModuleMap/`.

With swift-nio-1.10.0 there are only 2 modulemaps:
    
    - CCryptoOpenSSL
    - CNIOOpenSSL
    
With swift-nio-1.9.5 there are 8 modulemaps:
    
    - CCryptoOpenSSL
    - CNIOAtomics
    - CNIODarwin
    - CNIOHTTPParser
    - CNIOLinux
    - CNIOOpenSSL
    - CNIOSHA1
    - CNIOZlib
    
I have a custom location for zlib.
If I remove it, swift-nio-1.10.0 compiles file.

**Comment by noahemmet** [comment]
> Do you have zlib installed from Homebrew, MacPorts, or any other source?

I did! Running `sudo port uninstall --follow-dependents zlib` fixed the issue. Thanks!

**Comment by Lukasa** [comment]
@mixio Why do you have a custom zlib install being included?

**Comment by mixio** [comment]
It's not a custom zlib but a custom location with a zlib manually built, left over of a previous project dependency.

**Comment by Lukasa** [comment]
@mixio Why are you linking against that zlib?

**Comment by mixio** [comment]
I have a customized php linked against a few libraries I compile manually. Those libs were in the LD_LIBRARY_PATH.

**Comment by Lukasa** [comment]
Do you also have a custom include path? In general you shouldn't shadow system libraries like this in a general way: it can lead to real subtle bugs if the shadowing is applied inconsistently. You should probably apply the build flags only when necessary, rather than to all builds on your system.

**Comment by mixio** [comment]
That's what I try to do.

**Comment by Lukasa** [comment]
I don't think you're succeeding, sadly, as Xcode seems to be looking up the header files. What's the value of the `C_INCLUDE_PATH` environment variable? If it's unset, try re-generating your `.xcodeproj` and rebuilding.

**Comment by mixio** [comment]
@Lukasa since I removed the custom zlib everything compiles fine with 1.10.0.

**Comment by weissi** [comment]
ok, interesting. Glad we got all of you unblocked but I figure we should CC @aciidb0mb3r too. That must be related to https://github.com/apple/swift-nio/pull/636 which is the change to use umbrella headers for the C modules. I didn't expect that to have the side-effects of breaking with custom zlibs, @aciidb0mb3r any input?

**Comment by aciidb0mb3r** [comment]
> @aciidb0mb3r mind telling @mixio & @noahemmet what logs you'd like to see? As far as I understand you'd like them to install back the custom zlib, compile NIO 1.9.5 and send you some logs, right?

Right, exactly and then attach the build log generated in Xcode.

**Comment by mixio** [comment]
@aciidb0mb3r here are le [build logs](https://gist.github.com/mixio/08f8da82df0725ceefa9323e7bbea367).

**Comment by aciidb0mb3r** [comment]
This should be enough, can you file this as a radar though?

**Comment by weissi** [comment]
@aciidb0mb3r done, closing this issue now
