### ISSUE TITLE
collection of renames for 2.0

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#663]
This is supposed to become a crowd-sourced random collection of renames in SwiftNIO for the 2.0 release. Please just add something like

- [ ] rename `FooBar(bar: Bar)` to `FooBar(_ bar: Bar)`

**Comment by weissi** [comment]
again, CC'ing some folks @helje5 / @tanner0101 / @ianpartridge / @pushkarnk / @MrMage / @tachyonics / @airspeedswift / @moiseev / @kjessup / @normanmaurer / @Lukasa / @Joannis . Please name your small pet peeves here :)

**Comment by MrMage** [comment]
- [ ] rename `ctx` to `context`

What’s the motivation for changing port numbers to `Int`? Aren’t they always unsigned 16-bit integers?

**Comment by weissi** [comment]
> * [ ]  rename `ctx` to `context`
> 
> What’s the motivation for changing port numbers to `Int`? Aren’t they always unsigned 16-bit integers?

it's Swift convention to always use `Int` for everything (at least in public API) because it makes interoperability work much better. See for example Array's `var count: Int` even though clearly it's never negative...

**Comment by MrMage** [comment]
Makes sense, thanks!

**Comment by weissi** [comment]
- [ ] `new*Promise` to `make*Promise` as of the Swift API guidelines: ["Begin names of factory methods with “make”, e.g. `x.makeIterator()`"](https://swift.org/documentation/api-design-guidelines/#begin-factory-name-with-make)

**Comment by ianpartridge** [comment]
Do you want to tackle https://github.com/apple/swift-nio/pull/602 in 2.0 too?

**Comment by weissi** [comment]
@ianpartridge absolutely! thanks for reminding me

**Comment by weissi** [comment]
- [x] rename `then` to `flatMap`
- [x] rename `thenIfError` to `flatMapError`

to match `Result` in the stdlib

**Comment by tanner0101** [comment]
- [ ] rename `thenThrowing` to `mapThrowing` and add a `thenThrowing` that accepts a future. 
- [ ] make pipeline handler add / remove methods more consistent. i.e., all should support `before` / `after`, `first`, array, name, etc.
- [ ] add `promise.succeed()` with no args where `Success == Void`
- [ ] add convenience method for creating required wrapper to `ByteToMessageDecoder`. (maybe `PostgresMessageDecoder().handler`?)
- [ ] add `cascadeSuccess` to future. 
(I'll add to this list if I think of any more)

**Comment by tanner0101** [comment]
> What does remove(before:) mean? I don’t think that one makes much sense.

Sorry, the comment should just say "add methods". 

![screen shot 2019-01-23 at 5 02 42 pm](https://user-images.githubusercontent.com/1342803/51640167-c7a6cf00-1f30-11e9-8568-6a5ff470aa12.png)

Mostly I just think it would be nice to have the option to specify name / after / before when adding an array of handlers. For name, something like `[String: ChannelHandler]` would be nice. I also think naming this method `add(handlers:)` or `add(_ handlers:)` might be more Swifty.

**Comment by weissi** [comment]
> * [ ]  rename `thenThrowing` to `mapThrowing` and add a `thenThrowing` that accepts a future.

strong -1 to any name that starts with `map*`, that name would be just wrong. `map`'s signature is

    (ELF<Value>) -> ((Value -> NewValue)) -> ELF<NewValue>

, the important part here is that you can only transform a _success_ to a _success_ and nothing else.

`flatMapThrowing` (used to be `thenThrowing`) is a good name because its name is exactly what it does: It takes a throwing thing, converts that to an `ELF` and then `flatMap`s that. Works. You just can't implement that function with a `map` only but you can with a `flatMap`.

Namely, there's a natural translation from

    (A) throws -> B

to

    (A) -> EventLoopFuture<B>

which is exactly the right input type for a `flatMap. But there isn't any from

    (A) throws -> B

to

    (A) -> B

which would be the right input type for a `map`. I'm open to giving it some other name `combineThrowing` but it can't start with `map` because that's really wrong and misleading. My point is still that `flatMapThrowing` is arguably the best name because that's what it is (see it's implementation):

```swift
    public func flatMapThrowing<NewValue>(file: StaticString = #file,
                                line: UInt = #line,
                                _ callback: @escaping (Value) throws -> NewValue) -> EventLoopFuture<NewValue> {
        return self.flatMap(file: file, line: line) { (value: Value) -> EventLoopFuture<NewValue> in
            do {
                return EventLoopFuture<NewValue>(eventLoop: self.eventLoop, result: try callback(value), file: file, line: line)
            } catch {
                return EventLoopFuture<NewValue>(eventLoop: self.eventLoop, error: error, file: file, line: line)
            }
        }
    }
```

but I realise that people don't like it so I'd be open to `combineThrowing`  or so.

> * [ ]  add `promise.succeed()` with no args where `Success == Void`

-1 to this one too. Overloads always lead to sadness and this one saves two characters (I'll make a PR to get rid of the labels for `succeed` and `fail`).

> * [ ]  add `cascadeSuccess` to future.

+1

**Comment by weissi** [comment]
closing because mostly done apart from the work already filed as #483
