### ISSUE TITLE
get Swift 4.x CI for nio-1.12 and Swift 5 CI for master

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#667]
soon after there are Swift 5 snapshots to download from https://swift.org/download, we'll make the `master` branch Swift 5-only and `nio-1.12` will remain the Swift 4.x train.

So we need to re-architect how CI works:

`master` and all PRs targeting `master` need:
- Swift 5.0 on Ubuntu 18.04 and 16.04

`nio-1.12` and all PRs targeting `nio-1.12` need:
- Swift 4.0 on Ubuntu 14.04
- Swift 4.1 on Ubuntu 16.04
- Swift 4.2 on Ubuntu 18.04

CC @tomerd do you see any issues with this?

**Comment by weissi** [comment]
this can now be kicked off as the first Swift 5.0 tarballs are available 🎉

**Comment by tomerd** [comment]
nio-1.12
https://ci.swiftnio.io/job/swift-nio1-swift40-prb/
https://ci.swiftnio.io/job/swift-nio1-swift41-prb/
https://ci.swiftnio.io/job/swift-nio1-swift42-prb/

master
https://ci.swiftnio.io/job/swift-nio2-swift50-prb/

**Comment by weissi** [comment]
awesome, thanks so much @tomerd
