### ISSUE TITLE
ByteBuffer methods to respect reader/writer indexes

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#669]
`ByteBuffer` has some `get*` methods which do not respect the reader/writer indexes, and instead only respect the capacity of the buffer. This may result in accessing uninitialized memory and lead to unexpected results. I would propose that by default we have methods respect the reader/writer indexes and only if necessary expand the `ByteBuffer` API to include methods which ignore the reader/writer index (e.g. new methods, optional parameter, etc...).

Netty issue: https://github.com/netty/netty/issues/8601

documented here:
- [Important Usage Notes](https://apple.github.io/swift-nio/docs/current/NIO/Structs/ByteBuffer.html#important-usage-notes)
- for example in [`ByteBuffer.getInteger`](https://apple.github.io/swift-nio/docs/current/NIO/Structs/ByteBuffer.html#/s:3NIO10ByteBufferV10getIntegerxSgSi2at_AA10EndiannessO10endiannessxm2asts010FixedWidthE0RzlF)'s warning

**Comment by weissi** [comment]
@normanmaurer / @Lukasa are we doing this? I'm strong +1.

**Comment by Lukasa** [comment]
I think we should.

**Comment by weissi** [comment]
@normanmaurer okay with this too?

**Comment by AlanQuatermain** [comment]
I've been using these to more easily support dropping a payload-length value at the start of a header. In my HTTP2 encoder I'll skip three bytes, fill in the rest, and then once I've generated the payload I'll use the `set(integer:at:)` (I think?) API to put the length value back at the start of the block without manually moving the writer index back & forth, and also without accumulating other random-sized values (e.g. strings) within a secondary buffer.

**Comment by AlanQuatermain** [comment]
I also suspect I used the `get` variants in the HPACK Huffman implementation, though I don't have the source with me right now.
