### ISSUE TITLE
Question: Nested requests

### ISSUE THREAD

**Issue by mattpaletta** [apple/swift-nio#677]
Hi,
I'm trying at using swift-nio in one of my projects.  I'm working on a peer-to-peer distributed hash tables (for research).  I was hoping to use swift-nio as a networking layer, as I'm targeting devices that don't have very much computational power available, asynchronous networking seemed appealing.  

I think I've figured out to create a server and a client and have a client request a message to the server, the server parse it, process it, and return a value.  I also understand how you can use channel pipeline's to abstract the lower encode/decode steps in the process.

Where I'm stuck is what is the proper 'way', or idioms to read from a buffer (from the client), get a new channel to your peer, do some local processing, write to the buffer for your peer, wait for a response from your peer, then write data back to the client?

From what I've gathered so far, I'd call my delegate that implements my logic in the 'read' method on the server, passing it the data, and within the delegate method, create a new channel.  The delegate would add the new channel.write & channel.read (to it's peer) operation as a promise on the original context. My question, how do I handle getting the response from the same context to go back to the same synchronous code, so my delegate can continue executing, and eventually write data back to the first client.

Any help pointing me in the right direction would be very helpful.  Thanks!

### SwiftNIO version/commit hash
0.6.0

### Swift & OS version (output of `swift --version && uname -a`)
Swift 4.2.1
Mac OS High Sierra 10.13.6

**Comment by Lukasa** [comment]
> Where I'm stuck is what is the proper 'way', or idioms to read from a buffer (from the client), get a new channel to your peer, do some local processing, write to the buffer for your peer, wait for a response from your peer, then write data back to the client?

Let me break these steps down.

Reading from a buffer is `ChannelInboundHandler.channelRead`. You sound like you've already got a parser in place, which is good, as this means you'll always be reading whole messages.

Getting a new `Channel` to your peer is either using a `ClientBootstrap` to create one, or obtaining one from a connection pool. The former is much easier to get right in the first instance so I'd try that.

Doing local processing can be managed however you choose to manage it, either on the event loop or in a background thread. As getting a new `Channel` is asynchronous work you can race it with doing this processing if you like.

Write to the buffer for the peer is done by calling `Channel.write` on your new `Channel`.

Wait for a response from your peer requires a `ChannelInboundHandler` in the new `Channel`. This `ChannelInboundHandler` should be initialized with an `EventLoopPromise` that it will fulfil when the response is complete. You can then attach callbacks to that promise to handle the response.

Write data back to the client means calling `Channel.write` on the *original* `Channel` that started all of this work.

Does that help? If not, it may be helpful to see some of the code you're working on.

**Comment by mattpaletta** [comment]
Hi @Lukasa,
Thanks so much for getting back to me.  I understand the idea, and I tried to follow your advice starting with a more basic version, where I just have 1 channel and 1 peer, but I process the request that comes back.  I tried to follow your suggestions, and I was able to get a message from the client, send it to the server, and print the response back on the client within the handler.  The part I'm stuck on is how do I pass the promise and organize the handlers before I do the write so I can pass it up the 'promise stack'?

You can see the client code I have so far here:
https://github.com/mattpaletta/swift-nio-echo-server/tree/master/Sources/basic-client

And the server I'm using you can start with: `swift run echo-server`.

Thank you for your help.

**Comment by helje5** [comment]
It is less basic than I thought, but my WebSocket<->IRC bridge seems to be a little like what you are interested in, you can find it here: https://github.com/NozeIO/swift-nio-irc-webclient/blob/develop/Sources/IRCWebClient/IRCWebSocketBridge.swift, It translates NIO WebSocket packets into IRC ones and the reverse.

You usually don't have to do that much with Promises at all. If you receive data using `channelRead` you can do your transformations and pass it on to `write` on the outgoing channel. (either immediately or later).
The tricky bit is if you get a connection(channel) in your proxy, you need to setup the outgoing connection(channel) to your target. Which in itself is async (setting up the connection takes time). Before you are done with that setup, you may have received quite a few packets from the original client (which you are proxying).
There are two ways to deal with that, either you buffer those packets until you have a channel open to your target server, your you "suspend" the channel from reading any packets before you have that (there is some "autoread" flag, which you may want to disable until you have the target connection).

**Comment by Lukasa** [comment]
> (all that is more manual than with say Node, where you just create two streams and hook them up)

Indeed. I'm definitely interested in spending some time designing a nice "join these two Channels together" tool for SwiftNIO. It's reasonably straightforward in principle, but as with all things requires some thought to make the API pleasant and to avoid it being too surprising.

> The part I'm stuck on is how do I pass the promise and organize the handlers before I do the write so I can pass it up the 'promise stack'?

Whether you need a promise stack is very dependent on what exactly you're trying to do. If the goal is literally simply to proxy (that is, to shuffle bytes from the client to the server, and back again) without additional application logic, then you want to do what @helje5 suggests, which is to glue two `Channel`s together. This can be done, but we'd need to put together an example of how to do it (or just write the utility ourselves).

**Comment by helje5** [comment]
Of course there is additional logic ("receive data using channelRead you can do your *transformations* and pass it on to write on the outgoing channel"). 
In Node/Noze you do this using a simple "transform" stream, like: `input-channel | through2 { packet, done in ... transform-packet ... done(newPacket) } | target-channel` ([this](http://noze.io/noze4nonnode/) has a few more examples, I also highly recommend the [stream-handbook](https://github.com/substack/stream-handbook) for inspiration, IMO the Node v3 streams concept is really good).
(I still want to port the Noze streams from GCD to NIO, but not sure when I find the time).

**Comment by mattpaletta** [comment]
Thank for your feedback.  I got it working! I agree that a proxy example would be very helpful.  I think I'm looking for a little more than a single transformation function (a proxy) to the stream.  I was looking to send a message asynchronously, wait for the response async, and process the result before responding to the original request.  I'd say more of a micro service architecture, where A calls B, B checks with C, D, and E, before responding to A.  A simple example of that kind of architecture I think would be very helpful for developers. :)

You can see my simple implementation here before I incorporate it into the bigger project: (in my `write` function).
https://github.com/mattpaletta/swift-nio-echo-server/blob/master/Sources/basic-client/Basic-Client.swift

Thanks for all your help. @Lukasa @helje5

**Comment by helje5** [comment]
>  I think I'm looking for a little more than a single transformation function (a proxy) to the stream. I was looking to send a message asynchronously, wait for the response async, and process the result before responding to the original request.

That is precisely what a proxy does :-)

**Comment by mattpaletta** [comment]
Hi again,
I think I have an idea of how to do the nested transactions, and I have 'a' way of calling a delegate for processing, from within the handler, but I'm not sure if it's the right way to do it.  I am also trying to figure out how to take that result from the handler delegate and send it back to the client that requested it.

At the moment when I write back out to the server I get the following error:
```
Precondition failed: file swift-nio-echo-server/.build/checkouts/swift-nio.git-3108475404973543938/Sources/NIO/ChannelPipeline.swift, line 153
```

The relevant code is here: https://github.com/mattpaletta/swift-nio-echo-server/blob/master/Sources/echo-server/Echo-Handler.swift


For the nested promises thing, and waiting on a reply, here's how I'm doing it currently (see DependHandler): 
`https://github.com/mattpaletta/swift-nio-echo-server/blob/master/Sources/basic-client/BasicHandler.swift`

If you have a better, or cleaner way of doing it that doesn't cause 'promise leaking' errors, that would also be very much appreciated.

Thank you for all your help, once again!

**Comment by mattpaletta** [comment]
Hi @Lukasa @helje5 

I think I got my project working (at least for now).  Thank you both so much for your help.  I really appreciate it.  I will mark this as resolved.

Matthew
