### ISSUE TITLE
Provide opaque indices for CircularBuffer.

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio#682]
When we made `CircularBuffer` a `Collection`, we gave it an `Int` `Index` and kept it zero-indexed. In this sense it behaved like `Array`.

After some conversations with @lorentey I think I've been convinced that we should use an opaque index type. The reasoning for it is this:

1. In general, the opaque index will improve the performance of indexing operations, as it will contain the index into the backing buffer. This will avoid the addition and modulo operation we need to perform today. The performance diff here is minor though, and isn't the main reason to do it.
2. Treating the index as an `Integer` means we invalidate the `Index` in situations where we do not need to. For example, if you have the index of a value in the circular buffer today, any operation on it other than `subscript { set }` will invalidate that index: it will now be pointing at a different element. This is a frustrating behaviour: it would be nicer to be able to document a set of operations on `CircularBuffer` that do *not* invalidate indices.
3. It's out-of-step with best-practices around `Collection` indexing. Acknowledging `Array` to be the odd-one-out here for both historical and cultural reasons, in general `Collection` types in Swift *should* define their `Index` as an opaque type, to avoid users performing unexpected operations on them.

My proposal is that we should move to the following `Index` definition:

```swift
struct Index {
    var baseIndex: Int  // Array.Index
    var age: UInt32
}
```

The use of a modification counter allows us to invalidate indices when an operation is performed that would break them, but keep them the same when they do not. It also allows indices to be safe to use across CoW copies of the data structure, again assuming that nothing has happened that invalidates the indices.

The operations that would bump `age` are:

1. Reallocating the underlying storage.
2. Invoking `replaceSubrange` (including its variants such as removing elements, or inserting new ones anywhere in the array).

Things that would *not* bump `age`:

1. `prepend()` or `append()` where the underlying storage is not reallocated.
2. `removeLast(_)`
3. Any other `Collection` method we can see that shouldn't do this
4. `subscript { set }`

Of course, integer indexing is useful, so we should give people a useful spelling. We can do this by implementing this subscript:

```swift
public subscript(offset: Int) -> E {
    get {
        let index = self.index(self.startIndex, offsetBy: offset)
        return self[index]
    }
    set {
        let index = self.index(self.startIndex, offsetBy: offset)
        self[index] = newValue
    }
}
```

This will allow users to continue to perform integer-based indexing with the same semantics as today, while improving the general conformance to the Swift collection protocols.

Thoughts?

/cc @airspeedswift @moiseev

**Comment by weissi** [comment]
this is precisely what I was thinking we should do, thanks @Lukasa for writing this up. In fact I think pretty much all `Collection`s should have opaque indices

**Comment by weissi** [comment]
that's done by #826 and will be improved further in #835
