### ISSUE TITLE
handleJustWrite ignores statusCode

### ISSUE THREAD

**Issue by bbum** [apple/swift-nio#713]
In NIOHTTP1Server/main.swift, the handleJustWrite(...) method of the HTTPHandler class has a statusCode argument (that defaults to .ok).

The argument is ignored in the call to httpResponseHead(), which makes all responses from handleJustWrite() locked to .ok.

This includes responses to /dynamic/ requests to nonsense sub-requests-- say, /dynamic/mumblejumble-- which passes a status of .notFound (and a body of "not found").

**Comment by bbum** [comment]
--- a/Sources/NIOHTTP1Server/main.swift
+++ b/Sources/NIOHTTP1Server/main.swift
@@ -172,7 +172,7 @@ private final class HTTPHandler: ChannelInboundHandler {
         case .head(let request):
             self.keepAlive = request.isKeepAlive
             self.state.requestReceived()
-            ctx.writeAndFlush(self.wrapOutboundOut(.head(httpResponseHead(request: request, status: .ok))), promise: nil)
+            ctx.writeAndFlush(self.wrapOutboundOut(.head(httpResponseHead(request: request, status: statusCode))), promise: nil)
         case .body(buffer: _):
             ()
         case .end:

**Comment by normanmaurer** [comment]
@bbum good catch... want to provide a PR with a fix ?
