### ISSUE TITLE
Make BlockingIOThreadPool.runIfActive public

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio#720]
We added `BlockingIOThreadPool.runIfActive` to provide a good helper for submitting tasks for third parties, but we left it internal, so it cannot be used.

**Comment by FrankKair** [comment]
Hi,

`BlockingIOThreadPool` is a `public` class, and the `extension` where `runIfActive` is defined is a `public extension` as well. So it seems that this function is public already (or did I miss something?).

This was the commit that removed the *redundant modifiers* (public extension with public func):
https://github.com/apple/swift-nio/commit/26bee216743165ee6ce32e27a7c6e82a2b0e52e5#diff-0049a9dcaa22d27b194632faba70203d

**Comment by weissi** [comment]
@FrankKair I think you're right!

**Comment by weissi** [comment]
thank you
