### ISSUE TITLE
Publish 1.12.0 to Cocoapods

### ISSUE THREAD

**Issue by ilyapuchka** [apple/swift-nio#721]
The latest version available in Cocoapods is 1.11.0, it would be nice to publish the latest, which is 1.12.0

<img width="1162" alt="screen shot 2018-12-26 at 13 58 21" src="https://user-images.githubusercontent.com/1488293/50447917-56b2ce00-0916-11e9-9abc-bf65f02c772a.png">

**Comment by weissi** [comment]
thanks @ilyapuchka I will do this tonight!

**Comment by weissi** [comment]
Sorry for the delay @ilyapuchka , now done :) https://cocoapods.org/pods/SwiftNIO
