### ISSUE TITLE
NIOChatServer fails to build

### ISSUE THREAD

**Issue by Khorlane** [apple/swift-nio#722]
### Expected behavior
Successful build

### Actual behavior
Build fails
Gets:
Use of unresolved identifier 'ByteToMessageHandler'; did you mean 'ByteToMessageDecoder'?

### Steps to reproduce
1. Try to build it

### If possible, minimal yet complete reproducer code (or URL to code)
I used the NIOChatServer code as is.

### SwiftNIO version/commit hash
Current version/commit
885ac373adf0441789574400affe9f7802607bce

### Swift & OS version (output of `swift --version && uname -a`)
Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
Target: x86_64-apple-darwin18.2.0
Darwin Stephens-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

**Comment by weissi** [comment]
@Khorlane if you want to use Swift 4.2.1, you'll need to either depend on NIO using SwiftPM or use the `nio-1.12` branch. `master` will only work with the latest Swift 5.0 development snapshots.
