### ISSUE TITLE
payload immediately in the web socket upgrade response always gets lost

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#741]
### Expected behavior

- NIO allows to forward 'left over' bytes trailing the server's upgrade response when NIO acts as an HTTP client

### Actual behavior

- NIO just drops them on the floor
- the only initialiser that `HTTPResponseDecoder` offers today sets [`leftOverBytesStrategy: .dropBytes`](https://github.com/apple/swift-nio/blob/f38984d80efd8548e9df6e3edba6193dbc71be54/Sources/NIOHTTP1/HTTPDecoder.swift#L185-L187)

### Steps to reproduce

Different options:

#### @MrLotU's repro:
1. create a bot here:  https://discordapp.com/developers/applications/ 
2. copy the token
3. put it in `Sources/NIOWSTryoutExample/main.swift`  replacing `"token"`
4. run the program

#### pre fabricated response

```
HTTP/1.1 101 Switching Protocols
Date: Mon, 07 Jan 2019 15:54:00 GMT
Connection: upgrade
Set-Cookie: __cfduid=XXXX; expires=Tue, 07-Jan-20 15:53:59 GMT; path=/; domain=.discord.gg; HttpOnly
sec-websocket-accept: XXXX
upgrade: websocket
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 495799b4eab30cc5-LHR

Å_{"t":null,"s":null,"op":10,"d":{"heartbeat_interval":41250,"_trace":["gateway-prd-main-0vfv"]}}
```

or as base 64:

```
SFRUUC8xLjEgMTAxIFN3aXRjaGluZyBQcm90b2NvbHMNCkRhdGU6IE1vbiwgMDcgSmFuIDIwMTkgMTU6NTQ6MDAgR01UDQpDb25uZWN0aW9uOiB1cGdyYWRlDQpTZXQtQ29va2llOiBfX2NmZHVpZD1YWFhYOyBleHBpcmVzPVR1ZSwgMDctSmFuLTIwIDE1OjUzOjU5IEdNVDsgcGF0aD0vOyBkb21haW49LmRpc2NvcmQuZ2c7IEh0dHBPbmx5DQpzZWMtd2Vic29ja2V0LWFjY2VwdDogWFhYWA0KdXBncmFkZTogd2Vic29ja2V0DQpFeHBlY3QtQ1Q6IG1heC1hZ2U9NjA0ODAwLCByZXBvcnQtdXJpPSJodHRwczovL3JlcG9ydC11cmkuY2xvdWRmbGFyZS5jb20vY2RuLWNnaS9iZWFjb24vZXhwZWN0LWN0Ig0KU2VydmVyOiBjbG91ZGZsYXJlDQpDRi1SQVk6IDQ5NTc5OWI0ZWFiMzBjYzUtTEhSDQoNCoFfeyJ0IjpudWxsLCJzIjpudWxsLCJvcCI6MTAsImQiOnsiaGVhcnRiZWF0X2ludGVydmFsIjo0MTI1MCwiX3RyYWNlIjpbImdhdGV3YXktcHJkLW1haW4tMHZmdiJdfX0NCg==
```

### SwiftNIO version/commit hash

1.9.0

### Swift & OS version (output of `swift --version && uname -a`)

swift 4.2.1 on macOS

**Comment by Lukasa** [comment]
Nah, let's close it.
