### ISSUE TITLE
Is writeAndFlush thread safe?

### ISSUE THREAD

**Issue by guarland** [apple/swift-nio#742]
Is writeAndFlush thread safe?

```
private let accessQueue = DispatchQueue(label: "ThreadSafeSocket", attributes: .concurrent)

func sendDataToWebSocket(number: String, data: Data)  {() {
    self.accessQueue.async(flags:.barrier) {
            if let webSocket = connections[number] {
                webSocket.send(data, promise: socketPromise)
            } 
        }
}
```

**Comment by Lukasa** [comment]
Yes.

However, I have no idea what code you have posted: it doesn't appear to be using SwiftNIO directly.

**Comment by Lukasa** [comment]
If I had to guess based on the API you're using, it looks like you're using Vapor's WebSocket package. Is that right?

**Comment by guarland** [comment]
> Yes.
> 
> However, I have no idea what code you have posted: it doesn't appear to be using SwiftNIO directly.

I use a Vapor 3 which uses SwiftNio

```
   /// Private send that accepts a raw `WebSocketFrame`.
   private func send(_ buffer: ByteBuffer, opcode: WebSocketOpcode, fin: Bool, promise: Promise<Void>?) {
        let frame = WebSocketFrame(
            fin: fin,
            opcode: opcode,
            maskKey: mode.makeMaskKey(),
            data: buffer
        )
        channel.writeAndFlush(frame, promise: promise)
    }
```

**Comment by Lukasa** [comment]
So `channel.writeAndFlush` is thread-safe. However, other parts of the Vapor codebase may not be. You should evaluate that codebase to be sure.

**Comment by guarland** [comment]
> So `channel.writeAndFlush` is thread-safe. However, other parts of the Vapor codebase may not be. You should evaluate that codebase to be sure.

thanks, I got it. 

thic code wil be enough 

```
func sendDataToWebSocket(number: String, data: Data)  {() {
            if let webSocket = connections[number] {
                webSocket.send(data, promise: socketPromise)
            } 
}
```
