### ISSUE TITLE
ChannelPipeline remove0(ctx:promise:) takes boolean promise, but only ever fulfills with true

### ISSUE THREAD

**Issue by MrLotU** [apple/swift-nio#747]
## Short Description
This function (https://github.com/apple/swift-nio/blob/nio-1.12/Sources/NIO/ChannelPipeline.swift#L507) takes a `EventLoopPromise<Bool>`, but that promise is only ever fulfilled with `true` which kinda takes away the point of it being a boolean promise.

## Proposed Solution
Replace the `EventLoopPromise<Bool>` with an `EventLoopPromise<Void>` since there lies no further info in the value anyways.

**Comment by Lukasa** [comment]
Agreed. I think it was `Bool` from a previous version of this interface where it may return `false` if the context was not present, but we made that an error instead. This is a good 2.0 change. If you're interested in making the patch, we can change the entire public surface area of `ChannelPipeline.remove` to stop using `Bool` in cases where they are, as well as most of the internals.

**Comment by MrLotU** [comment]
Sure thing! You'll be seeing a PR soon :)

**Comment by weissi** [comment]
fixed this in #767
