### ISSUE TITLE
http1server example memory usage

### ISSUE THREAD

**Issue by tanner0101** [apple/swift-nio#749]
### Expected behavior

`NIOHTTP1Server` example to use < 10MB memory on boot.

### Actual behavior

Memory usage seems high at 47MB on boot.

![screen shot 2019-01-15 at 1 55 45 pm](https://user-images.githubusercontent.com/1342803/51210575-2b058100-18e1-11e9-99ad-2630dc27e332.png)

### Steps to reproduce

1. Generate Xcode project for SwiftNIO master.
2. Run `NIOHTTP1Server` example using latest Swift 5 toolchain.

**Comment by weissi** [comment]
that number sounds also surprisingly high to me, we should investigate

**Comment by Lukasa** [comment]
Also doesn't reproduce for me on the latest toolchain (2019-01-15):

<img width="266" alt="screenshot 2019-01-16 at 08 32 56" src="https://user-images.githubusercontent.com/1382556/51236178-6c417380-1969-11e9-87a3-eac86cefafea.png">

**Comment by Lukasa** [comment]
Doesn't reproduce for me in release mode either.

**Comment by tanner0101** [comment]
Weird. Must be something wrong with my computer. Just to verify, you were using `master` branch, right?

**Comment by Lukasa** [comment]
Yup, master branch, verified I was on the latest commit and everything.

**Comment by tanner0101** [comment]
OK, thanks for looking into it. I'll try to figure out what is up with my machine. 👍
