### ISSUE TITLE
Add support for Dash in reference documentation 

### ISSUE THREAD

**Issue by slashmo** [apple/swift-nio#764]
### Expected behavior
When visiting the [reference documentation](https://apple.github.io/swift-nio/docs/current/NIO/index.html) I expected to find an "Install in Dash" button as that's the case with many other jazzy-generated docs, e.g. [ReSwift](http://reswift.github.io/ReSwift/master).

### Actual behavior
On NIO's [reference documentation](https://apple.github.io/swift-nio/docs/current/NIO/index.html), the "Install in Dash" button is missing.

### Steps to reproduce

1. Open the [reference documentation](https://apple.github.io/swift-nio/docs/current/NIO/index.html)
2. Wonder about the missing "Install in Dash" button 🤓

**Comment by Lukasa** [comment]
Thanks for this! I think #700 should have resolved the production issue here, but the docs need to be regenerated.

One sec.

**Comment by Lukasa** [comment]
Ah, no, normally we push our docs in CI. The upshot here is that this should resolve itself when we tag a new release.

Please re-open if that does not happen.
