### ISSUE TITLE
think about HTTP CONNECT

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#774]
### Expected behavior
We should probably support `CONNECT` in some way shape or form. Turns out you can use swift-NIO with CONNECT (@tanner0101 got it to work) but it could probably be a lot better.

### Actual behavior
no support from NIO, need to mutate the pipeline yourself without assistance.

### SwiftNIO version/commit hash

NIO 1.x & `master` so far

**Comment by tanner0101** [comment]
For reference, the crux of my solution is [here](https://github.com/vapor/http/blob/4/Sources/NetKit/Client/HTTPClientConnection.swift#L57-L73):

```swift
switch proxy.storage {
case .none: break
case .server:
    let proxy = HTTPClientProxyHandler(hostname: hostname, port: port ?? 443) { ctx in
        // re-add HTTPDecoder since it may consider the connection to be closed
        _ = ctx.pipeline.remove(handler: httpResDecoder)
        _ = ctx.pipeline.add(handler: httpResDecoder, after: httpReqEncoder)
        
        // if necessary, add TLS handlers
        if let tlsConfig = tlsConfig {
            let sslContext = try! SSLContext(configuration: tlsConfig)
            let tlsHandler = try! OpenSSLClientHandler(context: sslContext)
            _ = ctx.pipeline.add(handler: tlsHandler, first: true)
        }
    }
    handlers.append(proxy)
}
```

[`HTTPClientProxyHandler`](https://github.com/vapor/http/blob/4/Sources/NetKit/Client/HTTPClientProxyHandler.swift) calls the supplied closure after successfully `CONNECT`ing to the proxy. It then writes any HTTP requests that were buffered while it was waiting.

**Comment by Lukasa** [comment]
As far as I know handling CONNECT is basically the same as handling upgrade, we just don't ship a broad solution to it. Totally fine with adding something.

**Comment by weissi** [comment]
@Lukasa exactly what I was thinking, we should provide help for the `CONNECT` upgrade in same way

**Comment by vkill** [comment]
@weissi The [example](https://github.com/vkill/swift-nio-http-client/blob/master/Tests/NIOHTTPClientTests/HTTPClientTests.swift#L61).

**Comment by weissi** [comment]
I think we can consider this done. [`async-http-client`](https://github.com/swift-server/async-http-client) implements [client support for CONNECT proxies](https://github.com/swift-server/async-http-client/pull/1/files) and we now also have a [`connect-proxy` example](https://github.com/apple/swift-nio-examples/tree/master/connect-proxy) which implements a CONNECT proxy.
