### ISSUE TITLE
remove deprecated functions introduced in #776

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#779]
remove deprecated functions introduced in #776 . #776 introduces deprecated functions because we removed a label into a function that was only introduced in NIO 2. The deprecation should make it much easier for users to track NIO's master. But before tagging 2.0, we really should remove them again.

The functions are in `EventLoopFuture.swift` and _not_ in the `_NIO1APIShims` module.

**Comment by aksswami** [comment]
@weissi I would like to create a PR for this one, but I don't understand the issue completely. 
I am only getting started with swift-nio and would like to contribute back.

**Comment by Lukasa** [comment]
@aksswami This issue isn’t a good first one, as it is mostly a reminder to do a specific job in the future. A great first issue is #720.
