### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by Jamez312** [apple/swift-nio#80]
I'm interested in beginning translating the project into Spanish and I was wondering if I could start pull requests of the files. Many thanks in advance!

**Comment by normanmaurer** [comment]
I am afraid but I think we are currently not on a stage to accept PRs for translations as we can not guarantee that we will be able to keep these up to date to reflect the changes that are done. 

With this in mind I think we should close this for now.

**Comment by normanmaurer** [comment]
@Jamez312 that said thanks for the offer!
