### ISSUE TITLE
conformance to RemovableChannelHandler

### ISSUE THREAD

**Issue by tanner0101** [apple/swift-nio#813]
### Expected behavior

Commonly used types conform to `RemovableChannelHandler`.

### Actual behavior

Need to add conformance myself.

```swift
extension HTTPResponseDecoder: RemovableChannelHandler { }
extension HTTPRequestEncoder: RemovableChannelHandler { }
extension HTTPResponseCompressor: RemovableChannelHandler { }
```

### SwiftNIO version/commit hash

`master` @ `119893182312113a4e1e5bc6c11b576791f7cebc`

### Swift & OS version (output of `swift --version && uname -a`)

```
Apple Swift version 5.0 (swiftlang-1001.0.60.3 clang-1001.0.37.8)
Target: x86_64-apple-darwin18.2.0
ABI version: 0.7
Darwin iMac.home 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
```

**Comment by weissi** [comment]
oops, sorry I missed this. This definitely needs fixing

**Comment by weissi** [comment]
done in #814

**Comment by weissi** [comment]
and https://github.com/apple/swift-nio-extras/pull/33
