### ISSUE TITLE
Provide ChannelHandler that closes Channel on unhandled error.

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio#841]
As we change #600, many users will start leaking Channels because they don't close on error. We should provide a ChannelHandler that closes on unhandled error that is typically added last to the pipeline.

**Comment by weissi** [comment]
see also:

- https://github.com/grpc/grpc-swift/issues/381
- https://github.com/pointfreeco/swift-web/issues/182
- https://github.com/NozeIO/MicroExpress/issues/8
- https://github.com/objcio/swift-talk-backend/issues/103
- https://github.com/PerfectlySoft/Perfect-NIO/issues/6
- https://github.com/vapor/http/issues/334
- https://github.com/amzn/smoke-framework/issues/19
- https://github.com/IBM-Swift/Kitura-NIO/issues/173

**Comment by allright** [comment]
I think this tickets have very similar:
https://github.com/apple/swift-nio/issues/841
