### ISSUE TITLE
improve ChannelPipeline debug print

### ISSUE THREAD

**Issue by tanner0101** [apple/swift-nio#848]
Calling `print` and `debugPrint` on a `ChannelPipeline` currently yields the following output:

```
ChannelPipeline (ObjectIdentifier(0x0000000101f26ea0)):
        handler0 (OpenSSLServerHandler) [IO]
        handler2 (HTTPResponseEncoder) [O]
        handler3 (HTTPRequestDecoder) [I]
        handler4 (HTTPServerRequestDecoder) [I]
        handler5 (HTTPServerResponseEncoder) [O]
        handler6 (HTTPServerUpgradeHandler) [IO]
        handler7 (HTTPServerHandler) [I]
```

This output is very handy, but I think it could be even better. I had some ideas:

- Line up values so it's easier for the eye to scan
- Get rid of redundant info (like repeating `handler` in `handler1`, `handler2`)
- Make incoming vs. outgoing handlers more separated.
- Add arrows so handler order is immediately clear.

Combining these ideas, I came up with this format:

```
ChannelPipeline[0x0000000101f26ea0]:
 #                      [I] ↓↑ [O]
 0     OpenSSLServerHandler ↓↑ OpenSSLServerHandler
 2                          ↓↑ HTTPResponseEncoder
 3       HTTPRequestDecoder ↓↑
 4 HTTPServerRequestDecoder ↓↑
 5                          ↓↑ HTTPServerResponseEncoder
 6 HTTPServerUpgradeHandler ↓↑ HTTPServerUpgradeHandler 
 7        HTTPServerHandler ↓↑
```

Given this print out would require some additional calculations, I think it could make sense under `debugPrint`. But being the default `print` would be even better. 

Thoughts? I'd be happy to submit a PR for this.

**Comment by Lukasa** [comment]
Sounds great, I love it!

**Comment by ktoso** [comment]
Looks awesome, 👍

**Comment by normanmaurer** [comment]
Thats a really cool idea.. I really love the "arrows" :)

**Comment by weissi** [comment]
really awesome, should we still print the `name` somewhere? I realise it's mostly `handlerN` but some people may actually name them?

**Comment by normanmaurer** [comment]
@weissi +1

**Comment by tanner0101** [comment]
PR submitted. I updated the formatting slightly to include the handler name since as @weissi mentioned it may be unique.

**Comment by weissi** [comment]
PR merged, thanks @tanner0101
