### ISSUE TITLE
TCPConnection handlers never deallocated with Atomic (look at Video & use remote server)

### ISSUE THREAD

**Issue by allright** [apple/swift-nio#874]
it is never reproduced on loopback, but only on remote server:
https://github.com/apple/swift-nio/issues/872
please, allow to reopen issues.
video with test:
https://yadi.sk/i/l6xhUmXlRsWQsA

**Comment by Lukasa** [comment]
Please stop opening new issues: I have reopened #872.

**Comment by allright** [comment]
thanks.
