### ISSUE TITLE
Timeout in Promise: What's the best way to have a timeout in the promise?

### ISSUE THREAD

**Issue by guarland** [apple/swift-nio#904]
What's the best way to have a timeout in the promise?

For example, if within 2 seconds there is no success, then execute PromiseBlaBla.fail(error: ...)

**Comment by Lukasa** [comment]
The general way to do this is to do something like this:

```swift
eventLoop.scheduleTask(in: .seconds(2)) {
    promise.fail(error: ...)
}
```

If you do that, you can also cancel this task from within the promise callback if you're so inclined by closing over the return value of `scheduleTask`.

If this is something you do regularly, you may want to wrap this in a helper.

**Comment by guarland** [comment]
Thanks Cory, that's what i needed, 

How can i cancel the task returned by scheduleTask?

**Comment by guarland** [comment]
> The general way to do this is to do something like this:
> 
> ```swift
> eventLoop.scheduleTask(in: .seconds(2)) {
>     promise.fail(error: ...)
> }
> ```
> 
> If you do that, you can also cancel this task from within the promise callback if you're so inclined by closing over the return value of `scheduleTask`.
> 
> If this is something you do regularly, you may want to wrap this in a helper.

**Comment by Lukasa** [comment]
Yup, that’s right.
