### ISSUE TITLE
eventLoop.scheduleTask limit 

### ISSUE THREAD

**Issue by guarland** [apple/swift-nio#922]
Are there any restrictions on use eventLoop.scheduleTask ? 

after 20 times the execution of this code the system hangs

```swift 
 let requestScheduled = req.eventLoop.scheduleTask(in: .seconds(2)) {
                    someMyFunction()
       }
```

after i added this code that deinit scheduleTask, everything works fine

```swift 
   requestScheduled?.cancel()
   requestScheduled = nil
```

but I am afraid that there will be delays when there are numerous requests,  are there any restrictions on use eventLoop.scheduleTask ?

**Comment by weissi** [comment]
@guarland So first of all: There are no limits. When you say the system hangs, what exactly do you mean, are you saying no more scheduled tasks are executed?

If yes, are you on macOS? If yes, could you run

    sample NameOrPIDOfYourProgram > ~/Desktop/stuck.sample

and then send the file `stuck.sample` on your Desktop? Let's assume your binary is called `App`, then you should be able to run

    sample App > ~/Desktop/stuck.sample

Also, you mention 'there will be delays when there are numerous requests', what exactly do you mean with that?

And lastly: What version of NIO are you using? Could you maybe paste your `Package.resolved`? Also maybe you could paste the code from `someMyFunction()`

**Comment by Lukasa** [comment]
Closing for inactive.
