### ISSUE TITLE
Backport. #752 to nio 1

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#934]
We should backport #752  to nio 1. Does  not matter in production but it just makes debugging unnecessarily hard...

**Comment by Palleas** [comment]
@weissi does that mean backporting in all the nio-1.x branches?

**Comment by weissi** [comment]
@Palleas no, we only need that for `nio-1.13`

**Comment by weissi** [comment]
this is done in #987

**Comment by weissi** [comment]
shipped in 1.14.1
