### ISSUE TITLE
NIO should provide some memory stats stuff

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#936]
NIO’s `System` type could be a great place to have a function that returns allocator statistics like `mallinfo` on Linux.

We could start with a OS-specific `String` representation that our users could `print`/log  say on receipt of a signal.

Example: the webservers could implement something that when `SIGUSR1` is received, the call the method suggested here and print the output. Then (for example for Vapor) users could use

    pkill -USR1 Run

And get the stats logged.

CC @tanner0101

**Comment by ianpartridge** [comment]
Are you sure it's ok to call mallinfo() inside a signal handler? I know malloc() isn't allowed, because the program could be halfway through a malloc() when the signal happens.

**Comment by Lukasa** [comment]
It’s not really safe to call almost anything in a signal handler. However, you can call things *in response to a signal*: you usually do this by doing the write-to-self-pipe trick. Or just use DispatchSources, which essentially does the safe thing too.

**Comment by ianpartridge** [comment]
> write-to-self-pipe trick

Qué? 😁

**Comment by weissi** [comment]
Write 1 byte to a pipe when the signal was triggered (in the handler). Elsewhere, just have a DispatchSource/epoll/kqueue/select waiting for writes on that pipe.

But as Cory says, DispatchSource.makeSignalSource is the right answer. That does the right thing.

**Comment by ianpartridge** [comment]
Cool, thanks.

**Comment by tanner0101** [comment]
This seems like a great idea.

**Comment by weissi** [comment]
Might be a better fit in swift-metrics: https://github.com/apple/swift-metrics/pull/61

**Comment by FranzBusch** [comment]
@weissi Can we close this issue since we are having this functionality in swift-metrics-extras now?

**Comment by weissi** [comment]
@FranzBusch Yes, I'm +1 on closing this. NIO shouldn't provide everything you might possibly need (although that was kinda the case in the old days).

This indeed sounds like functionality that could be exposed through Metrics and probably gathered with APIs from SwiftSystem?

**Comment by FranzBusch** [comment]
It is exposed to Metrics but not using SwiftSystem. It should be straight forward to use with this package: https://github.com/apple/swift-metrics-extras
