### ISSUE TITLE
Some performance questions regarding memory allocations

### ISSUE THREAD

**Issue by fadi-botros** [apple/swift-nio#942]
### Expected behavior
Using some kind of customized GC (yes, Swift is not GC based, but custom GCs could be made for different level of objects, we must be noted that using Swift has a lot of reasons including escaping the Java's VM and GC), or object pooling to handle the creation of a lot of `class` which is on the heap. Also it could be `struct`s not `class`es for saving on the stack (and to be easier customizable because using `MemoryLayout` and `UnsafeRawPointer.bindMemory` is easier in `struct`s).

Also why not making a Java style string allocation system ? Yes, most of the string handling here is low-level either using C or using `ByteBuffer`s, but what about user strings ?

### Actual behavior
`class`es are used in a lot of parts.

**Comment by weissi** [comment]
@fadi-botros Thank you but `String`s are not part of SwiftNIO and `String`s are `struct`s already, in many cases however backed by a `class`. If you have suggestions on how to improve Swift's memory management or Swift's allocation strategies, please file a bug at https://bugs.swift.org .

**Comment by fadi-botros** [comment]
Sorry for answering on a closed issue, but I don't mean only strings, SwiftNIO is an asynchronous framework which makes stack allocation impractical because you need to escape values from a cycle in the event loop to the next cycle. Heap allocations is slow in Swift because it is a non-GC non-VM language, and introducing real GC in Swift itself (i.e. changing Swift's allocation strategies) would make it more Java or Go like, which is not desirable.   But my suggestion is making small simple object pool or group of small custom GCs for the asynchronous operations and its data (i.e. channels, futures, strings, temporary dictionaries), like the abstraction we already have in the `ByteBufferAllocator` we would have allocators for every short lived object that needs to escape the stack to the "heap", so that those allocators could be implemented using faster techniques, like pooling.
