### ISSUE TITLE
[Discussion] Would tagging a 1.14 version be an option?

### ISSUE THREAD

**Issue by MrMage** [apple/swift-nio#945]
https://github.com/apple/swift-nio/pull/943 brings significant performance gains for processing large arrays of smallish, mostly already-fulfilled futures, which is a common pattern in e.g. template rendering. However, due to versioning constraints, Vapor 3 is tied to NIO 1. Vapor 4 (based on NIO 2), on the other hand, is not available yet, which means that Vapor users would be missing out on these performance gains for a while.

If we backported `whenAllSucceed` to NIO 1, we could take advantage of that by modifying its [`flatten`](https://github.com/vapor/core/pull/199) method to call through to `whenAllSucceed`, providing another ~3x speedup compared with https://github.com/vapor/core/pull/199.

However, `whenAllSucceed` is currently not available at all in NIO 1, which means that backporting it to NIO 1 would require a „feature-adding“ SemVer minor update. I’m filing this issue to discuss whether that would be an option at all.

/cc @weissi @tanner0101

**Comment by Lukasa** [comment]
I am not opposed to tagging reasonable minor version bumps for as long as we are supporting Swift 4.2. My real question is whether @tanner0101 would actually use the feature if we backported it.

**Comment by tanner0101** [comment]
@MrMage would `whenAllSucceed` improve performance beyond what https://github.com/vapor/core/pull/199 does already? (That PR has been merged and tagged as Core 3.8.0 now).

**Comment by MrMage** [comment]
@tanner0101 yes, in a quick experiment replacing `flatten` with the new version of `whenAllSucceed` provides _another_ 3x speedup, mostly because the compiler can better optimize away overhead intra-module, but also because we then have access to NIO-internal methods.

**Comment by tanner0101** [comment]
It would be worth a patch to vapor/core then IMO. `flatten()` is used everywhere.

**Comment by weissi** [comment]
cool, I'm +1 on for a 1.14 then :)

**Comment by weissi** [comment]
done
