### ISSUE TITLE
 get a ByteBuffer (slice) from a ByteBufferView

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#946]
There’s no reason we don’t provide a way to  get a ByteBuffer (slice) from a ByteBufferView.

**Comment by slashmo** [comment]
I'd love to try and implement this feature. Could you elaborate a bit more on what it's about? As far as I understood one should get a `ByteBufferSlice` from a `ByteBufferView` by sub-scripting the view, similar to how sub-scripting an `Array` returns an `ArraySlice`. Is that correct?

**Comment by tanner0101** [comment]
@slashmo yes that's correct. Except that there is no separate `ByteBufferSlice` type. A slice of a `ByteBuffer` is still a `ByteBuffer`. So basically there should be a way to convert a `ByteBufferView` to a `ByteBuffer` where the readable bytes are the same.

**Comment by weissi** [comment]
Thanks @tanner0101! Thanks @slashmo ! I think you could take the indices stored in the ByteBufferView and then call getSlice on the ByteBuffer that is also stored in the ByteBufferView with the startIndex and appropriate length.
