### ISSUE TITLE
Improve docs by enabling jumping to the GitHub definition of APIs

### ISSUE THREAD

**Issue by adtrevor** [apple/swift-nio#955]
Jazzy enables to display a `Show on GitHub` in the section of each method/property. This makes it much easier to browse APIs implementation directly online but isn't currently enabled on the NIO docs.

Thank you! 🙂

**Comment by adtrevor** [comment]
Maybe `--github-file-prefix` is the option to use but I'm not 100% sure.

**Comment by weissi** [comment]
@adtrevor I tried `--github-file-prefix` with various combinations

- `--github-file-prefix "https://github.com/apple/swift-nio/tree/$version/"`
- `--github-file-prefix "https://github.com/apple/swift-nio/tree/$version/$module/"`
- `--github-file-prefix "https://github.com/apple/swift-nio/tree/$version/$module/Sources/"`

but nothing worked :(. Maybe @jpsim can help us figure this out?

**Comment by adtrevor** [comment]
@weissi Hmmm... I had looked for it online and indeed I didn't find any answer either.

It's enabled in the docs of Vapor though (cc: @tanner0101 )

**Comment by weissi** [comment]
Oh yay! That’s great news, that means we can can it fixed somehow. @tanner0101 to the rescue 😁

**Comment by jpsim** [comment]
`--github-file-prefix` is definitely the correct way to enable this, and I've filed a PR enabling this at https://github.com/apple/swift-nio/pull/977. There's a GIF demonstrating that it works as intended as well.

**Comment by weissi** [comment]
should be fixed by #977 , when we next release we'll see if everything worked.
