### ISSUE TITLE
Docs on GitHub Pages for "current" is for Version 1.14

### ISSUE THREAD

**Issue by bluk** [apple/swift-nio#971]
### Expected behavior

I expected https://apple.github.io/swift-nio/docs/current/NIO/ to show docs related to the latest major version.

### Actual behavior

It seems the 1.14.0 docs were published to the `current` directory.

https://github.com/apple/swift-nio/commits/gh-pages/docs/current shows that the 1.14.0 docs were published over the 2.0.0 docs a couple of days ago in https://github.com/apple/swift-nio/commit/9b739a9576146fe87be28ee270475f5941b524ed . I don't know if this was intentional or just due to some automated publishing script.

### Steps to reproduce

Visit https://apple.github.io/swift-nio/docs/current/NIO/  .

**Comment by Lukasa** [comment]
This looks like a script bug somewhere. It seems that we're publishing `current` to the most recently tagged minor release, even where that minor release is on a maintenance branch rather than the current tip. @tomerd I think this is something you own?

**Comment by weissi** [comment]
There are two bugs: `1.14.0` is current & `2.0.1` isn't generated at all. Some CI weirdness

**Comment by weissi** [comment]
I kicked off the CI build again, hoping that it'll generate 2.0.1 and mark it 'current'

**Comment by weissi** [comment]
didn't work, need @tomerd's help

**Comment by weissi** [comment]
This is fixed now, thanks @tomerd
