### ISSUE TITLE
Assert hit on 32 bit machines 

### ISSUE THREAD

**Issue by tgu** [apple/swift-nio#972]
https://github.com/apple/swift-nio/blob/e32a436466b01d4d45555356eb5bbdcdf14b4526/Sources/NIO/CircularBuffer.swift#L83

**Comment by Lukasa** [comment]
Yes, that assertion seems somewhat bogus. @weissi this went in in #909, any reason for it?

**Comment by weissi** [comment]
@Lukasa I put that in during development and forgot to remove, apologies. We could probably could alter it to `== MemoryLayout<Int64>.size`
