### ISSUE TITLE
Improve release process

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#973]
Currently, the SwiftNIO release process is pretty makeshift and usually consists of @Lukasa and/or @weissi running the following manual procedure:

1. running `swift-nio-release-tools` (a terrible script that tests NIO dependents and isn't OSS yet because it contains internal projects too)
2. ~~doing a manual `git diff` check if we actually didn't break the API and in case of patch releases we check that we didn't add any functionality~~
3. tagging the version
4. go to https://github.com/apple/swift-nio/releases, enter tag & write release notes

Steps 2 to 4 are very manual and things really can go wrong. We should be able to do much better with more automation.

**Comment by Lukasa** [comment]
We have now automated all 4 of these steps.
